### PR TITLE
Width and Height params made non-negative for Opengl's Scissor Call

### PR DESCRIPTION
**Pull request by ranjith-bhide**
Fixes (#2814)

 

### Description:

Fixes (#2814)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks for working on this. Are you sure it’s the correct fix though? A negative scissor is certainly wrong, but a 0 scissor would result in nothing shown, so should we skip rendering it?

**Comment by ranjith-bhide** [comment]
> so should we skip rendering it?

Yes, That is what is expectated.
and this would be one way of getting OpenGL Scissors to do it for us, following the generic design.

**Comment by andydotxyz** [comment]
Looks to me like you found it :) yes indeed the clip stack is something to consider.
I guess you could push/pop the stack but just skip the paint call when rect is 0? Possibly could even skip the scissor open and close as they both know if the rectangle is 0 right?

**Comment by andydotxyz** [comment]
> as in the afterPaint function the pop happens unconditionally for all scrollable objects, hence the pop may happen at an incorrect point.

I'm not sure about this - the afterPaint has the same opportunity to check the size of the object in the (cache) node?
Checking for zero size in both methods would assume the size does not change during walk but that seems reasonable.
Or have I missed something?

**Comment by ranjith-bhide** [comment]
> I'm not sure about this - the afterPaint has the same opportunity to check the size of the object in the (cache) node?
Checking for zero size in both methods would assume the size does not change during walk but that seems reasonable.
Or have I missed something?

Sorry I was probably not clear when I mentioned the root cause.
It is not that the Object Itself is having the Width/Height as negative value. Its the `inner` rectangle which is the intersection of the parent Scroll object and the child Scroll Object that gets a negative width/height.
Screenshot from 2022-04-04 23-34-41

And as we are storing this `inner` variable only in the clips stack and nowhere else. if we do not push this to stack I dont think we will be able determine when this particular Object's `afterPaint` is getting called.

I hope this make sense @andydotxyz.

**Comment by andydotxyz** [comment]
Ah yes thank you, I should have noticed sorry. I guess this is about the simplest fix for a complex problem then :)

**Comment by ranjith-bhide** [comment]
> Ah yes thank you, I should have noticed sorry. I guess this is about the simplest fix for a complex problem then :)

I may be suggesting almost the same thing again, but the simplest fix for this problem I see is this:
```diff
diff --git a/internal/clip.go b/internal/clip.go
index d8983ce8..da8fbcd5 100644
--- a/internal/clip.go
+++ b/internal/clip.go
@@ -58,24 +58,28 @@ func (i *ClipItem) Rect() (fyne.Position, fyne.Size) {
 // Intersect returns a new clip item that is the intersection of the requested parameters and this clip.
 func (i *ClipItem) Intersect(p fyne.Position, s fyne.Size) *ClipItem {
        ret := &ClipItem{p, s}
        if i == nil {
                return ret
        }
 
        if ret.pos.X < i.pos.X {
                ret.pos.X = i.pos.X
                ret.size.Width -= i.pos.X - p.X
        }
        if ret.pos.Y < i.pos.Y {
                ret.pos.Y = i.pos.Y
                ret.size.Height -= i.pos.Y - p.Y
        }
 
        if p.X+s.Width > i.pos.X+i.size.Width {
                ret.size.Width = (i.pos.X + i.size.Width) - ret.pos.X
        }
        if p.Y+s.Height > i.pos.Y+i.size.Height {
                ret.size.Height = (i.pos.Y + i.size.Height) - ret.pos.Y
        }
+
+       /* Ensure Intersection Area Height and Width are always non-negative */
+       ret.size = ret.size.Max(fyne.NewSize(0, 0))
+
        return ret
 }
```

Here Im trying to ensure that the Returned rectangle of Intersection is always maintained to be of non-negative width and height. Because saying that the intersection of 2 rects have a negative length is absurd.
And thus this makes a bit more logical sense than simply seeming like a work-around (as in my original commit)

@andydotxyz Let me know if this makes sense, Ill update the PR.

**Comment by andydotxyz** [comment]
Using this simple fix will not stop us from drawing the items that should not be visible. It is simpler but it does not save lost performance, which is a shame.

Instead of having a comment to explain code we prefer code that explains itself, so I would consider this alternative:
```go
       if ret.size.Width < 0 || ret.size.Height < 0 {
              return fyne.NewSize(0, 0)
       }
```

This code is clear in its intent - check for invalid sizes and return 0

**Comment by ranjith-bhide** [comment]
> Using this simple fix will not stop us from drawing the items that should not be visible. It is simpler but it does not save lost performance, which is a shame.

Hi @andydotxyz. I spent a bit more time, and I see one way to actually achieve that performance optimisation. :) 
Let me know what you think.
```diff
index d8983ce..15e2afc 100644
--- a/internal/clip.go
+++ b/internal/clip.go
@@ -58,24 +58,30 @@ func (i *ClipItem) Rect() (fyne.Position, fyne.Size) {
 // Intersect returns a new clip item that is the intersection of the requested parameters and this clip.
 func (i *ClipItem) Intersect(p fyne.Position, s fyne.Size) *ClipItem {
 	ret := &ClipItem{p, s}
 	if i == nil {
 		return ret
 	}
 
 	if ret.pos.X < i.pos.X {
 		ret.pos.X = i.pos.X
 		ret.size.Width -= i.pos.X - p.X
 	}
 	if ret.pos.Y < i.pos.Y {
 		ret.pos.Y = i.pos.Y
 		ret.size.Height -= i.pos.Y - p.Y
 	}
 
 	if p.X+s.Width > i.pos.X+i.size.Width {
 		ret.size.Width = (i.pos.X + i.size.Width) - ret.pos.X
 	}
 	if p.Y+s.Height > i.pos.Y+i.size.Height {
 		ret.size.Height = (i.pos.Y + i.size.Height) - ret.pos.Y
 	}
+
+	if ret.size.Width < 0 || ret.size.Height < 0 {
+		ret.size = fyne.NewSize(0, 0)
+		return ret
+	}
+
 	return ret
 }
diff --git a/internal/driver/glfw/canvas.go b/internal/driver/glfw/canvas.go
index a632f9c..4b12c73 100644
--- a/internal/driver/glfw/canvas.go
+++ b/internal/driver/glfw/canvas.go
@@ -265,30 +265,38 @@ func (c *glCanvas) overlayChanged() {
 func (c *glCanvas) paint(size fyne.Size) {
 	clips := &internal.ClipStack{}
 	if c.Content() == nil {
 		return
 	}
 	c.SetDirty(false)
 	c.Painter().Clear()
 
 	paint := func(node *common.RenderCacheNode, pos fyne.Position) {
 		obj := node.Obj()
 		if _, ok := obj.(fyne.Scrollable); ok {
 			inner := clips.Push(pos, obj.Size())
 			c.Painter().StartClipping(inner.Rect())
 		}
+
+		if visible_area := clips.Top(); visible_area != nil {
+			_, paint_area := visible_area.Intersect(pos, size).Rect()
+			if paint_area.Width <= 0 || paint_area.Height <= 0 {
+				return
+			}
+		}
+
 		c.Painter().Paint(obj, pos, size)
 	}
 	afterPaint := func(node *common.RenderCacheNode) {
 		if _, ok := node.Obj().(fyne.Scrollable); ok {
 			clips.Pop()
 			if top := clips.Top(); top != nil {
 				c.Painter().StartClipping(top.Rect())
 			} else {
 				c.Painter().StopClipping()
 
 			}
 		}
 	}
 
 	c.WalkTrees(paint, afterPaint)
 }

```

**Comment by andydotxyz** [comment]
Yeah looks great @ranjith-bhide

**Comment by ranjith-bhide** [comment]
Hi @andydotxyz, I've updated the PR with changes okayed by you, Please take it forward for approval and merge.

**Review by andydotxyz — APPROVED** [review]
Excellent, thanks

**Pull request merged**
