### PR TITLE
widget.Form: implement Disableable

### LINKED ISSUE #2157: form: allow disabling submission
### Is your feature request related to a problem? Please describe:

I'd like to be able to disable the `widget.Form` submit button, when my app is doing something in the background (like sending data to a server) and the user shouldn't be able to run it again.

### Is it possible to construct a solution with the existing API?

I suppose you could set a fake ValidationError, but that seems a bit of a hack.

### Describe the solution you'd like to see:

Expose disabling/enabling `Form.submitButton`.

### PR DESCRIPTION
**Pull request by markspolakovs**
### Description:
Allow disabling and re-enabling a form.

Fixes #2157.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [n/a] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by markspolakovs** [comment]
Static analysis failure looks like a flake:

```
  Running [/home/runner/golangci-lint-1.37.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

Not sure about the travis failures on Windows, this PR doesn't touch that code (in theory).

**Comment by Jacalz** [comment]
> Static analysis failure looks like a flake:
> 
> ```
>   Running [/home/runner/golangci-lint-1.37.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
>   level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
>   level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
> ```
> 
> Not sure about the travis failures on Windows, this PR doesn't touch that code (in theory).

It should be fixed with https://github.com/fyne-io/fyne/pull/2155. Travis shouldn’t even be running, but we got some free tokens so our old instance fired up again. Removed as of that PR.

**Comment by andydotxyz** [comment]
Yes, if you can pull in latest `develop` then the test failures should be fixed.
Also please annotate the new public methods with:
```go 
//
// Since: 2.1
```

**Review by andydotxyz — APPROVED** [review]
Nice work thanks

**Pull request merged**
