### PR TITLE
Update menu, dialog, overlay to new theme definition

### PR DESCRIPTION
**Pull request by andydotxyz**
A few test fixups found along the way too

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
This looks very good but the tests seem strange. The workflows seem to not be firing for some reason?

**Comment by andydotxyz** [comment]
> This looks very good but the tests seem strange. The workflows seem to not be firing for some reason?

Weird. I kicked it with an empty commit

**Comment by andydotxyz** [comment]
Sorry @Jacalz for some reason I am having git issues in that it removes, instead of overwriting, files when I try to replace them.
Hopefully it's correct now (moved to a different computer)

**Review by Jacalz — APPROVED** [review]
Thanks. Looks good to me :+1:

**Pull request merged**
