### PR TITLE
Refresh during resize

### LINKED ISSUE #531: canvas.Image and canvas.Raster textures are not refreshed while actively resizing window.
**Describe the bug**
canvas.Image and canvas.Raster objects that are resized when the window is being resized do not have their underlying textures updated while the window is actively being resized (i.e. border hotspot is being dragged). When hotspot is released to "finish" the resize, only then is the texture actually updated. During resize, if we go from a small size to a larger size, there is noticeable blurriness as the smaller resolution image is scaled up to fill the larger area (this looks very much to me like it is OpenGL doing the scaling, as the visual quality reminds me of old 3D games with low resolution textures). I first noticed this in my own app, in which I was experimenting with using a canvas.Raster object created with NewRaster(generate func(w, h int) image.Image) to supply the image on demand using my own function (neat idea, by the way). I could see while debugging that canvas.Refresh() was being called for my canvas.Raster object every time it changed size, but canvas.Refresh() would not trigger my generate function to be called until after the window border was released.

I then checked to see if the demo exhibited similar behavior, and it did. I'm making an assumption that it uses canvas.Image to display SVG images.

**To Reproduce**

1. Build and run Fyne demo in a desktop environment (seen on Windows 10).
2. Go to tab with icon selector / display.
3. Start with a small window and drag border to increase window size.
4. Observe that icon appears blurry until mouse is released to finish resize.

**Screenshots**
Can add later if necessary.

**Device (please complete the following information):**
I am opening this issue at a time when I don't have easy access to my development system (sorry). I can update with more information in a week or so if reproduction is a problem.
 - OS - Windows 10, kept up to date, but don't have access to look at build number currently.
 - Go version - Unsure at present, sorry. It could be 6-12 months old.
 - Fyne version - Whatever was pulled with "go get fyne.io/fyne" as of mid to late last week.

### PR DESCRIPTION
**Pull request by windexlight**
**Description**

I spent some time debugging to try to find the source of #531, and found that the root cause seems to be related to [glfw.PollEvents()](https://github.com/fyne-io/fyne/blob/1df1ac1c3bae631e0300e53c653a82ad745c89a5/internal/driver/glfw/loop.go#L84) blocking while the window is being actively resized (see glfw/glfw#408 and glfw/glfw#424). While this call blocks, [freeDirtyTextures()](https://github.com/fyne-io/fyne/blob/1df1ac1c3bae631e0300e53c653a82ad745c89a5/internal/driver/glfw/loop.go#L131) is never called, which has the effect of textures not being updated. Unsure if this is intentional behavior or not, but I don't see scaling content during resize to be desirable in most cases. The recommended fix referenced by the glfw issues seems to be to do processing in window refresh callbacks, which are already present in fyne. I therefore added a call to freeDirtyTextures() in [glfw/window.go>window.refresh()](https://github.com/fyne-io/fyne/blob/1df1ac1c3bae631e0300e53c653a82ad745c89a5/internal/driver/glfw/window.go#L473). Since freeDirtyTextures() used a *glDriver receiver that was never referenced in the function body, I simply removed the receiver to make it easily callable from window.refresh(). If this is not desirable, another means could be found to obtain a glDriver instance from window.refresh().

Further, I wanted to add a flag to objects so they could be selectively refreshed during resize, instead of all or none. I accomplished this by adding a method signature to CanvasObject called SkipRefreshDuringResize(), which returns a bool, and implementing this in all the necessary places. Most implementations (including BaseWidget) use a public bool field called RefreshDuringResize, which is returned (inverted) from SkipRefreshDuringResize(). This has the effect of all objects defaulting to not being refreshed during resize. There could be some "gotcha" places where widgets maintain lists of child CanvasObjects, and the flag doesn't get propagated from the parent. I ran into this (and fixed it using an alternate constructor) for Icon, but possibly there are other places that might need attention.

The selective freeing of dirty textures is accomplished by modifying freeDirtyTextures() to:
- Take a new bool parameter called "resizing". When called from [repaintWindow()](https://github.com/fyne-io/fyne/blob/1df1ac1c3bae631e0300e53c653a82ad745c89a5/internal/driver/glfw/loop.go#L116), false is passed for resizing. When called from window.refresh(), true is passed.
- Do not execute canvas.painter.Free(obj) if resizing true and obj.SkipRefreshDuringResize() is true.
- If any of the above calls to Free() are skipped, add the root object (the one retrieved from canvas.refreshQueue) to a map to mark it as needing to be re-added to the queue.
- At the end of the function, use the map to re-add all objects still needing refresh to refreshQueue by calling canvas.Refresh().

I'm not in love with the above approach, as it means a lot of reading objects off the refreshQueue channel just to put them back. Would be better if there was some means of peeking objects instead of just removing them, but as best I can tell, this isn't possible with channels. Could think about using a different data structure (a slice?), but unsure if a channel is being used because of concurrency considerations (is it?).

I updated the fyne_demo app to refresh the big icon on the Graphics tab during resize, but not the checkered background, to demonstrate that some objects can be refreshed while others aren't.

Anyway, I've tested this on Windows 10 1903 (18362.476), and macOS Catalina 10.15.1. I don't have a Linux system to test on at present, or any mobile platforms.

Fixes #531

**Checklist**

- [x] Tests included - where it seemed appropriate/reasonable
- [x] Lint and formatter run with no errors
 Note: I think so, but not 100% sure exactly what to run to check this. I'm using VSCode with the Go extension, which I believe does auto linting and formatting, and I don't see it complaining about anything. I tried running "gofmt -w ." as suggested [here](https://github.com/fyne-io/fyne/wiki/Contributing), on the root of my local fyne repo, and it made 771 changes according to git (looks like changes to every file), so I'm not sure what I'm doing wrong there.
- [x] Tests all pass

(where applicable)

- [x] Public APIs match existing style - I think so, but open to discussion.
- [ ] Any breaking changes have a deprecation path or have been discussed - NA

### CODE REVIEW

**Comment by windexlight** [comment]
The thought just occurred to me that adding a method to CanvasObject could be a breaking change for anyone who has implemented a custom CanvasObject. Probably not desirable. I imagine there is a cleverer and less obtrusive way to tackle it by looking only for specific types of CanvasObject in freeDirtyTextures(), or by using a new interface type.

**Comment by andydotxyz** [comment]
Thanks for  looking into this - you are right the GLFW call hangs on resize, this is due to many operating systems suspending application event processing during this. You are quite right we have a workaround in place already so that could be re-used to trigger cache resets.

For the selective refresh I am not sure I see why it is required? It seems like a platform specific optimisation infecting the API of every single element we draw - if there is something to address then is there a better way to do it?

**Comment by windexlight** [comment]
The purpose of selective refresh would be to give the app developer freedom to choose how they want their app to behave. For some objects it might make sense not to redraw them while resizing, while for others, it’s really needed.

I think I was a little too heavy handed with my approach here, as I commented above. My thought now is to add a new interface, maybe something called LiveResizable, with two methods to get and set the flag. This could then be implemented only where it makes sense. In freeDirtyTextures, the flag would be checked only where objects implement LiveResizable, and would otherwise default to not live resizable. Probably just making BaseWidget, Container, Raster, and Image implement this would be enough. The flag could propagate to children automatically.

All that said, if there is appetite to just make everything live resizable across the board, that is certainly easier, and means no changes to any public APIs.

**Comment by andydotxyz** [comment]
I would imagine that, in the spirit of the smallest change possible, we could make live resize the standard (as that is mostly desired). Later, if there is need, we could look at another PR to add such a flag to determine whether or not this should apply to each canvasobject?

**Comment by windexlight** [comment]
Closing in favor of a new PR that will do global live resize only.

**Pull request closed without merging**
