### PR TITLE
Add support for go modules

### PR DESCRIPTION
**Pull request by lucor**
This PR will add support for go modules. 
go.mod has been created and modified to have same version as per libraries in `vendor` folder.

Note: tested only on linux (ubuntu 18.10)

## Test the PR locally
1. clone the PR branch outsite GOPATH
2. go test ./...
3. go build ./...
4. go test all

## Test the PR locally with a sample app

1. Create a project folder outside GOPATH (i.e. /tmp/test)
2. Create a go.mod file like below

```
module test
go 1.12
require fyne.io/fyne v0.0.0
replace fyne.io/fyne => github.com/lucor/fyne feature/modules
```

3. Create a fyne app (i.e. copy cmd/fyne/hello.go)
4. Run `go build`

### CODE REVIEW

**Comment by komuw** [comment]
maybe also add it to ci; https://github.com/fyne-io/fyne/blob/develop/.travis.yml

**Comment by lucor** [comment]
@komuw good catch thanks.

Before updating the travis file, I've some question I'd like to discuss.

a) should we still publish `vendor` folder ?
I'd say yes, at least until go mod is widely used and the effort to maintain up-to-date is not so high.
Right now, to reset the vendor content the following steps are required with go mod:
```
cd $FYNE_ROOT
go mod vendor
cp -Rf $GOPATH/pkg/mod/github.com/go-gl/glfw@<version>/v3.2/glfw/glfw ./vendor/github.com/go-gl/glfw/v3.2/glfw
find ./vendor/github.com/go-gl/glfw/v3.2/glfw -type d  | xargs chmod 755
find ./vendor/github.com/go-gl/glfw/v3.2/glfw -type f  | xargs chmod 644
```
> Note the steps related to the glfw source code are needed since `go mod vendor` [does not handle directories without a .go file inside](https://github.com/golang/go/wiki/Modules#some-needed-files-may-not-be-present-in-populated-vendor-directory). Probably this won't be required when glfw will add go mod support as per https://github.com/go-gl/glfw/issues/240. In the mean time a script or a fyne command could help to automate.

b) in travis which is the preferred way to test ?

1. checking out the project under $GOPATH and use the vendor folder (current configuration)
2. checking out the project outside $GOPATH  and use the vendor folder via the `-mod=vendor` [flag](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away)
3. checking out the project outside $GOPATH

Points 2 and 3 should drop test against 1.10 currently supported.

Thoughts ?

**Comment by andydotxyz** [comment]
Hi

a) yes - we should keep it for non-module folk
b) I don’t really know enough about modules, but do we need to test 1 and 3?

**Comment by lucor** [comment]
> Hi
> 
> a) yes - we should keep it for non-module folk

ok

> b) I don’t really know enough about modules, but do we need to test 1 and 3?

I was thinking the same, probably for us point 2 is the way to go. It should help to check vendor folder is up-to-date and reduce test time (no need to download dependencies).

If ok with the above, I'd proceed to:
- update travis.yml configuration as per point 2 (dropping 1.10 testing as well)
- add an utility to sync vendor folder (adding a `vendor` command to the fyne app?)

**Comment by andydotxyz** [comment]
That sounds fine, but I don’t think that it makes sense to add a vendor command in Fyne - this is just an internal utility surely?

**Comment by lucor** [comment]
Right. What about `cmd/internal` (`go run cmd/internal/main.go vendor`) or similar? 
Alternatively we'd have a bash script / makefile ... ?

**Comment by andydotxyz** [comment]
I think that cmd/*/ is part of the public binary list. What about doing something like the theme/gen.go - a script in the (vendor?) directory that can update the content? Alternatively we could add a scripts folder as some other projects have done

**Comment by lucor** [comment]
Ok. I'll do some tests but I think we can't have the script into vendor due to `go mod vendor` that resets the folder content. Anyway if not possible I'll add it into `scripts` using the fyne command as reference ;)

**Comment by andydotxyz** [comment]
Maybe take inspiration from https://github.com/golang-standards/project-layout/blob/master/README.md

**Pull request merged**
