### PR TITLE
Hide trailing List separator

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:
A simpler version of #1475 - maybe we can land this more quickly to get the release out?
Smaller changes, also matches the height of table/tree by adding separator size to the item content

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — DISMISSED** [review]
Looks good to me :+1:

**Comment by Jacalz** [comment]
Looks like there are conflicts with the base branch that needs to be resolved first.

**Comment by andydotxyz** [comment]
Yes sorry about that somehow the branch was based on a day or two back. 
Apologies for the force-push but it was much simpler to code and probably re-review than the merge!

**Review by Jacalz — APPROVED** [review]

**Comment by andydotxyz** [comment]
No longer needed

**Pull request closed without merging**
