### PR TITLE
Fix: filter out shortcut triggers where key-modifier is same

### LINKED ISSUE #2148: Don't create empty shortcuts
### Describe the bug:
When typing out a keyboard shortcut like "Ctr-A", first an empty "-Ctrl" shortcut is sent, which should not be

### To Reproduce:
Steps to reproduce the behaviour:
1. Implement `TypedShortcut`
2. Print the content of any `desktop.CustomShortcut`
3. Notice that the first is always listing `LeftControl` or `RightControl` as the `KeyName`

### Device (please complete the following information):
 - **OS:** darwin
 - **Version:** Catalina
 - **Go version:** 1.16
 - **Fyne version:** 2.0.2

### PR DESCRIPTION
**Pull request by AnkushJadhav**
### Description:
Shortcuts triggered an event to the queue for the shortcut's modifier key press. Added a filter to prevent the modifier key press from triggering the shortcut callback.

Fixes #2148

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
This is a great fix thanks, would it be possible to add a test that shows the shortcut is no longer sent to an Entry?

**Comment by andydotxyz** [comment]
Oh one other thought - we try to keep method names in alphabetical order (grouped by type) so the new method probably belongs further down the file.

**Comment by AnkushJadhav** [comment]
Thanks. Will make the changes and update the PR asap. Since the fix is applicable for any component on the window that implements `TypedShortcut`, should the test for this be on `window` or on the `entry` widget?

**Comment by AnkushJadhav** [comment]
@andydotxyz Added tests to a generic implementation of `Shortcutable` instead of entry, as the code change impacts all implementations of `Shortcutable`

**Review by andydotxyz — APPROVED** [review]
Great thank you very much :)

**Pull request merged**
