### PR TITLE
Add helpers for square size and offset position

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

I have noticed that it is quite common to create sizes and positions that are "squared", with the same values in both places. This PR introduces helpers for simplifying code to make it less to write and easier to read as there is less information to parse on one line. Another benefit is that it allows there to be less theme lookups without having to cache the value in a variable first (less to write, simpler).

On top of introducing that API, this PR also adapts some existing code to use the new API.   

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
This is a nice helper, and SquareSize is clear. But is there a better name for SquarePos?

**Comment by Jacalz** [comment]
My initial idea was `NewEqualPos` but went with square for consistent. Would you prefer that one instead?

**Comment by andydotxyz** [comment]
I'm not really a fan, something about Equal implies a test or comparison I think.
"diagonal" may be relevant but I can't see a way to use it. 
In matrices such a behaviour may be called unit or identity - can that help?

**Comment by Jacalz** [comment]
Yeah, me neither. It's hard to come up with a good name for it. I'll have to think some more about it.

**Comment by Jacalz** [comment]
I discussed this with two colleagues at work. We concluded that `fyne.NewSquareDisplacedPos()` was the most correct we could think of. What do you think?

**Comment by andydotxyz** [comment]
Interesting... what about Offset instead of Displaced as I think we use that term elsewhere.

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Sorry I missed this before but it needs the "Since".
Good otherwise

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
