### PR TITLE
make image comparison tests less brittle

### LINKED ISSUE #4573: image rendering tests are fragile
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Run `go test ./...`. I get multiple test failures around rendering images not matching perfectly. The diffs appear quite small.

Example:

```
       	           	--- Expected
        	           	+++ Actual
        	           	@@ -4251,3 +4251,3 @@
        	           	 00010990  ff fd fd ff ff ff ff ff  f2 c0 c0 ff c8 01 01 ff  |................|
        	           	- 000109a0  c8 00 00 ff d4 35 35 ff  ff ff ff ff ff ff ff ff  |.....55.........|
        	           	+ 000109a0  c8 00 00 ff d4 36 36 ff  ff ff ff ff ff ff ff ff  |.....66.........|
        	           	 000109b0  ff ff ff ff ff fd fd ff  ff ff ff ff cd 17 17 ff  |................|
        	Test:       	TestDocTabs_ApplyTheme
        	Messages:   	Image did not match master. Actual image written to file:///Users/josh/x/fyne/container/testdata/failed/doctabs/desktop/single_custom_theme.png.
FAIL
FAIL	fyne.io/fyne/v2/container	0.789s
```

### How to reproduce

See above.

### Screenshots

_No response_

### Example code

Again, see above.

### Fyne version

caf50f6407d7f8a5abc91064338ce9bc3b1820bb

### Go compiler version

1.21.6

### Operating system and version

macOS Sonoma

### Additional Information

How would you like to approach fixing this? Do you want to allow some tolerance in pixel values? Or have multiple allowed images it can match?

### PR DESCRIPTION
**Pull request by josharian**
- internal/test: allow images to be +/- 1 RGB value per pixel

### Description:

This provides robustness when the rendering engine
behaves (ever so) slightly differently.

Fixes #4573 (I think, I can't be entirely sure
because my tests still fail because of #4572)

While we're here, let gofumpt add an octal marker to 0o755.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by josharian** [comment]
(Test failures were real...didn't see them locally because they were masked by even more test failures. Seems like CI coverage on macOS is somehow insufficient?)

**Comment by andydotxyz** [comment]
Is this still with good performance? last time I tried to do a pixel iteration route it was 20* slower than the assert library comparison

**Comment by josharian** [comment]
> Is this still with good performance?

Does it matter in practice? I did a quick spot check with this on and off and none of the tests were obviously slower at the top level.

I can certainly make it faster...at the cost of time and effort and code complexity. I'd suggest that we start by making it work, and then make it faster if/when it turns out to matter.

**Comment by andydotxyz** [comment]
> I can certainly make it faster...at the cost of time and effort and code complexity. I'd suggest that we start by making it work, and then make it faster if/when it turns out to matter.

That sounds reasonable. However I wonder - could it be put into an GOOS check (as this only impacts M1/M2 or arm64) meaning that anything not Darwin (or arm64?) still runs the original faster code path?

**Comment by josharian** [comment]
Done. PTAL.

**Comment by andydotxyz** [comment]
Nice one thanks

**Review by andydotxyz — APPROVED** [review]
Nice one thanks

**Pull request merged**
