### PR TITLE
Enhance Entry readonly state

### LINKED ISSUE #488: Entry (read only) state can support the right mouse button
I hope Entry (read only) state can support double-click mouse, provide pop-up menu, select text and copy it.

example：

4B17A90639F0623339DC6188DACADB91

### PR DESCRIPTION
**Pull request by spatocode**
**Description**
Enhance entry readonly state by adding support for keyboard, mouse focus and click event.

Fixes #488 

**Checklist**

- [x] Tests included
- [x] Lint and formatter run with no errors
- [x] Tests all pass

(where applicable)

- [ ] Public APIs match existing style
- [ ] Any breaking changes have a deprecation path or have been discussed

### CODE REVIEW

**Comment by andydotxyz** [comment]
Hi, thanks for the contribution but I don't quite understand - why do you want a readonly entry to accept key presses?
I'm not too sure I agree that it should get focus either. Can you provide some background please?

**Comment by spatocode** [comment]
Focus and Key presses on readonly entry enables one to move through the columns and rows of an entry using keyup/down/left/right or similar. It also enables shortcut actions like cut, copy, paste e.t.c. The takeaway is, keypresses and focus are strictly for shortcut actions and moving through entry cols/rows respectively.

**Comment by spatocode** [comment]
Most readonly entry i've seen supports that.

**Comment by andydotxyz** [comment]
I don’t think i have seen a read only entry that has a cursor visible, have you got some examples we could compare with? (I checked html and cocoa which don’t do it) Shortcuts makes sense - but our shortcut code is handled before it hits the entry widget so that should work anyway.

**Comment by spatocode** [comment]
Am not sure about cocoa, but in HTML, it's browser specific. IE, Edge and Firefox has a visible cursor in readonly cursor while Chrome doesn't support that. Some C++ GUI toolkit like wxWidget supports that also. But on a personal note, i think having a visible cursor on readonly entry is a good idea bcos it shows a user that it's really an entry and not some container with border.

> Shortcuts makes sense - but our shortcut code is handled before it hits the entry widget so that should work anyway.
Yea, you're right. I think i missed this.

**Comment by andydotxyz** [comment]
This has raised a really interesting question actually - what about a readonly entry is more than a label? My guess is the ability to make selections.
Does it make sense to have readonly as well as disabled? Should we have called it disabled in the first place? If it’s a different colour (like disabled button) then it indicates that it cannot be changed. If we add focus to a readonly entry the it looks exactly the same but cannot be edited.

Would there be any objections to moving towards a Disabled state where the text can be selected? This seems like a happy medium. I don’t want to manage too many different states and the difference in HTML renderers shows how complex this topic can be..?

**Comment by andydotxyz** [comment]
Looking at the updated code (thanks) I think the right click menu to copy a selection makes sense :). It’s the cursor portion that I guess I’m unsure about - see above. What do others think?

**Comment by spatocode** [comment]
This is becoming interesting, though i don't think it's such a complex topic. I think the current readonly entry is more of a disabled entry except for the background color which should be similar to a disabled button. In the case of having both disabled and readonly entry, i'm not sure if it makes sense(though i don't see it as a bad idea). Maybe it's up to the community to air their views.

**Comment by spatocode** [comment]
> It’s the cursor portion that I guess I’m unsure about

Is it possible for a readonly entry to have focus without a visible cursor(like in chrome)? If so, maybe that could be better(alternative design)?

**Comment by spatocode** [comment]
On a second thought, if there's no cursor, i don't think it will be possible to perform a mouse drag selection on texts. What do you think?

**Comment by andydotxyz** [comment]
I guess all of these ideas are possible, as we are building it from scratch :). However I don't think that getting focus without showing that there is focus works really - it will look strange as someone tabs through the UI...
I think it's entirely possible to make a selection without an input cursor though.

**Comment by andydotxyz** [comment]
On the slack channel we have 3 to 0 votes in favour of moving to “Disabled” with appropriate styling.

**Comment by andydotxyz** [comment]
Now 4 to 1

**Comment by andydotxyz** [comment]
It looks like disabled, but with selections and right click menu wins through.
Do you want to take this PR forward in this direction @spatocode or would you like to start a new one and/or hand the task to someone else?

**Comment by andydotxyz** [comment]
I have a related PR to move to disabled on Entry
https://github.com/fyne-io/fyne/pull/551.

Let me know what you think. If the team are happy and this lands then the content above still makes sense but should be based on top of the new Entry widget code.

**Comment by spatocode** [comment]
That's great! The disabled feature styling looks better now. Should close this now till there's a pressing need for readonly feature.

**Comment by andydotxyz** [comment]
Ok, thanks. If you still think it needs pop-up for select etc then we can address through a new issue or PR.
Thanks for your help on this, sorry it wasn’t this PR that landed

**Comment by spatocode** [comment]
Ah, no problem. I'm glad an issue has been resolved.

**Pull request closed without merging**
