### PR TITLE
Add tree binding types and use it in Tree widget

### LINKED ISSUE #3995: ability to create Tree widgets with data bindings to arbitrary types?
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

i wish there was the option to use data bindings to custom types with the Tree widget, similarly to the [List widget](https://developer.fyne.io/binding/list).

### Is it possible to construct a solution with the existing API?

yes, but it's NOT pretty. essentially, what i have to do is:

1. create a helper function that takes a slice of custom structs as an argument and an ORM instance as arguments
2. loop over the slice, checking if each element has a parent and adding it to the "root" if true (via the `CreateNode` method)
3. convert each slice element's primary key to a string and append it to an array (also via the `CreateNode` method)
4. create an update function that queries a database for the item identified by the `TreeNodeID` argument to update the label accordingly
5. return the tree

### Describe the solution you'd like to see.

the addition of a function called something like `widget.NewTreeWithData`, whose arguments are functions that take a `binding.DataItem` as opposed to a plain string/`widget.TreeNodeID`.

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #3995 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Review by Jacalz — APPROVED** [review]
Nice. Well done. We should probably add the tree to the data binding tab in `fyne_demo` but I will not hold up this PR on that :)

**Comment by andydotxyz** [comment]
Thanks. I wasn't sure about fyne_demo as the binding tab is getting too complicated. Think maybe we need to split it down more into individual widgets and show normal vs data bind for each of them instead.

Future work indeed.

**Comment by williambrode** [comment]
I just noticed this code in `gen.go`:

```go
	for _, b := range binds {
		if b.Since == "" {
			b.Since = "2.0"
		}

		writeFile(listFile, list, b)
		if b.Name == "Untyped" {
			continue // interface{} is special, we have it in binding.go instead
		}

		writeFile(treeFile, tree, b)
		if b.Name == "Untyped" {
			continue // interface{} is special, we have it in binding.go instead
		}
```

Checking `b.Name` twice is at least not necessary - but was the intention to leave out the Untyped Tree, or to include it?  I was just hoping to try to use an Untyped Tree binding.  The comment about it being in binding.go doesn't seem to apply to UntypedTree.

**Comment by andydotxyz** [comment]
Good spot. The UntypedTree should have been included.

**Pull request merged**
