### PR TITLE
Fix/windows dual graphics

### LINKED ISSUE #437: failed to initialise OpenGL
`
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()
	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))
	w.ShowAndRun()
}
`
Output;
PS C:\GoCode\fyne> go run .\fyne_sample.go
2019/09/04 19:16:37 Fyne error:  failed to initialise OpenGL
2019/09/04 19:16:37   Cause: glGetBufferParameteri64v
2019/09/04 19:16:37   At: C:/Users/eduar/go/src/fyne.io/fyne/internal/driver/gl/window.go:1007
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x54 pc=0x5b394d]

### PR DESCRIPTION
**Pull request by mgazza**
### Description:

Fixes #437 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Any breaking changes have a deprecation path or have been discussed.
- [x] Check for binary size increases when importing new modules. -> Increased by 2mb

### CODE REVIEW

**Comment by andydotxyz** [comment]
Looks good to me, thanks so much.

> Check for binary size increases when importing new modules. -> Increased by 2mb

How did you get this? It sounds worrying but locally my compile showed the same binary size (approximately, growth was 1.5k for hello app).

**Comment by mgazza** [comment]
I got this when cross-compiling from linux to windows with static libs 
`CGO_LDFLAGS="-static-libgcc -static" CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -ldflags "$(cat LDFLAGS)" -o bin/..... github.com/....cmd/term`

**Review by andydotxyz — APPROVED** [review]
It would be excellent if this did fix some of the mystery openGL issues!

**Comment by andydotxyz** [comment]
I can confirm a regular windows debug build is also 2M larger with this change.
However I think it's just debug symbols - if I run "fyne package -release" to strip them the files return to the same size - so I think this is ok. @Jacalz ?

On a side note I had no idea that windows executables are nearly double the size with the debug symbols in!

**Pull request merged**
