### PR TITLE
Update go-locale version for full language integration on macos

### PR DESCRIPTION
**Pull request by sdassow**
### Description:

With this the preferred language from the languages list is used as it should on macOS.

### Checklist:

- [ ] Tests included.
- [X] Lint and formatter run with no errors.
- [X] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
Please don't remove the PR checklist. It is meant to be filled out :)

**Comment by sdassow** [comment]
Ok, added them back. Only removed them because they don't mean much for this PR I think.

**Comment by Jacalz** [comment]
Sorry to be picky but they are meant to stay. However, you should not fill in the one about adding tests if you haven't added any.

**Comment by sdassow** [comment]
Right, changed. There are no new tests, but existing tests cover it, which I've used as qualifier ;-).

**Review by dweymouth — APPROVED** [review]

**Pull request merged**
