### PR TITLE
Add string binding to the Selected field of the Select widget

### PR DESCRIPTION
**Pull request by jimorc**
### Description:
Adds string binding to the Selected field of the Select widget.

Partial implementation for issue 2836. Binding of the Options field is outside the current scope of the binding implementation. A couple of suggestions were made:
1. Implement functionality in fyne-x.
2. Discuss BindXxx, e.g. BindSelected, BindOptions, but this is a discussion I would much prefer to leave to the main fyne developers as this may result in breaking changes.

### Checklist:

- [x] Tests included.
- [x] Tests all pass.
- [x] Formatter runs with no errors. Formatting actually done by my IDE (VSCode).
- [x] golang-ci run with no additional errors over those already produced in develop branch

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
This looks good thanks so much, but the version numbers are rather old

**Comment by jimorc** [comment]
> This looks good thanks so much, but the version numbers are rather old

I assume you mean the "Since 2.0" lines. If yes, what should it be: 2.5? 2.6? IF not, then I don't know what version numbers you are referring to.

**Comment by andydotxyz** [comment]
> > This looks good thanks so much, but the version numbers are rather old
> 
> I assume you mean the "Since 2.0" lines. If yes, what should it be: 2.5? 2.6? IF not, then I don't know what version numbers you are referring to.

That's correct, it should be 2.6 - there should be a comment inline in the PR review.

**Review by andydotxyz — APPROVED** [review]
Great, thanks very much!

**Pull request merged**
