### PR TITLE
mobile tests on CI

### PR DESCRIPTION
**Pull request by toaster**
### Description:

This PR enables mobile tests on CI.
It adjusts the tests and masters (images/markups) to make them pass.
There are known issues with doc tab rendering which are addressed in #1962.

### Checklist:

- ~~[ ] Tests included.~~
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
This add 6 * mobile test runs (doubling the number we currently check), is that what we want?
`release/v2.0.x` adds just 1 more test run to check mobile which seems like enough for the verification

**Comment by Jacalz** [comment]
I think the approach from @andydotxyz might be the best one going forward. It allows us to more easily expanding the mobile tests in the future. This adds a little bit too much complexity to the regular platform tests in my opinion.

**Comment by andydotxyz** [comment]
I landed my file to develop. If that was merged in to this PR we should see the checks pass.
They are currently marked as not-required because they fail on develop :(.

**Comment by toaster** [comment]
How about I’ll simply extract the test fixes out of this PR into a separate one?

**Comment by andydotxyz** [comment]
> How about I’ll simply extract the test fixes out of this PR into a separate one?

Probably easier, go ahead :)

**Pull request closed without merging**
