### PR TITLE
Lock and unlock less for BaseWidget.Move

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

Instead of first locking to set size and then locking again to get the implementation we can do it while we hold the first lock. This also matches the behaviour in all other methods.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
TODO: Benchmark the effect of this and apply the same to internal/widget if useful.

**Review by andydotxyz — DISMISSED** [review]
thanks

**Comment by Jacalz** [comment]
Benchmark results: This seems to bring down the time to call `Move()` (including creation of position) from 68ns to 55ns.

**Comment by Jacalz** [comment]
Sorry, needs a new approval. I added the same change to the internal basewidget.

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
