### PR TITLE
fix some race conditions

### PR DESCRIPTION
**Pull request by jadr2ddude**
this is rather incomplete

### CODE REVIEW

**Comment by paulhovey** [comment]
I'm having deja vu of #190 :astonished:

**Comment by jadr2ddude** [comment]
Unfortunately I don't think it is possible to properly fix all of the race conditions with our current concurrency model.

**Comment by andydotxyz** [comment]
Let’s talk on Slack about what it would be good to consider changing. If it’s related to widget render API there may be scope to change this in 1.1

**Comment by andydotxyz** [comment]
pulling some items from here into the main code ready for a 1.0.1 release

**Comment by jadr2ddude** [comment]
I am somewhat busy with other things. Feel free to re-use any code from here, but I am gonna close this.

**Pull request closed without merging**
