### PR TITLE
expose entry attribe Scroll value and support one entrance to set it

### PR DESCRIPTION
**Pull request by sunvim**
### Description:

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by andydotxyz** [comment]
These types are already exposed in the container package.

**Comment by Jacalz** [comment]
Please also note that we, according to the PR template and contributor documentation, want PRs to target the `develop` branch and not `master`.

**Comment by Jacalz** [comment]
If anything, the scrolling constants should be in the `fyne` package. I also don’t quite think we need a setter when we already have access to the field easily.

**Comment by sunvim** [comment]
> These types are already exposed in the container package.

yeah , I see!

**Comment by sunvim** [comment]
> If anything, the scrolling constants should be in the `fyne` package. I also don’t quite think we need a setter when we already have access to the field easily.

okkk ,got it

**Pull request closed without merging**
