### PR TITLE
Add tappable to widget.Slider

### PR DESCRIPTION
**Pull request by alexballas**
### Description:
Adding tappable to widget.Slider

Fixes [#3650](https://github.com/fyne-io/fyne/issues/3650)

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
You might wish to close this in favour https://github.com/fyne-io/fyne/pull/3531. It implements the full focus controls.

**Comment by Jacalz** [comment]
Hmm. Sorry never mind. We are just doing similar but not the same things. It might be better to try and work together in this :)

**Comment by alexballas** [comment]
Hi @Jacalz, would you like me to push the same changes to your branch and close this one?

**Comment by alexballas** [comment]
Unless this gets approved now and you use that as the base for your branch

**Comment by Jacalz** [comment]
I might be able to cherry-pick you commit into my branch. That way we will avoid a few headaches with merge conflicts.

**Comment by Jacalz** [comment]
It also might just be simpler to merge this as that PR seems to be a bit stuck on a (possible) rounding error. Will try to review this when I have some time over.

**Review by andydotxyz — APPROVED** [review]
Looks good to me, thanks!
Best wait for @Jacalz as well given the note above.

**Review by Jacalz — CHANGES_REQUESTED** [review]
This is great, thanks. The only thing I would like to fix is that there now is a lot of code duplication between `Dragged()` and `Tapped()` (they are basically the same). It seems to me like you should be able to just have `Dragged()` call `Tapped()` with it's point event.

**Comment by andydotxyz** [comment]
> This is great, thanks. The only thing I would like to fix is that there now is a lot of code duplication between `Dragged()` and `Tapped()` (they are basically the same). It seems to me like you should be able to just have `Dragged()` call `Tapped()` with it's point event.

A good assertion, though I would prefer they both call a common method like `positionChanged` or similar, so it can't accidentally break if tapped and dragged change (for example if the request for `OnChangeEnded` were called from the `Tapped` method...

**Comment by andydotxyz** [comment]
It is probably worth noting that `SetValue` is almost identical as well (with extra `Refresh`) - so possibly it could be even tidier with that common method being used by all three?

**Comment by Jacalz** [comment]
Indeed. Sounds like a good plan to me 👍

**Comment by alexballas** [comment]
Do you believe the code duplication in this case justifies the creation of a new method?
We're effectively talking about those lines
```go
	if s.almostEqual(lastValue, s.Value) {
		return
	}

	s.Refresh()

	if s.OnChanged != nil {
		s.OnChanged(s.Value)
	}
}
```
 Keeping things simple and leaving each method as they are sounds cleaner and aligns more to the Go way.
If we used a new method, we could also try to transfer the Value setting into that new method but we'd then need to account for two cases. One where just the ratio is passed and one where a direct value is pass (for the case of the SetValue method). It all sounds like unnecessary complexity.

**Comment by alexballas** [comment]
I did apply the changes however, let me know

**Review by Jacalz — APPROVED** [review]
Looks good to me. Well done :+1: 
I just want the opinion of @andydotxyz before merging :)

**Review by andydotxyz — APPROVED** [review]
Thanks so much. Always nice to get a new feature whist reducing the lines of code in the widget ;)

**Pull request merged**
