### PR TITLE
Refactoring/paint tree

### PR DESCRIPTION
**Pull request by toaster**

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks for this. Unfortunately something does not feel quite right.
If you look at internal/driver/util.go around like 69 we are setting the clip, but then the painter is ignoring these parameters (this seems to be a mistake made with the original code you are refactoring).

I'm not sure from looking exactly how this duplication came about but essentially the "should we crop smaller" is handled in the util so the paint should not have to check for ScrollContainer as the parameters are passed in.

As such we are applying scroll parameters for each painted object, so perhaps these clipping methods are overkill? If not then another suggestion is that the clipping is applied incrementally smaller so maybe Push and Pop would be better than Start and Stop with regards to the new methods?

Sorry for the lack of clarity of thought here, It's late!

**Comment by toaster** [comment]
> If you look at internal/driver/util.go around like 69 we are setting the clip, but then the painter is ignoring these parameters (this seems to be a mistake made with the original code you are refactoring).

This is a different kind of clipping. You introduced these clipping parameters for the fix of #299.
When refactoring the tree walk out of the painter I spent some time thinking about using the clipping params of the `WalkTree` callback but I thought that this would only be an advantage if I could get rid of the `if _, ok := obj.(*widget.ScrollContainer)` in the `canvas#paint`. But this is not the case unless we extend the `beforeChildren` callback with more parameters which indicate the _start_ and the _end_ of a clipping. Therefore I did not change anything there.

However, I agree to your point with having only one location for deciding on clipping and computing its parameters. AFAICS this should be the tree walker. I will try to achieve this in another PR.

**Comment by andydotxyz** [comment]
I'm not quite sure what you mean about a different type of clip?
Looking at it more I think that removing the "if ScrollContainer" line and applying the scissor to the current clip coordinates (translated appropriately, as in your code here) would work just the same?

Apologies - I feel like I am probably missing the point here.

**Comment by toaster** [comment]
Then you would apply GL scissor for all children of the scroller with the same coordinates.
Additionally you would disable the scissor after each child.
I don't think this would work but I don't have knowledge about the GL rendering. The GL calls used for the scissor don't look as if they are nestable to me.

**Comment by andydotxyz** [comment]
I was not proposing that it was nested - in the paint call (which is a beforeChildren) you would set the scissor, paint, unset the scissor and return.

That said I have reviewed this with fresh eyes and see this is a refactoring and it's neater than before. The check for "should we clip" inside a function that passes clip parameters seems strange but can be fixed later if we need to. I'll see it as an optimisation for now ;)
Perhaps you could add a comment to the method so that for future note we realise it's ignoring the parameters passed in as an optimisation?

Having said that if at some point in the future we add another item that clips and it can be inside the scroller then this new model creates nested clips that you rightly suggest cannot be nested.
I don't think we have to worry about that now, but I wanted to check it was considered.

**Pull request merged**
