### PR TITLE
dependencies: update glfw to 20200625191551

### PR DESCRIPTION
**Pull request by RustamGamidov**
changes in the glfw:
  - pr-285 Fixes a compiler error by using null joystick on freebsd
  - pr-282 fix regression from pr-256 GetClipboardString No longer returns an error
  - pr-280 fix: go mod vendor
  - pr-273 Added missing functions for compatibility with Vulkan
  - pr-270 .travis.yml: use latest stable Go (1.13.8 and 1.12.17 at this time)

### Description:
pulling in external dependency with the fixes preventing fyne crashes

Fixes #(issue)
#1132
#1123
#743 (claimed as fixed but the real fix is in the update that is missing)

### Checklist:
- [ ] Tests included.
- [x] Lint and formatter run with no errors. (no code changes, just deps)
- [x] Tests all pass.

#### Where applicable:
- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by andydotxyz** [comment]
I think the vendor files must be out of date after this? Using “fyne vendor” will ensure the updated C and H files are included as well as the Go.

**Comment by RustamGamidov** [comment]
if i understood you correctly that was my mistake in he first try.
i've made force-push to update `vendor\modules.txt` in the same commit.
strange that only one build has failed because of that.

**Comment by andydotxyz** [comment]
If you look at the changes tab for this PR there are 0 code changes present, so something doesn’t quite add up... the vendor folder should reflect all the code improvements you have listed I would think?

**Comment by RustamGamidov** [comment]
oh! i missed `vendor` is in the repo and not received basing on the txt file. sorry
made that change

**Pull request merged**
