### PR TITLE
Correctly shape input before truncating

### PR DESCRIPTION
**Pull request by andydotxyz**
Partial fix for #4998

Need to resolve an underlying issue before this can be correctly tested - current state breaks existing tests too

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by dweymouth** [comment]
What is the status of this PR - what's the underlying issue that needs to be resolved? I tried this out and it seems to be truncating the Japanese script way too early now:

image

**Comment by andydotxyz** [comment]
> it seems to be truncating the Japanese script way too early now:

Yup, that's the issue, Before it was treating it as a full block of unshaped characters and now it splits it into runs correctly but it will wrap early if they are not all part of exactly the same character / font / face type - the related issue I have opened is https://github.com/go-text/typesetting/issues/166

**Comment by andydotxyz** [comment]
That should cover it now @dweymouth  :)

**Review by dweymouth — APPROVED** [review]
Seems to work fine now, thanks for getting this sorted!

**Pull request merged**
