### PR TITLE
Fix blocking theme issues

### LINKED ISSUE #3462: New 2.3.0 theme suggestions
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

There are some little things that I think should be improved in the new theme:

Check mark should be white
image

Menu items and buttons should have a little more right-padding to by symmetrical
image
image

### Is it possible to construct a solution with the existing API?

_No response_

### Describe the solution you'd like to see.

image

### PR DESCRIPTION
**Pull request by andydotxyz**
Menu padding/align and contrast for checks

Fixes #3462

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
A few tests are failing but it seems good otherwise. I also noticed that the progress bar text is a little hard to read in the light theme. I think it might have the wrong color:
image

**Comment by andydotxyz** [comment]
> A few tests are failing but it seems good otherwise. I also noticed that the progress bar text is a little hard to read in the light theme. I think it might have the wrong color: image

Thanks, updated to match the fix of Check :)

**Comment by Jacalz** [comment]
Hmm. The progress bar seems a bit problematic. It is better in some places now and worse in others:
image
image
image
image

**Comment by Jacalz** [comment]
I think the solution would be to always keep the progress bar text white. Seems to give the best contrast in my opinion.

**Comment by andydotxyz** [comment]
> I think the solution would be to always keep the progress bar text white. Seems to give the best contrast in my opinion.

Unfortunately that approach codes something theme specific into the progress bar, so could break with other themes, or would require new APIs in the theme to return a colour that works as you describe.
Given we can't do either of those at this stage I think the options are to go as-is or to draw a background behind the text.
What I would like to do is render the text on background as foreground colour, and that over the primary section to be background colour. But at this time we don't have the ability to crop the text rendering in that way I don't think.

**Review by Jacalz — APPROVED** [review]
Makes sense. This is better than before at least :)

**Pull request merged**
