### PR TITLE
With Chrome 106 it is now possible to run fyne wasm output.

### PR DESCRIPTION
**Pull request by Bluebugs**
### Description:
Chrome 106 did solve its bug when running fyne application targeting webassembly. So let's switch to serving wasm output to chrome 106 and older.

### Checklist:
- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:
- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by Jacalz** [comment]
Can you add a TODO, or open an issue, to remind us to remove this once Chrome 106 is out minimum version?

**Comment by Bluebugs** [comment]
> Can you add a TODO, or open an issue, to remind us to remove this once Chrome 106 is out minimum version?

I actually do not know how we would decide that. If you have suggestion, I can add that to an issue.

**Comment by andydotxyz** [comment]
Looks fine. Would be good if you can fill the PR template though.

**Comment by Bluebugs** [comment]
> Would be good if you can fill the PR template though.

I really never know what to do when this is outside of the go code base. There is no test I can think of for it, and none of the other question seems relevant. What is the expected action on those checkbox if they are not relevant to this case?

**Comment by andydotxyz** [comment]
If the items under "where applicable" are not applicable we remove them instead of leaving them unchecked (otherwise GitHub reports them as incomplete tasks).
I agree there are no tests that make sense at this time

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
