### PR TITLE
refactor(gen): use go/format.Source function instead of call "gofmt" …

### PR DESCRIPTION
**Pull request by bestgopher**
…tool to format code

 

### Description:

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).

### CODE REVIEW

**Comment by bestgopher** [comment]
@changkun What do you think about this change？

**Review by changkun — APPROVED** [review]
LGTM

**Comment by changkun** [comment]
@bestgopher Thanks for the contribution! I didn't know `go/format` has this type of ability...

**Comment by changkun** [comment]
@bestgopher Please also resolve the conflicts as PRs must be sent to the develop branch.

**Comment by bestgopher** [comment]
> @bestgopher Please also resolve the conflicts as PRs must be sent to the develop branch.

done!

**Review by changkun — APPROVED** [review]

**Review by Jacalz — APPROVED** [review]
Nice stuff. Thanks and congratulations for your first PR for Fyne :)

**Pull request merged**
