### PR TITLE
Fix for text widgets not correctly aligning or showing

### PR DESCRIPTION
**Pull request by andydotxyz**
### Description:
Two different text fixes - first (alignment) was to resize text provider.
Second was to stop cascading Hidden flag - the driver does this now

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by stuartmscott** [comment]
Could this error if Resize is called before CreateRenderer?

What does the driver do differently?

**Comment by andydotxyz** [comment]
This shouldn't cause crashes as the BaseWidget and textProvider are both full types embedded in the widgets - not assigned in CreateRenderer.

The driver used to respect the Hidden state of every item on the screen - but now it stops drawing a tree as soon as a node is not visible. This the Label or HyperLink Hidden flag superceeds the provider one.

**Comment by stuartmscott** [comment]
Can you remove "l.provider.Hidden = l.Hidden" from Label.CreateRenderer?

**Comment by andydotxyz** [comment]
Fixed this left over Hidden - i told you my search was broken @stuartmscott !
Can you test this patch on your end to verify it fixes the hidden issue?

I'll now try and write the tests that illustrated how it was broken and now fixed to flesh out the PR

**Comment by stuartmscott** [comment]
I wasn't sure how to cherry-pick this whole PR on top of the accordion widget branch (if there is an easy way, please let me know) so I ended up just cherry-picking 7a54721 individually (69c13ba wouldn't cherry-pick - fatal: bad object 69c13baf48ec156d158137ecb048758c4b48eb05, even checking out origin/fixalign only had 7a5 and not 69c :/, but it is a one liner so just edited the file myself) and I can confirm that the label issue I was seeing is resolved. Thanks Andy!

**Comment by toaster** [comment]
Why do you cherry-picking instead of merging the develop branch @stuartmscott?

**Comment by andydotxyz** [comment]
@toaster I think that's because this is a PR and I was looking for him to test it on top of another open PR. Neither exist on develop yet.

**Comment by andydotxyz** [comment]
Tests now in :)

**Comment by toaster** [comment]
> Correct, not sure if Git/Github has a better way to combine PR branches

That‘s plain git:
```
git co pr1-branch
git rebase pr2-branch
```

**Pull request merged**
