### PR TITLE
Lang: add portuguese

### PR DESCRIPTION
**Pull request by lostdusty**
Requested by andy on https://github.com/andydotxyz/fyne/pull/4

### CODE REVIEW

**Comment by Jacalz** [comment]
@andydotxyz Would it not be better to have the translations go through Weblate? I’m a bit worried that they will get out of sync if we merge PRs here?

**Comment by andydotxyz** [comment]
Weblate reads this repository, they will stay in sync. We have a GitHub hook informing of any changes upstream.

**Comment by lostdusty** [comment]
totally forgot about weblate

**Review by andydotxyz — APPROVED** [review]
Thanks so much. Glad that we are getting some translations in before the release :)

**Comment by andydotxyz** [comment]
Congratulations on your first Fyne PR merge @lostdusty thanks so much :)

**Comment by lostdusty** [comment]
🎉, More to come soon.

**Pull request merged**
