### PR TITLE
Support submenus in system tray

### PR DESCRIPTION
**Pull request by andydotxyz**
I had not noticed this did not work! 
Perhaps should back-port to release branch?

### Checklist:

- [ ] Tests included. <-- still not figured out how we test interactions with the systray API
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by xiebruce** [comment]
I need this function in macOS system tray, I'm now can add menus by using the following commands
```bash
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show1", func() {
				w.Show()
			}), fyne.NewMenuItem("Show2", func() {
				w.Show()
			}), fyne.NewMenuItem("Show3", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.ShowAndRun()
}
```

But I don't know how can I add submenus to the menus in the system tray, just like the following screenshot
image

How can I do this?

**Comment by andydotxyz** [comment]
Put a new `Menu` as `MenuItem.ChildMenu`

**Comment by andydotxyz** [comment]
https://github.com/fyne-io/fyne/blob/master/cmd/fyne_demo/main.go#L94

**Comment by xiebruce** [comment]
> https://github.com/fyne-io/fyne/blob/master/cmd/fyne_demo/main.go#L94

Thank you, I tried to wrote the following code, but why there's no childMenu? 
image

And if I click "show1" button, it shows the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1003fcf90]

goroutine 35 [running]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
        /Users/bruce/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver_desktop.go:74 +0x30
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
        /Users/bruce/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver_desktop.go:72 +0x14d
exit status 2
```

**Comment by andydotxyz** [comment]
Can you please try the latest release, I think you must be encountering an issue that was fixed already.

**Comment by xiebruce** [comment]
> Can you please try the latest release, I think you must be encountering an issue that was fixed already.

I tried using go 1.19.2(`go version go1.19.2 darwin/amd64`) and `fyne 2.2.4`, here is my go.mod
```
module go-GUI

go 1.19

require fyne.io/fyne/v2 v2.2.4

require (
    fyne.io/systray v1.10.1-0.20220621085403-9a2652634e93 // indirect
    github.com/davecgh/go-spew v1.1.1 // indirect
    github.com/fredbi/uri v0.0.0-20181227131451-3dcfdacbaaf3 // indirect
    github.com/fsnotify/fsnotify v1.5.4 // indirect
    github.com/fyne-io/gl-js v0.0.0-20220119005834-d2da28d9ccfe // indirect
    github.com/fyne-io/glfw-js v0.0.0-20220120001248-ee7290d23504 // indirect
    github.com/fyne-io/image v0.0.0-20220602074514-4956b0afb3d2 // indirect
    github.com/go-gl/gl v0.0.0-20211210172815-726fda9656d6 // indirect
    github.com/go-gl/glfw/v3.3/glfw v0.0.0-20211213063430-748e38ca8aec // indirect
    github.com/godbus/dbus/v5 v5.1.0 // indirect
    github.com/goki/freetype v0.0.0-20181231101311-fa8a33aabaff // indirect
    github.com/gopherjs/gopherjs v1.17.2 // indirect
    github.com/jsummers/gobmp v0.0.0-20151104160322-e2ba15ffa76e // indirect
    github.com/pmezard/go-difflib v1.0.0 // indirect
    github.com/srwiley/oksvg v0.0.0-20200311192757-870daf9aa564 // indirect
    github.com/srwiley/rasterx v0.0.0-20200120212402-85cb7272f5e9 // indirect
    github.com/stretchr/testify v1.7.2 // indirect
    github.com/tevino/abool v1.2.0 // indirect
    github.com/yuin/goldmark v1.4.0 // indirect
    golang.org/x/image v0.0.0-20220601225756-64ec528b34cd // indirect
    golang.org/x/mobile v0.0.0-20211207041440-4e6c2922fdee // indirect
    golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d // indirect
    golang.org/x/sys v0.0.0-20220412211240-33da011f77ad // indirect
    golang.org/x/text v0.3.7 // indirect
    gopkg.in/yaml.v3 v3.0.1 // indirect
    honnef.co/go/js/dom v0.0.0-20210725211120-f030747120f2 // indirect
) 
```

But still no childMenu, and if I click `show1` button, still shows the same error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1003fcf10]

goroutine 27 [running]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
        /Users/bruce/go/pkg/mod/fyne.io/fyne/v2@v2.2.4/internal/driver/glfw/driver_desktop.go:74 +0x30
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
        /Users/bruce/go/pkg/mod/fyne.io/fyne/v2@v2.2.4/internal/driver/glfw/driver_desktop.go:72 +0x14d
exit status 2
```

Here is my code
```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		menu1 := fyne.NewMenuItem("show1", nil)
		menu1.ChildMenu = fyne.NewMenu("",
			fyne.NewMenuItem("Show1-sub", func() {
				fmt.Println("Menu New->File")
				// w.Show()
			}),
		)
		m := fyne.NewMenu("MyApp", menu1)
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
You'll need to use a development version I think

**Comment by xiebruce** [comment]
OK, but I don't know how to install a non-released version, I'm not familiar with it, but I'll google it, thank you.

**Comment by andydotxyz** [comment]
`go get fyne.io/fyne/v2@develop`

**Comment by xiebruce** [comment]
Thank you so much, finally it works after I use `go get fyne.io/fyne/v2@develop` and `go mod tidy`
image

**Pull request merged**
