### PR TITLE
Some better wording for the changelog

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This improves some wording for the changelog of v2.3.5.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
This isn't how we usually word it. I missed the "### Fixed" header which would have made more sense but normally the issues are describing the problem not the fix I think.

**Comment by Jacalz** [comment]
If we are to describe a log of changes, isn’t it better to describe what we have done/fixed instead of what the problem was? It seems clearer to me and probably does so as well for users/developers with less knowledge of the internals of Fyne

**Comment by Jacalz** [comment]
But maybe my comment above only applies for when there is no ###fixed label? I think you might be right but I still believe that there are some improvements to be made

**Comment by Jacalz** [comment]
Neve mind. Ignore my two previous messages. I see what you mean and I believe to have addressed your concerns :)

**Review by andydotxyz — APPROVED** [review]
Thanks

**Pull request merged**
