### PR TITLE
fix: Use nativeScale to calculate touch location on IOS

### LINKED ISSUE #3122: Iphone incorrect click coordinates in zoomed screen view
### Describe the bug:

When using a zoomed display zoom view on IOS, click positions registered in fyne apps are incorrect relative to actual user clicks. Simply, when I click in the center of the screen, fyne registers the click a bit to the top left.
### To Reproduce:
Steps to reproduce the behaviour:
1. Set zoomed view in Settings -> Display & Brightness -> View -> Zoomed
2. Get fyne calc from app store.
3. Click on the top section of any button.
4. See that click is not registered on button clicked. For example, clicking on top section of button with number `5` in fyne calc, you will get button with number `8` clicked.

### Screenshots:

N/A

### Example code:

I believe the bug is in internal driver code, so all fyne IOS apps are susceptible to the bug.

### Device (please complete the following information):
 - **OS:** IOS
 - **Version:** 15.5
 - **Go version:** go1.17.1 darwin/amd64
 - **Fyne version:** v2.2.1 and develop

### PR DESCRIPTION
**Pull request by cedy**
### Description:

Fixes #3122

### Checklist:

- [] Tests included. <- I don't think tests applicable here.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass. <- Same tests that fail on master/develop for me, fail after my fix.

### CODE REVIEW

**Comment by cedy** [comment]
flaky tests?  seems to be fine locally

**Comment by andydotxyz** [comment]
These tests are not flakey - I added a new test to cover a regression that was found and this fix seems to be missing in the PR somehow.
Try rebasing on top of latest `develop` (as of now) because the fix is released and is merged back in.

**Comment by andydotxyz** [comment]
Actually it looks more like develop is not in the right state - what works on the release branch isn't passing on develop for more than this PR... I will have to look into it sorry!

**Review by andydotxyz — APPROVED** [review]
Aha, amazing catch - nice fix

**Pull request merged**
