### PR TITLE
Some text improvements including falling back to system fonts

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes are in separate commits, the fallback code is basically first-pass.
We include lookup for OS font for the current language and whatever font the OS has for japanese, which typically includes most script languages.

This provides good (tested) coverage of rendering out of the box for macOS, iOS, Linux and Android (windows still to be tested).
Memory increase is currently 5% - 20% depending on how many fonts the app uses.
There are more optimisations to come that will counteract the increase.
The code is now faster than before so that's the current tradeoff

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Still some tests to revise, but this is pretty much code complete I think.

image

**Comment by Jacalz** [comment]
How much work is left for this to be ready?

**Comment by dweymouth** [comment]
Same question as Jacalz, also wondering if this will cover Chinese and Korean as well even if the locale is EN. (Those along with Japanese are the most common non-Latin scripts in peoples' music libraries ;)

**Comment by andydotxyz** [comment]
Yes. It falls back on a rune basis so unidentified characters should all be looked up.
Functionally the only thing missing is when you need locale info to shape the glyphs in a run - but that is a step later than looking up the font.

I will try and address the rest issues this weekend to get the PR landed.

**Comment by andydotxyz** [comment]
On Windows and macOS (not Linux, iOS or Android) sometimes the symbol fonts align slightly differently on the sub-pixel.
I have disabled the test for now, it makes no difference to the functionality and I did not want to hold up people checking this out...

**Review by Jacalz — COMMENTED** [review]
I wonder if it perhaps would be easier to test this if we could easily disable the built in fonts similar to https://github.com/fyne-io/fyne/issues/2637?

**Comment by andydotxyz** [comment]
``

> I wonder if it perhaps would be easier to test this if we could easily disable the built in fonts similar to #2637?

I don't see why that makes it easier - if we disable the builtin fonts then it will be down to the OS/setup as to what fonts are found - basically guaranteed to be different unexpectedly on different computers - and may even break on CI.

**Comment by dweymouth** [comment]
I think @Jacalz means that if you can build with no bundled fonts, at least for testing, you don't need an app that has CJK or other less common characters to test the lookup

**Comment by dweymouth** [comment]
Plus now that lookup is in place we probably want to give apps the option to opt out of having any bundled fonts in the binary

**Comment by Jacalz** [comment]
> I think @Jacalz means that if you can build with no bundled fonts, at least for testing, you don't need an app that has CJK or other less common characters to test the lookup

Indeed. I figured it would make things not only easier to test but also allow us to test more parts of the font lookup.

> Plus now that lookup is in place we probably want to give apps the option to opt out of having any bundled fonts in the binary

Yup. That would be nice as well down the road as more of a feature than a testing helper :)

**Comment by andydotxyz** [comment]
These are good points and were agreed on Slack too as follow up work. This PR still needs a 👍 or 👎 to progress.

**Review by dweymouth — APPROVED** [review]
This seems good to me, at least as a first pass. More improvements can be done in follow-ups if needed. Also will be easier to continue testing with it integrated into develop.

**Pull request merged**
