### PR TITLE
Don't call OnScrolled if offset did not change

### LINKED ISSUE #1868: OnScrolled triggered when offset hasn't changed
`container.Scroll.OnScrolled` is called multiple times with the same offset, instead it should only be called when the offset has changed.

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #1868

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass. <- this is super strange... can't figure out why just yet

### CODE REVIEW

**Comment by andydotxyz** [comment]
I meant this to be a draft PR sorry. I cannot figure out yet why the visual tests fail just because we are not triggering on duplicate OnScroll calls

**Comment by andydotxyz** [comment]
> Have you managed to find the source for the error?

I'm getting there. Lots of widgets just worked off this false assumption.
I have found and resolved 2 issues. At least one more remains.

**Comment by andydotxyz** [comment]
Finally got to the bottom of it :)
It was 2 items in general

*) Calling `Scroller.Refresh()` no longer calls `OnScrolled`, so we may have to refresh the content directly if required
*) The setting of `Scroller.Offset` and then calling `Refresh()` does not call `OnScrolled` which makes sense. It previously did.

**Review by Jacalz — COMMENTED** [review]
Hmm, I think there might be something wrong here. When adding a few more tabs to the DocTabs in fyne_demo, the scroller jumps back to the start after a while of dragging it to the right.

I would go about replicating it like this:
- Go to the DocTabs section in fyne_demo.
- Press the "+" button to add a few tabs and thus get a scroller.
- Grab hold of the scroller with the mouse and drag it to the right.
- About 2/3 on the way to the right, the scroller jumps back to the start again.

**Comment by andydotxyz** [comment]
> Hmm, I think there might be something wrong here. When adding a few more tabs to the DocTabs in fyne_demo, the scroller jumps back to the start after a while of dragging it to the right.

This is a good catch thanks @Jacalz, however the issue is on develop too, so not part of the changes here.

**Comment by Jacalz** [comment]
> > Hmm, I think there might be something wrong here. When adding a few more tabs to the DocTabs in fyne_demo, the scroller jumps back to the start after a while of dragging it to the right.
> 
> 
> 
> This is a good catch thanks @Jacalz, however the issue is on develop too, so not part of the changes here.

Are you sure? I tested on develop and couldn't quite replicate it. I'll have to try again, I guess.

**Comment by andydotxyz** [comment]
> Are you sure? I tested on develop and couldn't quite replicate it. I'll have to try again, I guess.

Quite sure - it seems to glitch when it's about to show the selected tab when scrolling.

**Review by Jacalz — DISMISSED** [review]
You are entirely correct. Sorry for the fuss.

**Comment by andydotxyz** [comment]
Not a problem thanks @Jacalz.
I decided that this was a behaviour change so did not belong on a bugfix release (given the changes we had to make internally).
If you would be OK to re-approve with this change I would be appreciative :)

**Review by Jacalz — APPROVED** [review]
Looks good twice :)

**Pull request merged**
