### PR TITLE
Remove File Tree

### PR DESCRIPTION
**Pull request by stuartmscott**
Moved to https://github.com/fyne-io/examples

### Checklist:

- [n/a] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [x] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by stuartmscott** [comment]
Moved to https://github.com/fyne-io/examples/pull/28

**Review by andydotxyz — APPROVED** [review]
It's a shame but I agree we should not publish with controversial APIs.

**Comment by andydotxyz** [comment]
An extract from the call on friday suggested there may be a way forward if this incorporated the favourites etc that file dialog presents...

```
Worried about the precident of a new API with no new widget implemented under?
A more complete selector could be good, including favourites buttons etc.

The data binding will provide shared handling of the main data but probably would not cover the favourites

Could have a FileTree that is the favourites etc in addition to a file structure browse could be a reasonable widget.
- uri handling
- some file handling helpers?
- perhaps some file handling context menus?

- what if the "default" root was Home?
(other roots are the favourites / drives like file dialog left panel)
drives and favourites open other tree branches
```

**Comment by stuartmscott** [comment]
Seems like useful functionality, tho not sure if that needs to be a separate widget as all it does is return home and favourites as the children of the root, something like:

```go
tree.ChildUIDs(uid string) []string {
  var children []string
  if uid == tree.Root {
        children = append(children, homeDir, downloadsDir)
  } else {
        // Normal directory listing...
  }
  return children
}
```

**Comment by andydotxyz** [comment]
Perhaps, except it also needs to manage the possible duplicates by mounting the data tree in different roots

**Comment by stuartmscott** [comment]
I think that is outside the scope for an initial collection widget, but could be considered for future releases, feel free to file a feature request

**Pull request merged**
