### PR TITLE
Add Remove to data binding lists and trees

### LINKED ISSUE #3100: Function "Remove" or "RemoveItem" on binding lists
### Is your feature request related to a problem? Please describe:
When working with binded lists you can Append and Prepend items, but it's not possible to Remove them. 
This makes using binded lists more difficult.

### Is it possible to construct a solution with the existing API?
You can "Get" the list, manipulate it outside and then "Set" the new list.

### Describe the solution you'd like to see:
A "Remove" function which accept an index of the item that should be removed.

### PR DESCRIPTION
**Pull request by andydotxyz**
Adding the missing functions.
Removing a tree item removes all its children.

Fixes #3100

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Naming to be checked here I guess. List might add `RemoveIndex` in the future, should there be an equivalent for Map and/or should `Remove` be `RemoveKey`? I was following the Golang `delete` as passing the key but that may not fit with our API design.

**Comment by Jacalz** [comment]
I'll try to have a look tomorrow or on Thursday if possible.

**Comment by andydotxyz** [comment]
Thanks, I think it should all be sorted now.

**Review by Jacalz — CHANGES_REQUESTED** [review]
Looking good. Just some staticcheck fixes that need to be done now that it apparently understands what `v` is (bug?).

**Comment by andydotxyz** [comment]
Oh good point I missed that. It was a bug that was hiding. Added a new test to confirm

**Pull request merged**
