### PR TITLE
make CenterOnScreen() work when window hidden or visible.

### PR DESCRIPTION
**Pull request by paulhovey**
Also added helper function `moveToPosition()` . #97

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks, but the runOnMainAsync() calling runOnMainAsync() again seems messy. Normally I would be very happy about breaking functions down but in this case it seems unnecessary - and could cause visual delays.

**Comment by andydotxyz** [comment]
I just realised as well - the 10x10 initial is set in the same file - perhaps define it as a const and then the if (rather than max) version would work as expected?

**Comment by paulhovey** [comment]
I removed the nested call, but left `moveToPosition()` in the file.  I figured if you need it in the future, why re-invent?

The most future-proof way to use the if-statement instead of the `Max()` call is to make a constant (or two) and initialize the window dimensions according to that, then use the if-statement based on that.  I'd worry that GFLW or one of the libraries it uses to actually draw something on a screen would add a pixel or two and ruin the if-statement.  I really don't see any good reason to not just use `Max()`.

**Comment by andydotxyz** [comment]
I take your point on Max, let's go with it as you have there.

moveToPosition(), however, is now dead code - an internal method that no-one uses. Surely your IDE is adding a warning for this? I realise it's not a public API but I'd prefer not to see code added that is not used. (Apologies again for being picky but such addition will reduce our test coverage)

**Comment by andydotxyz** [comment]
I realised we didn't really have a test for this, which should have been possible.
So I added one. It needed a little refactoring but I think it makes sense. Let me know if you disagree! 5ce5a59

**Pull request merged**
