### PR TITLE
Don't traverse un-rendered widgets

### LINKED ISSUE #3922: Freeze when resizing AppTabs during Close Intercept on develop (working on 2.3.4)
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In my app, I want to wait for the current task to finish cleanly, waiting to close until the waitgroup is done.
When I close the window and don't touch it until the task exits, everything works. But if I resize the window while still waiting for the task to finish, it irreversibly freezes up.

### How to reproduce

- Run the example code
- Close the window (in this case within the first 10s)
- Before it actually closes, try resizing (see video attachment)

Voi-là, you just froze your app

### Screenshots

[recording_20230527-200714.webm](https://github.com/fyne-io/fyne/assets/54681180/9d8864b0-3541-4928-8733-0f55f5a2fc4d)

### Example code

```go
package main

import (
    "context"
    "fmt"
    "sync"
    "time"

    "fyne.io/fyne/v2"
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/theme"
    "fyne.io/fyne/v2/widget"
)

func main() {
    app := app.New()
    window := app.NewWindow("Window Title")

    ctx, cancel := context.WithCancel(context.Background())
    var wg sync.WaitGroup

    wg.Add(1)
    go func() {
        defer wg.Done()
        fmt.Println("TASK: Starting to do something")
        for i := 0; i < 10; i++ {
            time.Sleep(1 * time.Second)
            select {
            case <-ctx.Done():
                err := ctx.Err()
                if err != nil {
                    fmt.Println("TASK: Error:", err)
                    return
                }
                fmt.Println("TASK: Interrupted")
            default:
            }
        }
        fmt.Println("TASK: Done")
    }()

    appTabs := container.NewAppTabs(
        container.NewTabItemWithIcon(
            "Downloads",
            theme.DownloadIcon(),
            widget.NewButton("Downloads", func() {}),
        ),
        container.NewTabItemWithIcon(
            "Preferences",
            theme.SettingsIcon(),
            widget.NewButton("Preferences", func() {}),
        ),
    )
    appTabs.SetTabLocation(container.TabLocationLeading)

    window.SetContent(appTabs)

    window.Resize(fyne.NewSize(800, 450))

    window.SetCloseIntercept(func() {
        go func() {
            cancel()
            fmt.Println("MAIN: Window closed, waiting for task to finish...")
            wg.Wait()
            fmt.Println("MAIN: Finished, exiting")
            window.Close()
        }()
    })

    window.ShowAndRun()
}
```

### Fyne version

v2.3.4-rc1.0.20230526221837-732ffb69a21d

### Go compiler version

go1.20.3

### Operating system and version

Manjaro Linux / Wayland

### Additional Information

Strangely, when I remove the AppTabs and replace them with a label, this issue doesn't occur.

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #3922

### Checklist:

- [ ] Tests included. <- cannot think how ...
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Hmm, this seems to fail a lot of the visual tests... but apps in the real driver pass.
Not sure what to do about this and will have to think more.

**Comment by Jacalz** [comment]
Yeah this does work fine on desktop. Is there something wrong with the test code not marking widgets as rendered?

**Comment by andydotxyz** [comment]
> Yeah this does work fine on desktop. Is there something wrong with the test code not marking widgets as rendered?

Looking into it to see if I can find an answer to that question!

**Comment by Jacalz** [comment]
The code looks good and functions good but it does not seem to fix the linked issue? My application seems to still freeze when I try to reproduce the bug in the issue.

**Review by Jacalz — APPROVED** [review]
Ignore my previous message. This works fine :)

**Pull request merged**
