### PR TITLE
Feature: menu icons

### LINKED ISSUE #1752: MenuItem support Icon
### Is your feature request related to a problem? Please describe:
MenuItem supports text, but does not support Icon.

### Is it possible to construct a solution with the existing API?
no

### Describe the solution you'd like to see:
The addition of `MenuItem.Icon fyne.Resource` to be displayed next to the existing `MenuItem.Label string`

### PR DESCRIPTION
**Pull request by toaster**
### Description:

This PR adds support for icons to (non-native) menus.
It also fixes a bug where the expand icon of a deactivated menu item with submenu was not greyed out.

Fixes #1752

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is excellent thanks @toaster. Is the plan to do the macOS icons in a separate PR?

**Comment by toaster** [comment]
@andydotxyz, here’s the MacOS native support.

**Comment by andydotxyz** [comment]
This is so cool!
One question - is it intentional that the `ColorizeSVG` is a new public method?
If so it's missing the "Since:" tag. If not then it could be internal for now...

**Comment by toaster** [comment]
Ah, yes, I wanted to move it to `internal/painter` first but that gave me a cyclic dependency.
I could add a new internal package `svg` for this. I would also suggest to move the SVG to image conversion there.
WDYT?

**Comment by andydotxyz** [comment]
> Ah, yes, I wanted to move it to `internal/painter` first but that gave me a cyclic dependency. I could add a new internal package `svg` for this. I would also suggest to move the SVG to image conversion there. WDYT?

This makes sense. Out of interest what was the cycle?

**Comment by toaster** [comment]
> This makes sense. Out of interest what was the cycle?

When moving the method from `theme` to `internal/painter` the `theme` package of course gets dependent on `internal/painter` which already depends on `theme`.

**Comment by andydotxyz** [comment]
Thanks for tidying this up. I am not quite sure of `PaintImageWithFillModeIgnored` - isn't this exactly the same as passing `PaintImage` where the image as any fill except `ImageFillOriginal`? It looks like an API that does not add functionality...

**Comment by toaster** [comment]
> Thanks for tidying this up. I am not quite sure of `PaintImageWithFillModeIgnored` - isn't this exactly the same as passing `PaintImage` where the image as any fill except `ImageFillOriginal`? It looks like an API that does not add functionality...

Yes, but:
The places calling this method don’t provide a canvas (because they probably don’t even have one). If you do this to the other `PaintImage` method and the image happens to have `ImageFillOriginal`, the app will crash with an NPE.

I think an API should not be designed around the provided feature(s) but should fulfil purposes as exact as possible.
For OS icon creation (render a Fyne image into a plain Go image) we don’t want to care about things like fill mode or providing a canvas. Whereas these are important for rendering a widget onto the screen.
It might be that both tasks share a lot of common code but that’s an implementation detail.

One could argue that a single `PaintImage` method could ignore the fill mode when no canvas is given but I think this would be non-obvious behaviour which is hard to justify.

**Comment by andydotxyz** [comment]
> If you do this to the other PaintImage method and the image happens to have ImageFillOriginal, the app will crash with an NPE.

Can we fix the nil crash rather than working around it?

If you don't care about the fill mode then don't set one and the `PaintImage` existing API will work, that is why we have sensible zero values for most fields. (the special case is FillOriginal which has to be set intentionally).

**Review by andydotxyz — APPROVED** [review]
Excellent, thank you so much!

**Pull request merged**
