### PR TITLE
interface generalization

### PR DESCRIPTION
**Pull request by tehsphinx**
### Description:
A more general use of existing functionality is possible by using the appropriate interfaces. This merge request applies that in 2 places.

### Checklist:
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
In the draw code we want to know that images are `NRGBA` Because that is the pixel format used lower down. Using the abstraction interface could lead to converting colour models during paint, which is going to add overhead.

**Comment by Jacalz** [comment]
I agree with @andydotxyz on this. At the same time, I also don't really see the need for the other interface generalizations. Using interfaces is slower than just using the pointers and if we don't use something else than those specific types, I don't see why we would switch to the interfaces.

**Comment by andydotxyz** [comment]
I guess I could see the argument if these were public methods...

**Comment by tehsphinx** [comment]
We can close this is you don't agree. It's just a suggestion. And yes, it definitely would make a lot more sense if the methods/functions were public.

**Pull request closed without merging**
