### PR TITLE
 [widget.NewMultiLineEntry() Bugs report]

### PR DESCRIPTION
**Pull request by jorzion**
Fix the problem that the mouse cannot be used to adjust the cursor position in NewMultiLineEntry.

 

### Description:

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by jorzion** [comment]
bug2-1

bug2-2

**Review by andydotxyz — CHANGES_REQUESTED** [review]
A nice fix, thanks. Please update for the CI failures.
Also can you base on develop? That is where we do our development work.

**Comment by jorzion** [comment]
> 

Do I need to submit the merge update again?

**Comment by andydotxyz** [comment]
I tried to rebase using GitHub UI for you but it did not work.
You should be able to rebase at your end and force-push the result.
Or a new PR, if that is easier.

**Comment by jorzion** [comment]
Okay.
Other bug:
bug1

**Comment by jorzion** [comment]
`go

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("widget.NewMultiLineEntry() has bugs")
	w.Resize(fyne.NewSize(800, 600))
	w.SetFixedSize(true)
	w.CenterOnScreen()
	textArea := widget.NewMultiLineEntry()
	textArea.Wrapping = fyne.TextWrapBreak

	textArea.SetText(`About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	About
	Fyne is an easy-to-use UI toolkit and app API written in Go. It is designed to build applications that run on desktop and mobile devices with a single codebase.
	
	Version 2.1 is the current release of the Fyne API, it introduced RichText and the DocTabs container, as well as the document storage API and FyneApp.toml metadata support. We are now working towards the next big release, codenamed bowmore and more news will follow in our news feeds and GitHub project.
	`)

	w.SetContent(container.NewMax(textArea))

	w.ShowAndRun()
}
`

**Comment by jorzion** [comment]
The New PR https://github.com/fyne-io/fyne/pull/2725

**Comment by andydotxyz** [comment]
I will close as this is superceded

> Please verify the bug I submitted in the last comment. [#2723 (comment)](https://github.com/fyne-io/fyne/pull/2723#issuecomment-1006180620)

Please report issues using an issue instead of a PR.

**Comment by jorzion** [comment]
> I will close as this is superceded
> 
> > Please verify the bug I submitted in the last comment. [#2723 (comment)](https://github.com/fyne-io/fyne/pull/2723#issuecomment-1006180620)
> 
> Please report issues using an issue instead of a PR.

The same problem encountered by another user. https://github.com/fyne-io/fyne/issues/2698

**Pull request closed without merging**
