### PR TITLE
Fix *BSD systems using the wrong (and slow) window resize

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

I realized that we had decided to group Linux into its own implementation without considering that *BSD systems would want to use the same fast file path.

Draft: Currently untested on BSD. The logic is sound and I just didn't forget my branch so opened.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
I think this ought to go into a v2.4.x release when merged.

**Comment by sdassow** [comment]
Oh, nice! Going to try this later on OpenBSD. Noticed it before, but didn't start debugging since I'm also hacking on the window manager I'm using and couldn't rule out that it wasn't my fault so far as I'm actually working on window resizing logic.

**Comment by sdassow** [comment]
Tested and works as intended on OpenBSD.

**Comment by Jacalz** [comment]
Thanks for testing 👍

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
