### PR TITLE
Move the fixed size ensuring size to the end of window setup

### LINKED ISSUE #2819: window.Resize() does not work if SetFixedSize(true) is set after
### Describe the bug:
In Fyne 2.1.3 the order of  window.Resize() and SetFixedSize(true) matters. This is not the case in Fyne 2.1.2

### To Reproduce: 

This code only works on Fyne 2.1.2. On Fyne 2.1.3, it does not resize the window w which appears minimized :
```go
w.Resize(fyne.NewSize(finalWidth, finalHeight)) 
w.SetFixedSize(true)
```

Whereas this code works perfectly 
```go
w.SetFixedSize(true)
w.Resize(fyne.NewSize(finalWidth, finalHeight)) 
```

### Device :
 - **OS:**  Linux Manjaro 
 - **Version:**  up do date 2022-03-04
 - **Go version:**  go1.17.6 linux/amd64
 - **Fyne version:** 2.1.3

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes order of operation issues such as #2819

Fixes #2819

### Checklist:

- [ ] Tests included. <- subtlety in render size for some Linux WM
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Tagged @Bluebugs on this as I think you worked on this recently

**Comment by Bluebugs** [comment]
This sadly doesn't fix @kheyse-oqton problem in #2800. It is still a progress as I get a 0x0 window (and crash) with master and the provided example. I think it is an issue where the proper size is only really known after the windows has been built.

**Comment by andydotxyz** [comment]
I removed #2800 from the fix list earlier today, this remains just a fix for #2819 as the description states above.
Can it be reviewed on the merits of that regression fix please?

**Review by Bluebugs — APPROVED** [review]
I am a bit uneasy that it doesn't fix #2800 as this patch change the behavior in that issue, but I can see that it does improve the situation. So let's move forward with this.

**Pull request merged**
