### PR TITLE
Test moving travis to Go 1.15 and speeding up travis builds

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:
This PR tries to move Travis to using the latest Go release and also makes sure to apply some changes to make builds faster.
It now uses caching for modules and apt packages while now only running code checks where we tell it to (basically means that we don't run it on each operating system virtual machine).

### Checklist:

- [-] Tests included.
- [-] Lint and formatter run with no errors.
- [ ] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
This has improved the run time for travis builds by about 2 minutes. See before and after:
image
image

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Please do t remove 1.12 - we need to continue checking compatibility

**Comment by Jacalz** [comment]
Oh, I see. I honestly thought that people would have dropped of that by now, but I see that Ubuntu 19.10 still uses that. Should we just drop testing for 1.13 and switch that to 1.12?

**Comment by andydotxyz** [comment]
Yeah, going back to the first item being 1.12 works.
At some point we can drop older versions - but that is a separate decision and not something to do accidentally by stopping checking in CI ;).

**Comment by Jacalz** [comment]
Yeah absolutely. Go 1.12.x is now back in again :)

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
