### PR TITLE
Update list.go

### PR DESCRIPTION
**Pull request by ruanwenfeng**
This min value is equal to -1 when minimized.  and line 192 panic: runtime error: index out of range [-1]

### CODE REVIEW

**Comment by andydotxyz** [comment]
It is not clear which value is -1 and when. Is it possible that your data callback `Length()` is returning -1 incorrectly?

**Comment by ruanwenfeng** [comment]
> It is not clear which value is -1 and when. Is it possible that your data callback `Length()` is returning -1 incorrectly?

@andydotxyz the line I modified, the min variable is qual to -1  when the software is minimized. The list widget needs to be displayed on the interface.

**Comment by andydotxyz** [comment]
Yes, but as that is a result of a Min() calculation it might be good to know the cause - which of those values was incorrect?
It will influence what makes a good fix for the issue.

**Comment by ruanwenfeng** [comment]
> Yes, but as that is a result of a Min() calculation it might be good to know the cause - which of those values was incorrect?
> It will influence what makes a good fix for the issue.

@andydotxyz Yes, I agree with you. It seems to be caused by the l.visibleItemCount variable.  we cang change the == in line 185 to <=

**Comment by andydotxyz** [comment]
> change the == in line 185 to <=

Perfect :)

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
Thanks for the contribution, it will be in 1.4.1 release

**Pull request merged**
