### PR TITLE
Now we have standard padded widgets we don't need padding in collections

### PR DESCRIPTION
**Pull request by andydotxyz**
I think the 2.0 larger widgets meant that collections are too padded.
This is now addressed.

I re-added a leading padding to tree so the icons were not (almost) flush to edge.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
Hmm, I am not so sure about this. Seems like quite a breaking change. While I think it probably makes https://github.com/fyne-io/fyne/pull/2181 work better, it makes wormhole-gui behave significantly worse.
image

**Comment by andydotxyz** [comment]
I’m sorry but I can’t see what is broken in the screenshot

**Review by stuartmscott — APPROVED** [review]
As agreed on Slack, this should not land in a patch release, and instead should target the next minor release (most likely 2.1.0).

**Comment by andydotxyz** [comment]
Thanks @stuartmscott that was my intent. I guess the original message was not that clear. Thanks

**Pull request merged**
