### PR TITLE
Mobile menu

### LINKED ISSUE #413: Add mobile menu support
Burger button and side bar?

### PR DESCRIPTION
**Pull request by andydotxyz**
**Description**

Adding mobile menu support. A burger icon with a drop down for the menu list, each then drops out a menu like on desktop.

Fixes #413 

**Checklist**

- [x] Tests included
- [x] Lint and formatter run with no errors
- [x] Tests all pass

This needs further exploration, some tests and a little tidying up - but I wanted to get feedback at this stage before I take it further as it's a pretty big item

### CODE REVIEW

**Comment by andydotxyz** [comment]
Here are some screenshots to show what it's like if folk don't want to install and try it :)

menu-expanded
menu-panel
menu-button

**Comment by andydotxyz** [comment]
Items to do before merge (assuming folk like the approach):

- [ ] Add tests
- [ ] Remove code duplication / tidy code in tree walks
- [ ] Respect hardware padding (on iOS button is half hidden behind screen corner)

**Comment by andydotxyz** [comment]
How about this for alignment?

Screenshot 2019-10-31 at 08 04 26

**Comment by joeblew99** [comment]
Impressive stuff dude !!!

**Comment by andydotxyz** [comment]
Updated again :) 
Screenshot 2019-11-01 at 19 13 56

**Pull request merged**
