### PR TITLE
Specific command compiling for android (from develop).

### PR DESCRIPTION
**Pull request by mrjrieke**
### Description:
I found this change highly useful for development.  I don't know if it interests you at all, but here it is if you like.

Fixes #???

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by mrjrieke** [comment]
Cherry picked from https://github.com/fyne-io/fyne/pull/1076

**Comment by andydotxyz** [comment]
Oh I just noticed this was made a draft, sorry about that - was there more to be done here?

**Comment by mrjrieke** [comment]
No, all done.

**Comment by mrjrieke** [comment]
Happy to help.  As I come across other things I find useful, I will try to help as I can.  This project you have going is really something special.  Thank you so much!

**Pull request merged**
