### PR TITLE
Password reveal/conceal support in PasswordEntry widget

### LINKED ISSUE #452: Password reveal/conceal support in PasswordEntry widget.
Allow users choose between concealing or revealing password when password texts entry widget is used.

### PR DESCRIPTION
**Pull request by lucor**
**Description**

Password reveal/conceal support in PasswordEntry widget

Fixes #452

**Checklist**

- [x] Tests included
- [x] Lint and formatter run with no errors
- [x] Tests all pass

(where applicable)

- [ ] Public APIs match existing style
- [ ] Any breaking changes have a deprecation path or have been discussed

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is visually really clean now, thanks for the hard work.
I wonder if perhaps it should avoid losing focus by requesting focus back on the entry each time the icon is tapped (as by default this removes focus) - what do you think?

**Comment by andydotxyz** [comment]
The code overall looks good, though the password reveal functionality could do with some tests.
I noticed that the following problem could occur:

	pe := widget.NewPasswordEntry()
	pe.Password = false

In this situation we end up with a regular entry with the new icon attached.
Perhaps it's visibility should check also that it's still a password entry?

**Comment by lucor** [comment]
I can't figure a way to allow backward compatibility (i.e.have an Entry with Password field set to true) without adding an internal field to keep track of the feature.
But I agree that we can use only the Password field to store the "visibility" state.
Updated the code to address the last one.

**Comment by andydotxyz** [comment]
Travis forgot the connection again - this did pass, so merging.
Thanks :)

**Pull request merged**
