### PR TITLE
Adding emoji support, in this iteration using an embedded font

### LINKED ISSUE #3790: Text doesn't render in Windows VM
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Text doesn't render on Windows (11) VirtualBox VM running in an Ubuntu host. Where the text should be is just an empty space. Hardware acceleration is enabled for the VM. This is a regression since earlier Fyne versions on the same VM with the same settings rendered text just fine. This problem is not present in a non-VM install of Windows.

### How to reproduce

Create a Windows 11 VM inside VirtualBox on Ubuntu (no idea if this is present with other combos of virtualization software, host OS, etc). Run the latest fyne demo.

### Screenshots

[screenshot](https://user-images.githubusercontent.com/5303666/230256584-3f8a0df7-23b1-4588-8bd8-14c62c60373f.png)

### Example code

fyne demo @ latest

### Fyne version

2.3.3

### Go compiler version

1.19.4 windows/amd64

### Operating system and version

Windows 11 (VM guest)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Emoji support using a flat SVG file bundled in apps.
Additionally to get colour font I stepped out the single-channel-text work which had associated bugs anyhow... should discuss.

Source font files go from 6MB to 18MB (maybe we should see if go:embed helps?
Debug app size on this machine went up 29%, stripped release binary was around 27%.

This increase in size is something to discuss. On later iterations we will add font lookup support so apps can be packaged without these fonts, but for now I don't know if it's worth making emoji specifically as an optional compile element?

Fixes #3790, #3879

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.
- [x] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by andydotxyz** [comment]
I cannot replicate the test failure on hyperlink focus - with 1.17 or 1.20 - anyone got ideas?

**Comment by andydotxyz** [comment]
> I cannot replicate the test failure on hyperlink focus - with 1.17 or 1.20 - anyone got ideas?

Never mind, it was just temporary... no idea how that happened but it's gone

**Comment by Jacalz** [comment]
As discussed on Slack, it would be nice to either have this `opt-in` or `opt-out`. The large binary size increase impacting a lot of applications, even those that have no need for emoji support, does not feel great. 

> Source font files go from 6MB to 18MB (maybe we should see if go:embed helps?

My testing that I did a while back seemed to indicate that it is ever so slightly bigger to use `go:embed` (we're talking kilobytes at most probably) because of the import of the embed package, I assume. Our own bundling is actually better there.

**Comment by andydotxyz** [comment]
It's now opt-out with the `no_emoji` build tag, matching the new tags that Tilo has added for other disabling aspects

**Review by Jacalz — COMMENTED** [review]
Are all the GL reverts supposed to be there? 

The code looks good otherwise and works great here. I'm "only" seeing a 22% size increase for stripped binaries actually. It looks better than I expected but the build tag is still a very nice addition 😀

**Comment by andydotxyz** [comment]
Without any GL revert the emoji will be in greyscale because the text was moved to single channel.
I could have left some in and/or turned it off with a flag, but given the code that would be off is causing two (linked) bugs it seemed sensible to revert the optimisation and call them fixed at the same time.

**Comment by Jacalz** [comment]
Ah, I see. I couldn't find any reference to why it was reverted so I thought it was a mistake

**Review by Jacalz — APPROVED** [review]

**Comment by andydotxyz** [comment]
Sorry there was a merge conflict crept into go.mod, updated.
Can you re-approve @Jacalz ?

**Pull request merged**
