### PR TITLE
Add an AllString validator for chaining together string validators

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This adds a new group validator for chaining together validators.
It is one of the validators mentioned in #1268 and might also (at least partially) help resolve the use case in #2562.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
I don't know if there is a use case for a "pass any" but if there is, we can certainly add one then. I agree that "All" is a better naming scheme and can work better with similar names in the future.

**Comment by Jacalz** [comment]
> One last thought - `validation.NewAllString` vs `validation.AllStrings` - I know we normally used `New` in this package for new validators, but in this case we could probably argue it's not creating a new one? Just a thought.

It is kind of creating a new validator from the validators that you passed, so I think it kind of makes sense as it is?

**Comment by andydotxyz** [comment]
Not sure that the singular form (no “s”) reads correctly does it?

**Comment by Jacalz** [comment]
> Not sure that the singular form (no “s”) reads correctly does it?

Hmm, yes and no. I went with "String" because it takes string validators and returns just one string validator, which as it happens, also only takes one string as an argument. With "Strings" one could think that it is a validator that takes more than one string? I'm not sure what's best?

**Comment by andydotxyz** [comment]
It is a tough one to know if we're getting it right. I think mostly "all string" doesn't read too well due to the order of words - how can you have "all" of a singular "string"... (thinking about group again "string group" flows, but "group string" doesn't - it would be "group of strings").

I am trying to explore this myself to see if anything becomes clear. My latest question is to compare with the hypothetical "Any" addition. So `validation.AnyString` does make sense, because it is asking for any one to check - but on that logic `validation.AllStrings` needs the "s" to communicate that many will be used to pass validation... I think.

Maybe someone with a fresh set of eyes could look over the various challenges / suggestions.

**Comment by Jacalz** [comment]
I changed the name to `AllStrings`. Didn't seem like anyone else wanted to chime in on the matter.

**Comment by stuartmscott** [comment]
> Didn't seem like anyone else wanted to chime in on the matter.

I did, but it was ignored - https://gophers.slack.com/archives/CK5U4BU87/p1635689185251500

**Comment by Jacalz** [comment]
> > Didn't seem like anyone else wanted to chime in on the matter.
> 
> 
> 
> I did, but it was ignored - https://gophers.slack.com/archives/CK5U4BU87/p1635689185251500

Oh, sorry. I must have missed that at the time. However, I think we have already thought about that before. I had hoped that more people would jump in with concrete answers.

**Review by andydotxyz — APPROVED** [review]
I think the current naming works for what @stuartmscott was suggesting as well (i.e. `NewAllFloats`

**Pull request merged**
