### PR TITLE
Simple attempt to fix form tests 🤞

### PR DESCRIPTION
**Pull request by fpabl0**
### Description:

Use `test.ApplyTheme` instead of `app.Settings().SetTheme` to avoid data races in form tests.

### Checklist:

~~- [ ] Tests included.~~
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
Nice stuff. Looks green now. Make sure to re-run the tests a few times to make sure that it sticks before we approve 🙂

**Comment by fpabl0** [comment]
> Nice stuff. Looks green now. Make sure to re-run the tests a few times to make sure that it sticks before we approve

Got it. I have re-run the tests in my fork and it seems to passed consistently, but I will do the same here, hope it solves those tests

**Comment by fpabl0** [comment]
@Jacalz it seems it works well :), I have rerun the tests 5 times here and 3 times in my fork and they always passed :)

**Review by Jacalz — APPROVED** [review]
Wonderful. Would have been a nice change even if it hadn't fixed the tests 🙂

**Comment by fpabl0** [comment]
Hope this finally solves those flaky tests

**Pull request merged**
