### PR TITLE
Ensure current index is positive + test

### PR DESCRIPTION
**Pull request by stuartmscott**
I missed a positive index check in #760. Added test which fails if check is missing.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Travis passed but didn’t report

**Comment by stuartmscott** [comment]
> continuous-integration/travis-ci Expected — Waiting for status to be reported

> Travis passed but didn’t report

This is happening on other PRs too

**Comment by andydotxyz** [comment]
Should be fixed again now

**Comment by stuartmscott** [comment]
Thanks!

**Pull request merged**
