### PR TITLE
Fix conflict of struct name itemAndID

### PR DESCRIPTION
**Pull request by Dorbmon**
### Description:

When build in the develop branch, got error:
```
../../widget/list.go:529:6: itemAndID redeclared in this block
../../widget/gridwrap.go:467:6: other declaration of itemAndID
```
This is because two structure uses the same name in the same package.
I renamed these two structures.
### Checklist:

- [ ] Tests included.
- [X] Lint and formatter run with no errors.
- [X] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
I think you have accidentally based this on top of another PR instead of on the develop branch

**Comment by dweymouth** [comment]
Thank you for this! There were two separate PRs for List and GridWrap that were never tested together! But as andydotxyz said, it looks like you have the wrong base commit for this PR.

**Comment by Dorbmon** [comment]
Sorry for that. I choose the wrong branch to create the new branch.

**Comment by Dorbmon** [comment]
I think I based on the my another PR.

**Pull request closed without merging**
