### PR TITLE
Optimize png images and svg images - WIP

### PR DESCRIPTION
**Pull request by Jacalz**
**Description**

All `png` and `svg` images in the repository have been optimized to reduce their size.
The size reduction will hopefully lead to faster downloads of the library and slightly smaller memory footprint when running an apps.
The `png` images were optimized using [optipng](http://optipng.sourceforge.net/) and `svg` files were optimized using [svgo](https://github.com/svg/svgo).

||Old size|New size   |
|---|---|---|
|**img folder**|599,0 kB|393,0 kB|
|**icons folder**|40,6 kB|34,4 kB|
|**Total**|639,6 kB|427,7 kB|

The result is that we have decreased the total asset size by about 33%.

**Checklist**

- [x] Lint and formatter run with no errors
- [x] Tests all pass

### CODE REVIEW

**Comment by Jacalz** [comment]
I will update this PR with the bundled asset updates, but I would like to know where I can find the script to update them easily. I couldn't really find it now when I checked.

**Comment by andydotxyz** [comment]
Thanks! inside theme folder run "go run gen.go"

**Comment by Jacalz** [comment]
Thanks for the information!
I have made a new logo for the project. Is that something you would be interested in?

Icon in 512px size:
icon-512

I will replace the old icon with this new one (in 256px size), if you like it. I could also make sure that you get the original Inkscape file if you want.

**Comment by andydotxyz** [comment]
Thanks for doing that as well. We have another replacement logo ready to go but I will present this to the team for a vote as well - please don't replace it yet as this takes a little coordination.

**Comment by Jacalz** [comment]
Alright. All the optimized icons have been bundled now :+1:

**Comment by andydotxyz** [comment]
Thanks! (sorry about the tests not completing, there is an issue with our travis config but it passed OK)

**Comment by Jacalz** [comment]
There’s no need to be sorry, shit happens. I ran the testes locally anyways, to make sure that it worked as expected 😉

**Comment by andydotxyz** [comment]
Sorry @Jacalz this had to be reverted - it broke all of the SVG rendering.
I apologise for not having tested it more rigorously.

Feel free to look into why this happened or to re-submit with just raster graphics optimised.

**Comment by andydotxyz** [comment]
I think that the tests must have run against the assets pre-bundling but not after the bundle commit for some reason.
Just load fyne_demo and you'll see all the images missing

**Comment by Jacalz** [comment]
I will see if I can get the svg files to work. If not, I will just re-submit with the png images. The size decrease wasn't that big with the svg files, so worst case scenario isn't that bad...

**Pull request merged**
