### PR TITLE
test: Add RenderObjectToMarkup and RenderToMarkup functions

### LINKED ISSUE #5124: test: Add RenderToMarkup and RenderObjectToMarkup
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I would like versions of [AssertRendersToMarkup](https://github.com/fyne-io/fyne/blob/v2.5.1/test/test.go#L104) and [AssertObjectRendersToMarkup](https://pkg.go.dev/fyne.io/fyne/v2@v2.5.1/test#AssertObjectRendersToMarkup) that don't do any assertions, or use golden files. I'd like them just to return the markup version of the object/canvas, which I can then do my own assertions on.

This would give me the flexibility to use regular expressions, or other checks that don't consider the entire output.

### Is it possible to construct a solution with the existing API?

No.

### Describe the solution you'd like to see.

  I propose the following additional functions be added to `fyne.io/fyne/v2/test`

```golang
RenderToMarkup(c fyne.Canvas) string
RenderObjectToMarkup(o fyne.CanvasObject) string
```

### PR DESCRIPTION
**Pull request by flimzy**
### Description:
Adds RenderObjectToMarkpu and RenderToMarkup functions

Fixes #5124

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by dweymouth** [comment]
It looks like the test is failing on Windows

**Comment by flimzy** [comment]
> It looks like the test is failing on Windows

I don't think it's within my power to fix/debug timeouts in the Windows runners.

**Comment by dweymouth** [comment]
> > It looks like the test is failing on Windows
> 
> I don't think it's within my power to fix/debug timeouts in the Windows runners.
> 
> Do you think that is somehow related to the changes in this PR?

It looks to be related:

```
--- FAIL: TestRenderObjectToMarkup (0.00s)
    test_test.go:48: 
        	Error Trace:	D:/a/fyne/fyne/test/test_test.go:48
        	Error:      	Not equal: 
        	            	expected: "<canvas size=\"20x20\">\r\n\t<content>\r\n\t\t<circle fillColor=\"rgba(0,0,0,255)\" size=\"20x20\"/>\r\n\t</content>\r\n</canvas>\r\n"
        	            	actual  : "<canvas size=\"20x20\">\n\t<content>\n\t\t<circle fillColor=\"rgba(0,0,0,255)\" size=\"20x20\"/>\n\t</content>\n</canvas>\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,6 +1,6 @@
        	            	-<canvas size="20x20">
        	            	-	<content>
        	            	-		<circle fillColor="rgba(0,0,0,255)" size="20x20"/>
        	            	-	</content>
        	            	-</canvas>
        	            	+<canvas size="20x20">
        	            	+	<content>
        	            	+		<circle fillColor="rgba(0,0,0,255)" size="20x20"/>
        	            	+	</content>
        	            	+</canvas>
        	            	 
        	Test:       	TestRenderObjectToMarkup
        	Messages:   	existing master is equal to rendered markup
--- FAIL: TestRenderToMarkup (0.00s)
    test_test.go:100: 
        	Error Trace:	D:/a/fyne/fyne/test/test_test.go:100
        	Error:      	Not equal: 
        	            	expected: "<canvas padded size=\"9x9\">\r\n\t<content>\r\n\t\t<circle fillColor=\"rgba(0,0,0,255)\" pos=\"4,4\" size=\"1x1\"/>\r\n\t</content>\r\n</canvas>\r\n"
        	            	actual  : "<canvas padded size=\"9x9\">\n\t<content>\n\t\t<circle fillColor=\"rgba(0,0,0,255)\" pos=\"4,4\" size=\"1x1\"/>\n\t</content>\n</canvas>\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,6 +1,6 @@
        	            	-<canvas padded size="9x9">
        	            	-	<content>
        	            	-		<circle fillColor="rgba(0,0,0,255)" pos="4,4" size="1x1"/>
        	            	-	</content>
        	            	-</canvas>
        	            	+<canvas padded size="9x9">
        	            	+	<content>
        	            	+		<circle fillColor="rgba(0,0,0,255)" pos="4,4" size="1x1"/>
        	            	+	</content>
        	            	+</canvas>
        	            	 
        	Test:       	TestRenderToMarkup
        	Messages:   	existing master is equal to rendered markup
FAIL
FAIL	fyne.io/fyne/v2/test	0.255s
```

**Comment by dweymouth** [comment]
Looks like it's a \n vs \r\n newline difference

**Comment by flimzy** [comment]
Ah right. Looks like I saw the timeout on a different runner. Let me do some newline fixing.

**Comment by dweymouth** [comment]
You forgot to import the `strings` package

**Comment by flimzy** [comment]
> You forgot to import the `strings` package

That is SO weird, considering it's automatic. Not sure how I missed committing that.

**Comment by andydotxyz** [comment]
If possible please avoid force-pushing after review, it means we can't see what has changed since the last review.

**Review by andydotxyz — APPROVED** [review]
Thanks so much for this neat addition

**Pull request merged**
