### PR TITLE
Replace empty interface with any type

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

For #3242 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
Are you certain that these are interchangable and that this does not impact code usage at all?
i.e. if someone has `var thingy interface{}` and it is getting or setting something that is now `any` will the compiler translate every time without errors?

**Comment by Jacalz** [comment]
I'm pretty certain it's fine. It is supposed to be an alias for the other, i.e. `var ListItemID = int` allows the passes functions to use `int` as type.

**Review by andydotxyz — DISMISSED** [review]
Ah yes an "=" alias - I missed that

**Comment by andydotxyz** [comment]
> Had to force-push a rebase to fix a merge conflict. Will likely require a re-approval. Sorry

This only happens if you rebase on top of conflicts though, merging in the develop branch allows the conflict to be resolved plainly in the new commit. Isn't that how we normally merge conflicts?

**Comment by Jacalz** [comment]
> This only happens if you rebase on top of conflicts though, merging in the develop branch allows the conflict to be resolved plainly in the new commit. Isn't that how we normally merge conflicts?

Not for me. I have `git` set up to always rebase by default. I'm not a fan of merge commits

**Review by dweymouth — APPROVED** [review]

**Comment by andydotxyz** [comment]
> > This only happens if you rebase on top of conflicts though, merging in the develop branch allows the conflict to be resolved plainly in the new commit. Isn't that how we normally merge conflicts?
> 
> 
> 
> Not for me. I have `git` set up to always rebase by default. I'm not a fan of merge commits

Is it possible to avoid them when conflicts are an issue? As you know force push does make the review much harder.

**Comment by Jacalz** [comment]
I can try to remember to force git to add a merge conflict in cases where review is ongoing. But is it really an issue in this case, or similar, where it already has been approved?

**Comment by andydotxyz** [comment]
As we would point out to other contributors a force-push (even if the PR has been approved) requires a full re-review as there is no trace of what has changed since the review

**Comment by Jacalz** [comment]
Yeah that's true. I'll have to try to remember to force git to do a merge commit

**Pull request merged**
