### PR TITLE
Fix last row sometimes being missing in List

### LINKED ISSUE #4909: Sometimes the last list row that should be visible doesn't show
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Sometimes the last should-be-visible row in a list doesn't show until you scroll a bit past where it should start being visible, and if it's the last row, depending on the list widget's size (ie viewport size) it may not show at all

### How to reproduce

it's been a known issue for awhile but just never had a ticket tracking it

### Screenshots

_No response_

### Example code

any app with a list

### Fyne version

develop

### Go compiler version

all

### Operating system and version

all

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Fixes #4909 

The `calculateVisibleRowHeights` calculation derived `maxRow` as the max row that could possibly be visible, but the rest of the function treated it as the first row that couldn't be visible (i.e. inclusive vs exclusive bound issue).

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

### CODE REVIEW

**Comment by dweymouth** [comment]
A bunch of list tests are failing as they seem to depend on the old incorrect behavior. I'd appreciate if someone can check my assumptions before I update them all though.

**Comment by dweymouth** [comment]
> It does seem as though you've found an off-by-one. Just make sure it does not relate to a header row/column counting...

List doesn't have header rows builtin like table

**Comment by andydotxyz** [comment]
Haha you got me :) I should sleep more!

**Comment by dweymouth** [comment]
> Haha you got me :) I should sleep more!

Also just that I'm quite familiar with the List API as something like 40% of my app UI is different kind of lists (with another 40% being gridwraps maybe) 😄

**Review by Jacalz — COMMENTED** [review]
Hmm. Is it possible to get some kind of code to reproduce this or a test that clearly shows it? I notice no difference in lists on my computer.

**Comment by dweymouth** [comment]
It was a rounding error so it only reproduced at certain list widget sizes relative to the row size. Larger rows (ie taller than just a label) seemed to reproduce the problem more often too. Drag the window size around while being scrolled right near the bottom of the list and eventually you should get the original problem to repro

**Comment by andydotxyz** [comment]
I was able to replicate the issue with one of my apps and this does indeed fix it.

**Review by andydotxyz — APPROVED** [review]
Thanks so much for solving this

**Pull request merged**
