### PR TITLE
Preferences improvements, fix locking and watch file

### LINKED ISSUE #1718: fatal error: concurrent map iteration and map write
### Describe the bug:
When updating to the latest develop version, I noticed that dragging the slider in wormhole-gui's settings caused a panic due to a fatal error. This did not occur a week or two back on develop before I updated.

### To Reproduce:
I have yet to narrow it down in a smaller code example, but it seems to be related to the change listeners.
The best way is to just draw the slider **fast** under the settings tab in [wormhole-gui](https://github.com/Jacalz/wormhole-gui/tree/develop), on latest develop.
fatal-error

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.10.4
 - Go version: 1.15.6
 - Fyne version: 5fc52fcc1b31fd8dbbbe06bf58a65faab221f208

I have successfully managed to track down that it probably is caused by https://github.com/fyne-io/fyne/commit/77a198529eed3100e070b7c6b66c351c6a2e12e8.

### PR DESCRIPTION
**Pull request by andydotxyz**
Adds monitoring preference files for changes (re-using the settings code thankfully).
It hit the map concurrency issue so I resolved that as well.
The external looking APIs are all internal so the change is non-breaking.

Fixes #1718

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
@andydotxyz Looks like staticcheck failed.

**Review by Jacalz — CHANGES_REQUESTED** [review]
Staticcheck is complaining about an error that isn't handled. This does fix the crash, but I am getting a lot of these errors when dragging the slider in wormhole-gui:
image

**Comment by andydotxyz** [comment]
> This does fix the crash, but I am getting a lot of these errors when dragging the slider in wormhole-gui:

Oh no! This is strange. Has the file got corrupted somehow?
I tested against a few preference based apps here and it was quite happy.

**Comment by Jacalz** [comment]
> > This does fix the crash, but I am getting a lot of these errors when dragging the slider in wormhole-gui:
> 
> Oh no! This is strange. Has the file got corrupted somehow?

I thought about that to, but removed it and tried again with the same result. It seemed to be more prominent when changing it fast.

**Comment by andydotxyz** [comment]
> It seemed to be more prominent when changing it fast.

Ah, I think I have not tested lots of changes in a row. Will see if I can replicate.

**Review by Jacalz — APPROVED** [review]
Works great now. Thanks for the fix :+1:

**Pull request merged**
