### PR TITLE
Fix #2222 and #2220 for buttons, once more with feeling

### LINKED ISSUE #2220: Themed resources are drawn with the wrong colors if a theme's Color() method returns certain types of Colors
### Describe the bug:
I've written a fix for this, and a bunch of tests. (I'm also going to make a pull request after posting this)

Fyne displays incorrect colors in PrimaryThemedResources (such as checkboxes) which are SVGs, when a theme's Color method returns an RGBA64, NRGBA64, RGBA with 0<a<0xff, NRGBA with 0<a<0xff, Alpha16, Gray16, or any custom Color implementation where the least significant byte of each component returned by RGBA() is not equal to the most significant byte. The correct colors are only shown with RGBA with a=0 or a=0xff, Alpha, or Gray, and those only appear correct because their RGBA() method simply clones each 8 bit component of the color into both the high and low byte of the 16 bit output components (Go's (color.RGBA) RGBA() returns r<<8|r, g<<8|g, b<<8|b, a<<8|a, where r is uint32(c.R), etc). The reason it gives incorrect colors when 0<a<0xff for RGBA and NRGBA is because of the alpha-premultiplication (RGBA has it built into the components, unless an RGBA is incorrectly constructed without it, and NRGBA's RGBA() multiplies the alpha into the r, g, and b return values), and theme/svg.go's colorToHexAndOpacity's current code is written as if it expects RGBA() to return non-alpha-premultiplied values (it doesn't remove the alpha-premultiplication) whose most significant byte matches their least significant byte (it doesn't >>8 the return values from RGBA() before casting them to bytes).

I also found the same problem in other places in Fyne's code:
- dialog/base.go's themedBackgroundRenderer's Refresh()
- test/markup_renderer.go's markupRenderer's setColorAttrWithDefault
- test/markup_renderer.go's rgbaColor
- widget/button.go's buttonColor() (which appears to have another issue as well, which I'll have to make a separate issue about)

I noticed this because I was returning an (opaque) NRGBA64 from a custom Theme's Color method. I have a video of that below.

(When I looked into this, I found out that svgs can't support 64 bit colors anyways, but this still seems like a bug worth fixing, especially since not all resources are SVGs, and there's other code with the same problem that doesn't use SVGs.)

### To Reproduce:
Steps to reproduce the behaviour:
1. Colorize a resource with NRGBA64{R: 0xff00, G: 0xffff, B: 0x00ff, A: 0xffff}.
2. Draw it.
3. It looks cyan when it should look yellow.
4. Do it again but give it an alpha value of 0x7fff.
5. It looks like a translucent light green color when it should look like a translucent yellow color.

### Video:
In this video, I change the value of an NRGBA64 color returned by a theme by dragging a hue slider (which goes from 0 to 360). The color created is opaque, and generated from converting HSL to RGB. You can see everything in the window change at the correct rate except the checkbox, which changes much more quickly because colorToHexAndOpacity is calling RGBA() and using the least significant byte of R, G, and B, instead of the most significant byte.
https://user-images.githubusercontent.com/6283593/116925385-20dd2d00-ac27-11eb-92d5-7a2c74528cfd.mp4

### Example code:
These are two of the subtests I added to theme/icons_test.go's TestColorizeResource. If colorToHexAndOpacity was working correctly, the first would be #ffff00, and the second would be #ffff00 with 50% alpha. Instead, the first is #00FFFF, and the second is #7fff7f with 50% alpha.
```go
		"NRGBA64": {
			svgFile: "circles.svg",
			color:     color.NRGBA64{R: 0xff00, G: 0xffff, B: 0x00ff, A: 0xffff},
			wantImage: "colorized/circles_yellow.png",
		},
		"translucent NRGBA64": {
			svgFile:   "circles.svg",
			color:     color.NRGBA64{R: 0xff00, G: 0xffff, B: 0x00ff, A: 0x7fff},
			wantImage: "colorized/circles_yellow_translucent.png",
		},
```

### Device (please complete the following information):
 - **OS:** Windows 10 Pro
 - **Version:** 20H2
 - **Go version:** 1.16.3 windows/amd64
 - **Fyne version:** 083f0344089df647ed3a2e33b8b77e0972b75517 (which is the last commit on the develop branch at time of writing)

### LINKED ISSUE #2222: buttonRenderer's buttonColor can generate out of range alpha values when hovered (might affect RGB too?)
### Describe the bug:
The math in widget/button.go's buttonRenderer's buttonColor() for color calculations while hovering appears to be very wrong (in addition to being affected by #2220), but I'm not sure what it is actually trying to do.

At present it is doing this when a button is hovered:
```go
		bg := theme.ButtonColor()
		if r.button.Importance == HighImportance {
			bg = theme.PrimaryColor()
		}
		dstR, dstG, dstB, dstA := bg.RGBA()
		srcR, srcG, srcB, srcA := theme.HoverColor().RGBA()
		srcAlpha := float32(srcA) / 0xFFFF
		dstAlpha := float32(dstA) / 0xFFFF
		targetAlpha := 1 - srcAlpha*dstAlpha
		outAlpha := srcAlpha + targetAlpha
		outR := (srcAlpha*float32(srcR) + targetAlpha*float32(dstR)) / outAlpha
		outG := (srcAlpha*float32(srcG) + targetAlpha*float32(dstG)) / outAlpha
		outB := (srcAlpha*float32(srcB) + targetAlpha*float32(dstB)) / outAlpha
		return color.RGBA{R: uint8(uint32(outR) >> 8), G: uint8(uint32(outG) >> 8), B: uint8(uint32(outB) >> 8), A: uint8(outAlpha * 0xFF)}
```

The problem here is that the math doesn't make any sense, even if it's accounting for premultiplication (I'm not sure if it is or not). You can see that if you just look at what's going on with the alpha values:
Let's assume srcA=51, dstA=204.
srcAlpha will be 0.2, and dstAlpha will be 0.8.
targetAlpha = 1 - 0.2 \* 0.8 = 0.84
outAlpha = 0.2 + 0.84 = 1.04
The alpha value that is used in the new color.RGBA will be uint8(1.04\*0xFF).
1.04\*0xFF is 265.2, or 0x109, and so when it's cut off to just 8 bits, the color.RGBA will have an alpha value of 0x09, which is equivalent to if outAlpha had been 0.035.

So that seems like an obvious bug, but less obvious is what the code is *supposed* to be doing.
I checked all the other things that can be hovered, but they pretty much all just set their color to HoverColor. This seems to be something new.

(This doesn't even get into how the alpha calculations may be screwing up the colors too - they'd be screwed up anyways from just having alpha due to #2220, which I haven't fixed for this method)

### To Reproduce:
Steps to reproduce the behaviour:
1. If you want to see it visually, try creating a theme whose background color is 0xff0000, button color is 0x00ff00 with alpha 204, and hover color is 0x0000ff with alpha 51, and a window with a button on it that you can move the mouse over to see what happens. Given that #2220 also applies, the results will probably be confusing. Also you can't actually see the alpha values this way, you'd have to try to infer them, which would be difficult given that the color values won't necessarily make any sense either...

### Device (please complete the following information):
 - **OS:** Windows 10 Pro
 - **Version:** 20H2
 - **Go version:** 1.16.3 windows/amd64
 - **Fyne version:** 083f0344089df647ed3a2e33b8b77e0972b75517

### PR DESCRIPTION
**Pull request by AmanitaVerna**
### Description:
- Replaces the math used for blending the hover color in button.go's buttonRenderer's buttonColor() to fix #2222.
- Fixes the last remaining cases of #2220 that I've found, in buttonColor() and in button.go's newButtonTapAnimation().
- Adds a math-based test which uses an alternate way of calculating the same blending operation to test buttonRenderer's hover code against (TestButton_Hover_Math in button_internal_test.go).
- Updates the hover test image used by button_test.go's TestButton_Hover()
- Updates a bunch of hover-related tests so that they look for the corrected output from buttonColor(), by updating the four XML files and one image that they test against.

Fixes #2222
Fixes #2220

### Checklist:
- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass. (for real this time, I think. Except when unrelated things sometimes randomly fail.)

(Also, thanks @andydotxyz for the advice on how to do things in order to have a clean commit history)

### CODE REVIEW

**Comment by AmanitaVerna** [comment]
The failing tests do not appear to use hovering, and presumably each of the two had one of those random glitches that caused them to fail.

**Comment by Jacalz** [comment]
Do you think that you could name the PR titles after what the PR does next time? I prefer that because mentioning what issue it fixes, is just another number to remember. Thanks :)

I would have preferred something like “Fix more button color issues” or something along those lines.

**Comment by AmanitaVerna** [comment]
Sure, I'll keep that in mind for next time.

**Comment by AmanitaVerna** [comment]
If there is a way I can make github re-run the tests, I don't see it

**Comment by Jacalz** [comment]
I think you might need collaborator access for that to be available. I'll kick them for you.

**Review by andydotxyz — APPROVED** [review]

**Review by Jacalz — APPROVED** [review]
Looks good to me. Kicked the tests to make them complete. Will merge when they do so.

**Comment by Jacalz** [comment]
I have tried kicking the tests about five times now, but the same one keeps failing all the time unfortunately.

**Comment by AmanitaVerna** [comment]
Is there any way to access the image(s) that it says it's writing out when it fails, to see what it's seeing?

**Comment by fpabl0** [comment]
Not sure if #2262 may solve the failing test here (as it is failing always) but could you please try merging `develop` into your branch?

**Comment by fpabl0** [comment]
Great! 🎉 Thanks for this and the remaining fix :)

**Comment by AmanitaVerna** [comment]
> Not sure if #2262 may solve the failing test here (as it is always failing) but could you please try merging `develop` into your branch?

That (and making the same change in a few more places that also were causing problems) seems to have solved it! Nice!

**Comment by Jacalz** [comment]
I am wondering if the test fixes perhaps should be in a separate PR? Not quite related to the button colours. Thoughts?

**Comment by AmanitaVerna** [comment]
It is true that it's not quite related to button colors, but I also have 10 failed test runs in my email inbox indicating that it just did not want to pass all the tests without the test fixes.

In order to have them separate I would (correct me if I'm wrong) need to create another branch based on current develop, submit the additional test fixes to it (or someone else could add them), wait for that to be merged, create another branch based on develop again, copy all my changes from this PR's branch into that branch, and submit that as another PR (which would make it the third one for this issue since I've already done that once). Honestly I would prefer not to have to do all that if at all possible.

**Comment by Jacalz** [comment]
I understand that the email notifications are annoying. I don't know why GitHub isn't smart enough to send them to me given that I were the one re-running the tests multiple times.

We generally don't want to have PRs contain things outside of the scope because it makes it harder to look back on changes in the future. It is not quite that hard and tedious to do. The test fixes would require a new branch and PR for them to land yes. However, this PR would just need to revert the tests and then rebase on develop after that lands.

I know that you have talked about that before @andydotxyz. What is your take on it?

**Comment by AmanitaVerna** [comment]
> I understand that the email notifications are annoying. I don't know why GitHub isn't smart enough to send them to me given that I were the one re-running the tests multiple times.

No, no, I wasn't trying to say that the email notifications were annoying. I just looked in my inbox to count how many times it had failed, because it seemed like kind of a lot of times to have to re-run the tests and still not be able to get them to pass when they weren't failing due to any changes in the PR.

> We generally don't want to have PRs contain things outside of the scope because it makes it harder to look back on changes in the future. 

That makes sense, yes. And I'm aware you prefer not to do that, but since I was specifically asked to merge develop in to incorporate @fpabl0's fix to the tests, I figured that it was probably fine to do so in this case (and then since I had already done so, to implement the same fix on the additional tests that failed (some when I tested it locally, and one when I committed it), so that the PR would finally pass the tests.

> It is not quite that hard and tedious to do. The test fixes would require a new branch and PR for them to land yes. However, this PR would just need to revert the tests and then rebase on develop after that lands.

That sounds a lot easier. I didn't know what rebasing did, so I wasn't aware of it as a possibility. I probably could have avoided merging develop in in the first place by using rebase, yes? (There would still have been the additional failing tests, but that could have gone in an additional PR, as you said, followed by presumably more rebasing)

To be honest, I'm still not quite used to patches even *having* commit histories. The last time I really worked with version control, it was with SVN, and patches were basically just diff files (and it was years ago, too). It's a bit of a learning curve moving to git.

**Comment by andydotxyz** [comment]
> I know that you have talked about that before @andydotxyz. What is your take on it?

Each commit should have a separate purpose (i.e. a feature, a refactor or whitespace).
Each PR should have a scope. If bug fixes relate to the feature addition that is cool.
If bug fixes are unrelated to the feature being added then yes a separate PR is best.

**Review by andydotxyz — APPROVED** [review]
In this instance we were fighting bad tests and it's not a big deal for a one off :)

**Review by Jacalz — APPROVED** [review]
I agree. I just wanted to raise the question, not cause an argument :)

**Pull request merged**
