### PR TITLE
Feature/keyboard controllable main menu

### PR DESCRIPTION
**Pull request by toaster**
### Description:

This makes the main menu keyboard controllable. It is the first (and biggest) part of #1647.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
A quick question here... You have added `FocusNext` and `FocusPrevious to the `Canvas` API - but only used it internally to the drivers as far as I can see... could it not just be local to the glCanvas and mobileCanvas?

**Comment by Jacalz** [comment]
I think I might be able to answer that question @andydotxyz. I am one of the people that really want those methods. It is going to make changing focus a lot easier then the current way of keeping references to the things that want to be focused. It would clean up the code in Sparta that currently looks like this: https://github.com/Jacalz/sparta/blob/develop/internal/gui/widgets/entry_advanced.go.

**Comment by andydotxyz** [comment]
I think the right fix in your situation @Jacalz is that we implement "move on when enter pressed in form if single line", which is a separate issue.
I guess there are happy side-effects of exposing the methods here, but is that the reason that they were added? :)

**Comment by Jacalz** [comment]
> I think the right fix in your situation @Jacalz is that we implement "move on when enter pressed in form if single line", which is a separate issue.
> I guess there are happy side-effects of exposing the methods here, but is that the reason that they were added? :)
I am not talking about widgets inside of a form and neither am I talking about pressing enter. The on Enter code is only about executing a function. I am talking about pressing up or down arrow to move between widgets in a VBox. Adding this is a good addition in my opinion 🙂

**Comment by andydotxyz** [comment]
> I am talking about pressing up or down arrow to move between widgets in a VBox

Ah OK thanks, was hard to tell from just reading the code. As above I don't mean to say it isn't useful, but was asking if it is required for the PR...

**Comment by Jacalz** [comment]
> Ah OK thanks, was hard to tell from just reading the code.
Hehe, I can see that. That code is in serious need for a rewrite 🙃

**Review by andydotxyz — CHANGES_REQUESTED** [review]
It looks like `FocusNext` and `FocusPrevious` on the `Canvas` API are not required for this change.

**Comment by Jacalz** [comment]
> It looks like `FocusNext` and `FocusPrevious` on the `Canvas` API are not required for this change.

Can we perhaps have that moved out to a separate PR then? I still think it is a very good and useful addition 🙂

**Comment by toaster** [comment]
> > It looks like `FocusNext` and `FocusPrevious` on the `Canvas` API are not required for this change.
> 
> Can we perhaps have that moved out to a separate PR then? I still think it is a very good and useful addition 🙂

I will do that.

**Review by Jacalz — COMMENTED** [review]
Just a heads up. Looks like tests are failing importunately.

**Comment by andydotxyz** [comment]
I got a crash if I pressed Enter on a folder:

```

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Can you look into the crash I put in the channel? (selecting a folder menu).

Also in the original #1515 it was added that `Esc` should close the menu - is that in scope for this change as well?

**Review by andydotxyz — APPROVED** [review]
This is great, thanks

**Pull request merged**
