### PR TITLE
fix glfw window test

### PR DESCRIPTION
**Pull request by toaster**
### Description:

Two GLFW tests failed (locally on my Mac):
1. The window hover test did not work since some padding changed in the past and the mouse movement did not fit any more.
2. The window close interception test did not take into account the asynchronous nature of the `Close()` call.

### Checklist:
- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
I am getting a few test failures on Linux. Notably, the `TestWindow_HandleOutsideHoverableObject` is still failing for me:
[glfw-test-failures.txt](https://github.com/fyne-io/fyne/files/11294496/glfw-test-failures.txt)

**Review by andydotxyz — APPROVED** [review]
Excellent tests far more readable thanks!

**Comment by toaster** [comment]
> I am getting a few test failures on Linux. Notably, the `TestWindow_HandleOutsideHoverableObject` is still failing for me: [glfw-test-failures.txt](https://github.com/fyne-io/fyne/files/11294496/glfw-test-failures.txt)

@Jacalz Yes, these are known. I try to get the GLFW tests non-failing step by step. Make them non-failing on Linux is actually my highest prio because the Linux tests actually run on CI without crashes while the MacOS tests aren’t.

**Comment by Jacalz** [comment]
@toaster Absolutely, I just meant that you had specifically modified `TestWindow_HandleOutsideHoverableObject` to work on macOS in this PR but it is failing on Linux with these changes.

**Comment by toaster** [comment]
> @toaster Absolutely, I just meant that you had specifically modified `TestWindow_HandleOutsideHoverableObject` to work on macOS in this PR but it is failing on Linux with these changes.

Yes, but these failures are not new. If you compare the test run with the base of this PR, you’ll notice that all the failures are there plus two for the window hoverable test complaining about a `nil` where it should not.

**Pull request merged**
