### PR TITLE
Reduce allocations in GridWrap on scroll updates

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Similar to #4398 but for the GridWrap widget.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
The tests don't seem to run. That seems strange

**Comment by Jacalz** [comment]
Yeah maybe

**Comment by dweymouth** [comment]
The tests ran after another commit that was just a typo fix

**Comment by andydotxyz** [comment]
Thanks for looking into this - it certainly sounds desirable.
Are there any metrics / indicative benchmark we can check it against?

**Comment by dweymouth** [comment]
I didn't run profiling myself but doing a memory profile with pprof and scrolling around a bunch in the GridWrap in Fyne Demo should show fewer overall allocations than the same thing without this change

**Review by andydotxyz — APPROVED** [review]
Thanks for this

**Pull request merged**
