### PR TITLE
Convert more widgets

### PR DESCRIPTION
**Pull request by andydotxyz**
TODO:

- [x] Accordion
- [x] Activity
- [x] Card
- [x] Menus 
- [x] Toolbar

This just leaves the collections and containers for another PR

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by dweymouth — COMMENTED** [review]
Is this work going to be obsolete when we move to the approach of theming the icons in the renderer so that custom widgets can have theme overrides "just work"?

**Comment by andydotxyz** [comment]
> Is this work going to be obsolete when we move to the approach of theming the icons in the renderer so that custom widgets can have theme overrides "just work"?

No. Colouring icons will just work, but widgets must all look up the current theme for their widget - the globalm APIs we used before have no way of knowing what context the incoming request for icon/colour etc is referring to.

**Comment by andydotxyz** [comment]
This qualifies for auto-acceptance as its been a week with no change requests, but it seems a bit large to do so.
Any thoughts @Jacalz @dweymouth ?

**Review by dweymouth — APPROVED** [review]
Seems fine to me

**Pull request merged**
