### PR TITLE
Resets cursor position for empty text

### LINKED ISSUE #212: Clearing a text input and typing in it again causes a panic
```
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
fyne.io/fyne/widget.(*textProvider).insertAt(0xc4201cc2a0, 0x1, 0xc420af9a64, 0x1, 0x1)
	/Users/pbarnum/go/src/fyne.io/fyne/widget/text.go:147 +0x26f
fyne.io/fyne/widget.(*Entry).TypedRune(0xc4201b6e10, 0xc400000073)
	/Users/pbarnum/go/src/fyne.io/fyne/widget/entry.go:232 +0x8d
fyne.io/fyne/driver/gl.(*window).charModInput(0xc420148200, 0xc420148180, 0x73, 0x0)
	/Users/pbarnum/go/src/fyne.io/fyne/driver/gl/window.go:807 +0x7c
fyne.io/fyne/driver/gl.(*window).(fyne.io/fyne/driver/gl.charModInput)-fm(0xc420148180, 0x73, 0x0)
	/Users/pbarnum/go/src/fyne.io/fyne/driver/gl/window.go:867 +0x46
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.goCharModsCB(0x6d00770, 0x73)
	/Users/pbarnum/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/input.go:300 +0x5d
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_471f26bf8a94_goCharModsCB(0x6d00770, 0x73)
	_cgo_gotypes.go:2101 +0x3b
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1111 +0x41
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.PollEvents()
	/Users/pbarnum/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:777 +0x20
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc4201211a0)
	/Users/pbarnum/go/src/fyne.io/fyne/driver/gl/loop.go:77 +0x4d2
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc4201211a0)
	/Users/pbarnum/go/src/fyne.io/fyne/driver/gl/driver.go:58 +0x43
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc420148200)
	/Users/pbarnum/go/src/fyne.io/fyne/driver/gl/window.go:303 +0x57
main.main()
```

To reproduce:
1. Create a text input and button. On button click, run `input.SetText("")`
2. When app is running, type some characters into the text input
3. Click the button, this should set the input value to an empty string
4. Click in the text input to bring it into focus, you should see the cursor is not at the starting position, but slightly to the right of it.
5. Type a character
6. The app panics with the above call stack

Note: You can prevent the app from crashing, before step 5, hit the right/left arrow key and it should correct itself.

### PR DESCRIPTION
**Pull request by pbarnum**
Resolves #212

### CODE REVIEW

**Comment by pbarnum** [comment]
```
### Before
[2019-04-07 01:32:33] ~/Personal/fyne <212-text_out_of_bounds> $ go test ./...
ok  	_/Users/pbarnum/Personal/fyne	(cached)
ok  	_/Users/pbarnum/Personal/fyne/app	(cached)
ok  	_/Users/pbarnum/Personal/fyne/canvas	(cached)
ok  	_/Users/pbarnum/Personal/fyne/cmd/fyne	(cached)
?   	_/Users/pbarnum/Personal/fyne/cmd/fyne_demo	[no test files]
?   	_/Users/pbarnum/Personal/fyne/cmd/hello	[no test files]
?   	_/Users/pbarnum/Personal/fyne/dialog	[no test files]
ok  	_/Users/pbarnum/Personal/fyne/driver/desktop	(cached)
ok  	_/Users/pbarnum/Personal/fyne/driver/gl	(cached)
ok  	_/Users/pbarnum/Personal/fyne/layout	(cached)
?   	_/Users/pbarnum/Personal/fyne/test	[no test files]
ok  	_/Users/pbarnum/Personal/fyne/theme	(cached)
--- FAIL: TestEntry_SetTextEmptyString (0.00s)
	entry_test.go:77:
			Error Trace:	entry_test.go:77
			Error:      	Not equal:
			            	expected: 0
			            	actual  : 4
			Test:       	TestEntry_SetTextEmptyString
	entry_test.go:88:
			Error Trace:	entry_test.go:88
			Error:      	Not equal:
			            	expected: 0
			            	actual  : 4
			Test:       	TestEntry_SetTextEmptyString
	entry_test.go:89:
			Error Trace:	entry_test.go:89
			Error:      	Not equal:
			            	expected: 0
			            	actual  : 1
			Test:       	TestEntry_SetTextEmptyString
FAIL
FAIL	_/Users/pbarnum/Personal/fyne/widget	1.233s

### After
[2019-04-07 01:34:58] ~/Personal/fyne <212-text_out_of_bounds> $ go test ./...
ok  	_/Users/pbarnum/Personal/fyne	(cached)
ok  	_/Users/pbarnum/Personal/fyne/app	(cached)
ok  	_/Users/pbarnum/Personal/fyne/canvas	(cached)
ok  	_/Users/pbarnum/Personal/fyne/cmd/fyne	(cached)
?   	_/Users/pbarnum/Personal/fyne/cmd/fyne_demo	[no test files]
?   	_/Users/pbarnum/Personal/fyne/cmd/hello	[no test files]
?   	_/Users/pbarnum/Personal/fyne/dialog	[no test files]
ok  	_/Users/pbarnum/Personal/fyne/driver/desktop	(cached)
ok  	_/Users/pbarnum/Personal/fyne/driver/gl	(cached)
ok  	_/Users/pbarnum/Personal/fyne/layout	(cached)
?   	_/Users/pbarnum/Personal/fyne/test	[no test files]
ok  	_/Users/pbarnum/Personal/fyne/theme	(cached)
ok  	_/Users/pbarnum/Personal/fyne/widget	1.351s
```

**Comment by pbarnum** [comment]
There was something I noticed when writing this test. When I used the `KeyEnd` initially trying to get the cursor to the end of the line (not knowing it was already there), my test failed. I read the code for this key press and found that it actually does this
```
e.CursorColumn = provider.len()
```
Shouldn't it instead be this?
```
e.CursorColumn = provider.rowLength(e.CursorRow)
```

**Comment by andydotxyz** [comment]
Yes, you are quire right, thanks for noticing. I think we missed a few multiline corner cases in the textProvider refactoring

**Comment by pbarnum** [comment]
Sounds good, I'll make the associated issue.

**Comment by paulhovey** [comment]
I think this PR should be based against develop, and will need to add the mutex around modifying e.CursorRow and e.CursorColumn similar to #196 .

**Comment by pbarnum** [comment]
Thanks for the heads up!

**Comment by pbarnum** [comment]
FYI: `master` and `develop` are out of sync.

**Pull request merged**
