### PR TITLE
fix calculating executable name in package command for apps using go modules

### PR DESCRIPTION
**Pull request by pymq**
### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by pymq** [comment]
Good idea, done

**Comment by andydotxyz** [comment]
The code and tests look ready, thanks.
However the files removed from the vendor file don’t seem right, do you know why this has happened?

**Comment by pymq** [comment]
I don't know, really. I just used `fyne vendor` to pull new dependencies. Maybe because of `+build ignore` tag in those files?
Reverted changes.

**Comment by andydotxyz** [comment]
Many thanks. Can you confirm what platform you were running the vendor command on? We probably need to look into it further if our tooling is causing issues

**Comment by pymq** [comment]
I am using Ubuntu Linux, Go 1.13.8, project is located outside of GOPATH

**Comment by andydotxyz** [comment]
Thanks, I see the same on an Arch Linux box. Will look into this more and see what's going on.

**Comment by andydotxyz** [comment]
It seems like these files are needed by macOS, I can't find a way to make the vendor command include them, I'll open another issue so we can track this.

**Pull request merged**
