### PR TITLE
Ci cleanup

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

Golint has been deprecated and frozen. Go vet and staticcheck should have us covered.
After some fixes upstream in gocyclo, we can also stop removing the vendor folder now.
The workflow has also been renamed to not be called "checks".

Added in the stricter security permissions and renamed the license workflow to not be called "checks".

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
> After some fixes upstream in gocyclo, we can also stop removing the vendor folder now.

Not sure about this... As is demonstrated in the failure currently not all libraries that we vendor will share our sense of how strictly things should be enforced... any changes will be reversed next time someone "mod vendors" so I think it must still be ignored.

In the future we can strip out vendor anyhow (once go modules are standard for all versions we support).

**Comment by Jacalz** [comment]
> any changes will be reversed next time someone "mod vendors" so I think it must still be ignored.

Sorry, I'm not sure I follow here. I haven't modified anything inside the vendor folder. The linting tools now all ignore the vendor folder (gocyclo was the only one that wasn't doing it before). Keeping the vendor folder in our case now is just the same as when we deleted it before. None of our tools are checking it either way.

**Comment by andydotxyz** [comment]
> Sorry, I'm not sure I follow here. I haven't modified anything inside the vendor folder.

I did not mean to suggest you had modified the content, but that the "static_analysis" test failure was reporting incorrectly formatted code. This is where the problem is because we cannot modify the vendor folder to fit. This used to be ignored so I assumed the issue related to your description including "we can also stop removing the vendor folder now."...

**Comment by Jacalz** [comment]
> 

Ah, I see. I had missed that fact that goimports failed. I see what you mean now. Because I didn't use it in the last PR, I missed that it looked at the vendor folder.

**Comment by Jacalz** [comment]
This should be looking better now :)

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
