### PR TITLE
Add SetValue() to slider

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:
This adds a SetValue() function to be consistent with other widgets.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [x] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is skipping the range clamping which seems risky. And you’re setting the value after calling OnChanged which is not what others to iirc...

**Comment by Jacalz** [comment]
Seems that radio doesn’t, but I can get that changed if you would like. Should be fixed now :)

**Comment by andydotxyz** [comment]
> Seems that radio doesn’t

The other trigger within Slider might have been a better comparison ;)

But yes it looks like radio might be wrong - the "OnXxx" callbacks signal that something has already happened.

**Review by andydotxyz — APPROVED** [review]

**Comment by Jacalz** [comment]
I was the one to add support for that to Radio, so I can claim that as my fault ;)
Will get that fixed :)

**Pull request merged**
