### PR TITLE
bugfix #2013: addAttributes return parameter is always nil, and not used

### LINKED ISSUE #2013: function never returns a value
### Describe the bug:

Function `addAttributes` in `cmd/fyne/internal/mobile/binres/binres.go` always returns nil, never the promised attributes xml.

### PR DESCRIPTION
**Pull request by nealmcc**
### Description:
Removed unused return values, to avoid ambiguity.  These functions alter their input parameters.

Fixes #2013 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks for looking at this. I think that a lot of the test code could be removed if you use the stretchr/testify package that we use elsewhere for assert etc

**Comment by Jacalz** [comment]
Can you please use PR titles what they are fixing, instead of what issue they fix? Makes it much easier to glance at an issue an know what it does. Keeping track of a lot of numbers is hard :)

**Review by andydotxyz — APPROVED** [review]
Great thanks :)

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Oops, looks like there is another check error:
Error: cmd/fyne/internal/mobile/binres/binres_test.go:60:6: func compareBytes is unused (U1000)

**Comment by nealmcc** [comment]
Sorry about the spam - I meant to wait and push once I'd done this refactoring

**Comment by nealmcc** [comment]
> Oops, looks like there is another check error:
> Error: cmd/fyne/internal/mobile/binres/binres_test.go:60:6: func compareBytes is unused (U1000)

I've removed this helper function since the testify/require library achieves the same thing

**Comment by nealmcc** [comment]
I realised after I pushed the refactoring that you'd already nearly approved the PR without it, and the additional refactoring is likely more time consuming to review than  you would like.

My intent was to clarify (for myself as much as anything) the purpose of each function (particularly the return values vs modified parameters). I don't believe I've changed the behaviour at all and the tests that I added from upstream still pass.  However, if you'd prefer to simplify the PR, I'm happy revert 8461c79 and  7ab8f58

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
