### PR TITLE
internal/driver/mobile: tidy unused code

### PR DESCRIPTION
**Pull request by changkun**
### Description:
This is the 3rd pull request of a series of pull requests intended to remove the fyne-io/mobile dependency, as per discussed in #2428.

This change does a few simplifications of the internal/driver/mobile package, containing remove unused packages, remove used functions, etc (only 42 GL functions are used for fyne, it might be a good motivation for fyne to write a custom clean gl package, instead of depending on a go-gl package where a gl.go file is in 2MB size). 

Updates #843

@andydotxyz @Jacalz 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by changkun** [comment]
@andydotxyz @Jacalz Now rebased on top of the latest develop branch. The diff should be nice for the review.

**Comment by changkun** [comment]
Hmm. Interesting, what causes the failure? It was all passed.

**Comment by changkun** [comment]
Looks like because of the change from one of theses

https://github.com/fyne-io/fyne/commit/1dcae84cfd4a13dd4806a15247d69aab851acebf
https://github.com/fyne-io/fyne/commit/d54867fa03560f55b715c0cccabbc42e7f578f94
https://github.com/fyne-io/fyne/commit/ba8b723a6d6be04e71f010faddefc6f4ddd999d3

**Comment by andydotxyz** [comment]
> Hmm. Interesting, what causes the failure? It was all passed.

I missed something in Windows test code that somehow got into develop - it's all working smoothly again, sorry

**Comment by andydotxyz** [comment]
Sorry for the delay, let's pick this up after v2.1 (just a few more days).
We are so close that I don't want to make large changes, and this can be added any time as there are no API or behaviour changes.

**Comment by Jacalz** [comment]
I don't currently have any crops compiling setups for mobile devices, so I'll just ask out of curiously. Does this make the mobile binaries any smaller? If so, how much? 🙂

**Comment by changkun** [comment]
> I don't currently have any cross compiling setups for mobile devices, so I'll just ask out of curiously. Does this make the mobile binaries any smaller? If so, how much? 🙂

Yes, a little bit. We still have to rely on cgo anyway (Obj-C and Java). #911 was discussing Windows which will have significant improvements on the binary size.

But still, this reduces the binary size a bit:

iOS:

- before 28.4MB (develop)
- after 28.3MB (this)

Android:

- before 96.8MB (develop)
- after 96.6MB (this)

**Comment by Jacalz** [comment]
@changkun Thanks for the numbers. You have successfully cured my curiosity for now. Thanks for working on this :)

**Comment by changkun** [comment]
@andydotxyz ping

**Comment by andydotxyz** [comment]
Yeah sorry - still catching up on backlog, this is on my list for tomorrow!

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
