### PR TITLE
Switch to outline icons, fixes #1229

### LINKED ISSUE #1229: Move to outline icons
It seems that they may create a lighter feeling GUI - we could swap out the fill ones for line variants.
Not a big deal API level, but probably relates to material design review.

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This PR starts work on switching icons to being outlines instead. There was a few icons that I couldn't find outlines for (mostly file icons and color). Would appreciate if people had a look at this and to say what they think about the style. I don't know really what to say about the folder icons, but for the most part it looks really good, I'd say :slightly_smiling_face:  

Fixes #1229

image
image
image

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
I'm pleasantly surprised by most of this :).
The file icons were created manually, derived from the file template. Are those the ones you could not find?

If we're progressing with this then a checklist of what is missing would be good.

**Comment by Jacalz** [comment]
> I'm pleasantly surprised by most of this :).
> The file icons were created manually, derived from the file template. Are those the ones you could not find?
> 
> If we're progressing with this then a checklist of what is missing would be good.

Yes exactly. I couldn't find those icons (not surprising then) and there were just a few others. Will see about getting a checklist done as soon as I have the time to do so :)

**Comment by Jacalz** [comment]
Icons that are not currently updated:
- [ ] color-chromatic (does not seem to even exist on material.io)
- [ ] file-application
- [ ] file-audio
- [ ] file-image
- [ ] file-text
- [ ] file-video
- [ ] mail-reply (downloading outline icon from material.io downloads filled for some reason)
- [ ] storage (does not exist in outlined form on material.io)

I would propose that we switch the storage icon from storage to sd_storage:
image

**Comment by stuartmscott** [comment]
The original storage icon wasn't completely intuitive, but switching to sd_storage isn't much better. For one tying storage to a particular medium isn't futureproof - eg. floppy disk as save icon. For another the sd_storage icon looks far too similar to a file icon.

**Comment by Jacalz** [comment]
We are pushing this for a later release. Outline icons are not ready yet here neither upstream with Material where a lot of them are missing.

**Pull request closed without merging**
