### PR TITLE
ttc fonts supported

### LINKED ISSUE #4053: Support for font collections in theme / user font
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want to use .ttc to load my fonts

### Is it possible to construct a solution with the existing API?

I would have to load, parse and extract a font from the collection then pass it into fyne as a re-packaged font file (not sure if that is even possible).

### Describe the solution you'd like to see.

The ability to load .ttc and .otc files.
Ideally it would not have to parse and load every font in the collection - but somehow make them available for selecting when needed.

### PR DESCRIPTION
**Pull request by bon-ami**
theme.CheckFontParsable added
font.ParseTTC replaces font.ParseTTF. The first font of the collection is taken.

 

### Description:

Fixes #4053,#3799,#2761

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: .

### CODE REVIEW

**Comment by andydotxyz** [comment]
You do realise that this will parse the entire font collection and then return only the first font? Could be quite a bad performance drop.

Also, why all the nil checks added? Having font rendering need to worry about nil seems bad - because we cannot possible render a string if the font is nil. Unless I misunderstood the change this seems like a bad thing.

**Comment by dweymouth** [comment]
Yes, this certainly isn't really solving TTC support. TTC support means loading all the fonts in the collection when needed to display specific glyphs. The point of TTC is usually achieving larger glyph coverage than any single TTF can support on its own

**Comment by bon-ami** [comment]
@andydotxyz , @dweymouth , 
1. this is not a final solution. I cannot use current API to fully support ttc. Since I remember seeing the font mechanism/lib is to be switched, I only want to make ttc partially supported.
2. I want to protect the whole app being crashed by the rendering issue, by not showing the texts. Because I am using a customized theme with fonts, if the font is invalid, I have no API to check that and it will crash my whole app.
3. So I also added an API to check the validity of a font resource.

as I commented in https://github.com/fyne-io/fyne/issues/4053#issuecomment-2418643857,
I think we should provide a temporary change according to https://github.com/fyne-io/fyne/issues/2761#issuecomment-2041367042
as a quick, though not full, support to https://github.com/fyne-io/fyne/issues/3799

**Comment by andydotxyz** [comment]
Thanks for this, some thoughts:

> 1. this is not a final solution. I cannot use current API to fully support ttc. Since I remember seeing the font mechanism/lib is to be switched, I only want to make ttc partially supported.

The font lib was switched out a couple of releases ago, there is no future plans to change font loading.
If it is a temporary solution it should certainly not add new public APIs - we have to support them forever.

> 2. I want to protect the whole app being crashed by the rendering issue, by not showing the texts. Because I am using a customized theme with fonts, if the font is invalid, I have no API to check that and it will crash my whole app.

If there is a crash we should fix that directly - no Fyne API call or render should ever panic.
For the case where you are worried a font is not supported it is possible to query the go-text/typesetting loader directly in your app.

> 3. So I also added an API to check the validity of a font resource.

As noted above APIs should not be part of a temporary fix but have clear utility and purpose. I get the feeling that this has been added to avoid a crash - which is not how we do things as the panic itself should be resolved.

**Comment by andydotxyz** [comment]
I see that updates were merged but not addressing the comments left, is this PR still progressing towards something for v2.6.0?

**Comment by bon-ami** [comment]
> I see that updates were merged but not addressing the comments left, is this PR still progressing towards something for v2.6.0?

I merged on my branch, not here. It is a incomplete solution just for myself.

**Comment by andydotxyz** [comment]
> > I see that updates were merged but not addressing the comments left, is this PR still progressing towards something for v2.6.0?
> 
> I merged on my branch, not here. It is a incomplete solution just for myself.

OK thanks for the clarity. Please do open a PR on this project if you have a solution that would be something to be shared with all users.

**Pull request closed without merging**
