### PR TITLE
WIP - Full material design 

### LINKED ISSUE #958: Subjective comment on default colour choices in provided Fyne themes
After reading the docs on colour selection :
https://www.material.io/design/color/dark-theme.html#ui-application

.. I think the primary blue that we are running with is probably a little oversaturated.

Experimenting with plugging in the suggested "200" colors, the Fyne demo looks a bit less like a Fyne app, and more like other material themed apps.

### PR DESCRIPTION
**Pull request by steveoc64**
### Description:
WIP - preview of upgrading the internals to support the full Material Design color palette.

Support for extending the current theme by applying JSON patches on top - sort of like CSS, but not CSS.

Can copy generated themes directly from here, and apply the generated JSON to load the theme. 
  https://cimdalli.github.io/mui-theme-generator/

Remarkably, the existing API isnt touched at all, and it doesnt grow the code base a great deal.

Needs a bit more polish  - but worthy as an RFC / experiment

Fixes #958 #211 

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by steveoc64** [comment]
Found some nasty bugs in the tabContainer as well - from a recent patch in the last month or so

**Comment by andydotxyz** [comment]
Looks like tests are broken - I'd encourage running them before pushing any code even if it's WiP. They are there to remind us not to break API or functionality and might impact the viability of a proposed change.

**Comment by andydotxyz** [comment]
As we progress the implementation of Theme2 for 2.0 we should check back here to make sure we don't miss anything.

**Comment by andydotxyz** [comment]
Closing due to age and the number of conflicts against the new theme work.
Let's check back here as we roll out the updated theme to make sure we keep the work in mind.

**Pull request closed without merging**
