### PR TITLE
fix: fyne package targeting windows

### PR DESCRIPTION
**Pull request by garrettcorn**
### Description:
fyne package is grabbing GOARCH from runtime.GOARCH when building for windows causing issues when the target architecture doesn't match local architecture.

Fixes #(issue)
Change fyne package to grab GOARCH from the environment variable GOARCH and fallback to runtime.GOARCH if GOARCH is not set.

### Checklist:

- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
Would you mind changing the target branch to `develop` and rebasing on that?

Otherwise, looks great to me. You managed to fix the issue in a really clean way 👍

**Review by Jacalz — CHANGES_REQUESTED** [review]
Sorry, but it looks like the rebase introduced a lot of changes that shouldn't be part of the PR.

**Comment by garrettcorn** [comment]
That it did. Let me redo this properly from the devops branch and resubmit.

**Comment by garrettcorn** [comment]
new pull request here: https://github.com/fyne-io/fyne/pull/1319

**Pull request closed without merging**
