### PR TITLE
Second attempt at #529 but without svg changes

### PR DESCRIPTION
**Pull request by Jacalz**
**Description**

A revised second attempt but with only raster images optimized and
it is targeted against develop branch this time. That means that more
images have been optimized.

**Checklist**

- [x] Lint and formatter run with no errors
- [x] Tests all pass

### CODE REVIEW

**Comment by Jacalz** [comment]
Demo app works fine, however I would like to point out that the logo pretty bad on light theme :wink: 
image

**Comment by Jacalz** [comment]
Wait with merging this. I have small change that I would like to do.

**Comment by andydotxyz** [comment]
Thanks for this. You are quite right about the logo against the light theme - this will be fixed but the final assets did not arrive in time for our conference so i dropped in this file just for demo purposes. I now have the replacement files so I’ll replace it shortly :)

**Comment by Jacalz** [comment]
Never mind not merging. My planned changes did not turn out good :slightly_smiling_face:

**Pull request merged**
