### PR TITLE
Live refresh

### LINKED ISSUE #531: canvas.Image and canvas.Raster textures are not refreshed while actively resizing window.
**Describe the bug**
canvas.Image and canvas.Raster objects that are resized when the window is being resized do not have their underlying textures updated while the window is actively being resized (i.e. border hotspot is being dragged). When hotspot is released to "finish" the resize, only then is the texture actually updated. During resize, if we go from a small size to a larger size, there is noticeable blurriness as the smaller resolution image is scaled up to fill the larger area (this looks very much to me like it is OpenGL doing the scaling, as the visual quality reminds me of old 3D games with low resolution textures). I first noticed this in my own app, in which I was experimenting with using a canvas.Raster object created with NewRaster(generate func(w, h int) image.Image) to supply the image on demand using my own function (neat idea, by the way). I could see while debugging that canvas.Refresh() was being called for my canvas.Raster object every time it changed size, but canvas.Refresh() would not trigger my generate function to be called until after the window border was released.

I then checked to see if the demo exhibited similar behavior, and it did. I'm making an assumption that it uses canvas.Image to display SVG images.

**To Reproduce**

1. Build and run Fyne demo in a desktop environment (seen on Windows 10).
2. Go to tab with icon selector / display.
3. Start with a small window and drag border to increase window size.
4. Observe that icon appears blurry until mouse is released to finish resize.

**Screenshots**
Can add later if necessary.

**Device (please complete the following information):**
I am opening this issue at a time when I don't have easy access to my development system (sorry). I can update with more information in a week or so if reproduction is a problem.
 - OS - Windows 10, kept up to date, but don't have access to look at build number currently.
 - Go version - Unsure at present, sorry. It could be 6-12 months old.
 - Fyne version - Whatever was pulled with "go get fyne.io/fyne" as of mid to late last week.

### PR DESCRIPTION
**Pull request by windexlight**
**Description**

Please see #560 for discussion.

Fixes #531

**Checklist**

- [ ] Tests included
- [x] Lint and formatter run with no errors
- [ ] Tests all pass

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is a well formed PR and it could be accepted, thanks for doing this.
I'm not too sure, however, if the performance impact on resize is acceptable.
Perhaps we can get a few people's thoughts on this?

**Comment by windexlight** [comment]
Performance impact on resize is of course going to be quite dependent on what elements are present in the window, and how they are drawn. Only elements whose size changes with the window would be updated here, where they were not before. Using the Fyne demo as an example, the only elements that should really be affected are the icon preview and grid background on the Graphics tab. If both elements are live resized, it does start to get noticeably sluggish on my machine when the window is near full screen size (1080 resolution, 4K would be worse of course), and still more if the window is stretched across two monitors. It’s a judgment call what is “too sluggish”. My anecdotal impression is also that the grid background (which I believe is generated in a loop with a callback for every pixel, if I recall correctly) contributes more to the total refresh time than the icon itself does. It may be a separate topic to improve how that grid is drawn to improve performance in that specific case.

Beyond that, questions about performance impact loop back to the idea of implementing selective refresh, so the app developer can make their own choice about performance vs live resize.

Related to the question of performance is the introduction of resizing artifacts that start showing up with slower refresh times on Windows. This is a frustrating problem to tackle, as discussed in pretty good detail here: https://stackoverflow.com/questions/53000291/how-to-smooth-ugly-jitter-flicker-jumping-when-resizing-windows-especially-drag

**Comment by andydotxyz** [comment]
Let's pick this up as part of 1.3 and try to get the balance.
One reason not to go with the "should I refresh on resize" API is that it's not guaranteed - many Linux systems refresh "live" and so that API would be ignored for them...

**Comment by andydotxyz** [comment]
As we are now working on 1.3 in develop branch should we consider landing this and working to optimise before the release in a few months?

**Comment by andydotxyz** [comment]
Ok, landed. Let’s look at the performance impact and smooth the hotspots before 1.3 release

**Comment by andydotxyz** [comment]
You should check out #966 as it backs out some of this code because our render loop actually stays running on resize. seems almost silky smooth in compariosn and I'm much happer about speed :)

**Comment by windexlight** [comment]
My head hasn’t really been in the Fyne space for a while, but I looked through the changes in #966, and think I agree with the overall direction. It seems reasonable that if the GLFW call to poll for input events blocks the thread, then decoupling drawing from the main event loop, and moving it to another thread is a good structural change. If it has the side effect of improving performance, then great. My goal with this original PR was just to change as little as possible within the framework at the time, so not surprising there is a better solution.

**Pull request merged**
