### PR TITLE
WiP: Input Dialog

### PR DESCRIPTION
**Pull request by charlesdaniels**
### Description:

This PR implements an `InputDialog` which can be used to prompt the user for input. This can be simpler than using a custom widget, if you just need the user to enter a simple value.

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [X] Public APIs match existing style.

### CODE REVIEW

**Comment by charlesdaniels** [comment]
ezgif-1-ae7e22e7dc21

Video of the new dialog type in action.

**Comment by charlesdaniels** [comment]
RFC from @andydotxyz or anyone else who would care to chime in.

* The most elegant way I could think of to actually get the text the user entered into a callback was via the `onConfirm()` cb I just added, however and the validator are both `nil`-able to minimize friction.
* The dialog callback is set to a no-op, maybe I should add a way to allow setting that too? This might be a good idea, since right now there is no way to detect if the user cancelled, other than that the `onConfirm` callback doesn't fire.

Once we're happy with how this works, I will add some test cases and remove the WiP.

**Comment by andydotxyz** [comment]
Which callback is a no-op? Do you mean OnClosed?
The dialogs on the whole do need a bit of a design cleanup but until the 2.0 work we need to be consistent with how it currently works.

**Comment by charlesdaniels** [comment]
I meant that the callback that is part of the base dialog type is currently a no-op.

**Comment by andydotxyz** [comment]
Ah, I see - well that's an internal detail so it's not a worry if the exposed API is consistent with the others?
With them they (currently) call with a zero value on cancel.
That's the current design - I think in 2.0 we may need to move to the OnCancel vs OnConfirm(?) rather than a single generic function (later this year).

**Pull request closed without merging**
