### PR TITLE
New theme step 2 - thinner input and entry to match 

### PR DESCRIPTION
**Pull request by andydotxyz**
Move check and entry to be thinner with a primary colour thrown in to match designs.
Entry becomes boxed in not underlined.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

thinwidgets

### CODE REVIEW

**Comment by andydotxyz** [comment]
Latest update to colours to match design:
Screenshot 2022-08-10 at 17 51 36

**Comment by Jacalz** [comment]
Are the buttons supposed to be changed in the near future? They look rather big to me.

**Comment by andydotxyz** [comment]
Yes, padding is next, need to split inner and outer pad

**Review by Jacalz — APPROVED** [review]
Looks good to me :)

**Pull request merged**
