### PR TITLE
Update workflow deps and try to fix Windows compile issues

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This makes sure we use the latest checkout and setup-go-faster actions as well as adds a temporary workaround for compile issues on Go 1.19 and lower.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]
Thanks, great to have tests passing across the board again

**Comment by Jacalz** [comment]
The Windows test has a new name now so you might have to remove/change the requirement and then merge yourself, just so you know :)

**Comment by andydotxyz** [comment]
All green :sunglasses:

**Comment by Jacalz** [comment]
Yay 🎉

**Comment by andydotxyz** [comment]
Thanks for working on this, I know it's been a tough journey and there is more to do, but this is a big step.

**Pull request merged**
