### PR TITLE
Headers always sticky

### PR DESCRIPTION
**Pull request by andydotxyz**
As discussed on call this is neater and makes more sense.
Replaces the related PR #3827

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Bluebugs** [comment]
I managed to get a crash with this PR:
```
fatal error: concurrent map read and map write

goroutine 54 [running, locked to thread]:
fyne.io/fyne/v2/widget.(*tableCellsRenderer).MinSize(0xc0011f0140)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:935 +0x1b7
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0xc000146070?)
	/home/cedric/go/src/fyne.io/fyne/widget/widget.go:90 +0x2e
fyne.io/fyne/v2/internal/widget.(*scrollContainerRenderer).Layout(0xc0017c4de0, {0x443ee19a, 0x43d51800})
	/home/cedric/go/src/fyne.io/fyne/internal/widget/scroller.go:276 +0x48
fyne.io/fyne/v2/internal/driver/common.updateLayout({0xdabb60?, 0xc000146070})
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/canvas.go:535 +0xd4
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0xc0000c10e0)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/canvas.go:111 +0x18d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:199 +0x35
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003d9180?, 0xc0024ede30)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:907 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0020183a0?, 0x1?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:198 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc0024edf90?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:106 +0x1ac
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:254 +0x1d4
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:230 +0xea
```

Additionally the divider do not show all the time, but it isn't related to the scale factor which was my first guess. Instead it seems to be the case depending on which column/row is being displayed. Not sure what is the pattern.

**Comment by Bluebugs** [comment]
When the dividers do not shows:
Screenshot_20230417_151412

**Comment by andydotxyz** [comment]
> fatal error: concurrent map read and map write

the issue seems to be on the other access as this one is protected by locks.
Can you print the full stack so we can see what else is calling into `t.columnWidths`?

**Comment by andydotxyz** [comment]
Haha fantastic - there were no images needing changed after all - that does make more sense.
All green 😎

**Comment by Bluebugs** [comment]
```
fatal error: concurrent map read and map write

goroutine 54 [running, locked to thread]:
fyne.io/fyne/v2/widget.(*tableCellsRenderer).MinSize(0xc0011f0140)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:935 +0x1b7
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0xc000146070?)
	/home/cedric/go/src/fyne.io/fyne/widget/widget.go:90 +0x2e
fyne.io/fyne/v2/internal/widget.(*scrollContainerRenderer).Layout(0xc0017c4de0, {0x443ee19a, 0x43d51800})
	/home/cedric/go/src/fyne.io/fyne/internal/widget/scroller.go:276 +0x48
fyne.io/fyne/v2/internal/driver/common.updateLayout({0xdabb60?, 0xc000146070})
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/canvas.go:535 +0xd4
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0xc0000c10e0)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/canvas.go:111 +0x18d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:199 +0x35
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003d9180?, 0xc0024ede30)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:907 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0020183a0?, 0x1?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:198 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc0024edf90?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:106 +0x1ac
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:254 +0x1d4
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:230 +0xea

goroutine 1 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003d9180)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:125 +0x19f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0003d9180)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:169 +0x75
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0004a63c0)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:230 +0x2c
main.main()
	/home/cedric/go/src/fyne.io/fyne/cmd/fyne_demo/main.go:68 +0x48c

goroutine 6 [chan receive]:
fyne.io/fyne/v2/test.NewApp.func1()
	/home/cedric/go/src/fyne.io/fyne/test/testapp.go:166 +0x45
created by fyne.io/fyne/v2/test.NewApp
	/home/cedric/go/src/fyne.io/fyne/test/testapp.go:164 +0x379

goroutine 7 [syscall]:
syscall.Syscall6(0x42d371?, 0xbea1a0?, 0x0?, 0xc00041ff20?, 0xc0000e6d00?, 0xc00040fc70?, 0x46eea7?)
	/usr/lib/go/src/syscall/syscall_linux.go:91 +0x36
golang.org/x/sys/unix.EpollWait(0x0?, {0xc00040fc04?, 0x2?, 0x50eb1c?}, 0x10?)
	/home/cedric/go/src/fyne.io/fyne/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:56 +0x58
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0000433e0)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x7d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000a0af0)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:206 +0x275
created by github.com/fsnotify/fsnotify.NewWatcher
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:60 +0x1c5

goroutine 8 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/home/cedric/go/src/fyne.io/fyne/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
	/home/cedric/go/src/fyne.io/fyne/app/settings_desktop.go:42 +0x111

goroutine 10 [chan receive]:
github.com/godbus/dbus/v5.newConn.func1()
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/conn.go:303 +0x32
created by github.com/godbus/dbus/v5.newConn
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/conn.go:302 +0x4f6

goroutine 18 [IO wait]:
internal/poll.runtime_pollWait(0x7fa5c90384c0, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0000ed700?, 0xc0005281d0?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc0000ed700, {0xc0005281d0, 0x10, 0x10}, {0xc000484020, 0x1000, 0x1000}, 0x70000c0000b7c38?)
	/usr/lib/go/src/internal/poll/fd_unix.go:304 +0x3aa
net.(*netFD).readMsg(0xc0000ed700, {0xc0005281d0?, 0x1265f98?, 0x1592540?}, {0xc000484020?, 0xc000528096?, 0xc000528090?}, 0xc00052808c?)
	/usr/lib/go/src/net/fd_posix.go:78 +0x37
net.(*UnixConn).readMsg(0xc0000141e8, {0xc0005281d0?, 0xc00052e110?, 0x43d74b?}, {0xc000484020?, 0x448227?, 0xb6f900?})
	/usr/lib/go/src/net/unixsock_posix.go:115 +0x4f
net.(*UnixConn).ReadMsgUnix(0xc0000141e8, {0xc0005281d0?, 0xc0000b7d50?, 0x45eec0?}, {0xc000484020?, 0x4348a8?, 0xc00052c288?})
	/usr/lib/go/src/net/unixsock.go:143 +0x3c
github.com/godbus/dbus/v5.(*oobReader).Read(0xc000484000, {0xc0005281d0?, 0xc0000b7de8?, 0x434c87?})
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/transport_unix.go:21 +0x45
io.ReadAtLeast({0xda16c0, 0xc000484000}, {0xc0005281d0, 0x10, 0x10}, 0x10)
	/usr/lib/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/lib/go/src/io/io.go:351
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0xc000013530)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/transport_unix.go:91 +0x11e
github.com/godbus/dbus/v5.(*Conn).inWorker(0xc000399d10)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/conn.go:390 +0x48
created by github.com/godbus/dbus/v5.(*Conn).Auth
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/auth.go:118 +0x99c

goroutine 50 [syscall]:
syscall.Syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/syscall/syscall_linux.go:91 +0x36
golang.org/x/sys/unix.EpollWait(0x0?, {0xc00050fc04?, 0x0?, 0x0?}, 0x0?)
	/home/cedric/go/src/fyne.io/fyne/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:56 +0x58
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000490060)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x7d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0004960a0)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:206 +0x275
created by github.com/fsnotify/fsnotify.NewWatcher
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:60 +0x1c5

goroutine 51 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/home/cedric/go/src/fyne.io/fyne/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
	/home/cedric/go/src/fyne.io/fyne/app/settings_desktop.go:42 +0x111

goroutine 52 [chan receive]:
fyne.io/fyne/v2/app.watchFreedekstopThemeChange()
	/home/cedric/go/src/fyne.io/fyne/app/app_xdg.go:193 +0x1ed
created by fyne.io/fyne/v2/app.watchTheme
	/home/cedric/go/src/fyne.io/fyne/app/app_xdg.go:165 +0x25

goroutine 55 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0xc00049c150)
	/home/cedric/go/src/fyne.io/fyne/internal/async/chan_func.go:45 +0xf1
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
	/home/cedric/go/src/fyne.io/fyne/internal/async/chan_func.go:22 +0xf8

goroutine 56 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/window.go:34 +0x4d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:946 +0x136

goroutine 12 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:145 +0x3a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:144 +0xf9

goroutine 13 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:128 +0x2b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:127 +0xea

goroutine 14 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0xc0003cb3e0)
	/home/cedric/go/src/fyne.io/fyne/internal/async/chan_func.go:45 +0xf1
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
	/home/cedric/go/src/fyne.io/fyne/internal/async/chan_func.go:22 +0xf8

goroutine 15 [runnable]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize(0xc0003d9180?, {0xc0001edcf8?, 0x2?}, 0x41500000?, {0x1, 0x0, 0x0, 0x0, 0x0})
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:73 +0x94
fyne.io/fyne/v2.MeasureText({0xc0001edcf8, 0x2}, 0x18?, {0x1, 0x0, 0x0, 0x0, 0x0})
	/home/cedric/go/src/fyne.io/fyne/text.go:47 +0x88
fyne.io/fyne/v2/canvas.(*Text).MinSize(0xc0004be000?)
	/home/cedric/go/src/fyne.io/fyne/canvas/text.go:28 +0x4c
fyne.io/fyne/v2/widget.(*textRenderer).layoutRow(0x0?, {0xc001f34790, 0xc0000b9a7c?, 0xc0000b9a80?}, 0xbf00c0?, 0x41000000, 0x41000000, 0xc1800000)
	/home/cedric/go/src/fyne.io/fyne/widget/richtext.go:651 +0xbc
fyne.io/fyne/v2/widget.(*textRenderer).Layout(0xc001fefe60, {0xb9c28?, 0xc0?})
	/home/cedric/go/src/fyne.io/fyne/widget/richtext.go:503 +0x6c7
fyne.io/fyne/v2/widget.(*textRenderer).Refresh(0xc001fefe60)
	/home/cedric/go/src/fyne.io/fyne/widget/richtext.go:644 +0x3b3
fyne.io/fyne/v2/widget.(*RichText).CreateRenderer(0xc001fdfce0)
	/home/cedric/go/src/fyne.io/fyne/widget/richtext.go:75 +0x208
fyne.io/fyne/v2/widget.(*Label).CreateRenderer(0xc001f9bc80)
	/home/cedric/go/src/fyne.io/fyne/widget/label.go:63 +0x185
fyne.io/fyne/v2/internal/cache.Renderer({0xdae0d8, 0xc001f9bc80})
	/home/cedric/go/src/fyne.io/fyne/internal/cache/widget.go:33 +0x109
fyne.io/fyne/v2/widget.(*Label).MinSize(0xc001f9bc80)
	/home/cedric/go/src/fyne.io/fyne/widget/label.go:83 +0x3e
fyne.io/fyne/v2/widget.(*tableRenderer).Refresh(0xc001442660)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:827 +0x32
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc001432028?)
	/home/cedric/go/src/fyne.io/fyne/widget/widget.go:138 +0x2e
fyne.io/fyne/v2/widget.(*Table).SetColumnWidth(0xc001432000, 0xc0011ea690?, 0x42e64000)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:268 +0xb9
fyne.io/fyne/v2/widget.(*Table).Dragged(0xc001432000, 0xc0002711e8)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:186 +0x146
fyne.io/fyne/v2/widget.(*clip).Dragged(0xc0000b9fb0?, 0xc00247c101?)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:1411 +0x1d
fyne.io/fyne/v2/internal/driver/glfw.(*window).processMouseMoved.func5()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:458 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:946 +0x136

goroutine 82 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.catchTerm(0x0?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:188 +0x8f
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:168 +0x6b

goroutine 83 [chan receive]:
github.com/godbus/dbus/v5.newConn.func1()
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/conn.go:303 +0x32
created by github.com/godbus/dbus/v5.newConn
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/conn.go:302 +0x4f6

goroutine 20 [syscall]:
os/signal.signal_recv()
	/usr/lib/go/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/lib/go/src/os/signal/signal.go:151 +0x2a

goroutine 58 [IO wait]:
internal/poll.runtime_pollWait(0x7fa5c90383d0, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0004a8900?, 0xc000e95d80?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc0004a8900, {0xc000e95d80, 0x10, 0x10}, {0xc0012bc020, 0x1000, 0x1000}, 0x70000c000070800?)
	/usr/lib/go/src/internal/poll/fd_unix.go:304 +0x3aa
net.(*netFD).readMsg(0xc0004a8900, {0xc000e95d80?, 0x1265f98?, 0xc000e95c34?}, {0xc0012bc020?, 0xc000e95ace?, 0xc000e95ac8?}, 0xc000e95ac4?)
	/usr/lib/go/src/net/fd_posix.go:78 +0x37
net.(*UnixConn).readMsg(0xc000014518, {0xc000e95d80?, 0xc0012d07b0?, 0xda1040?}, {0xc0012bc020?, 0xdaa2f0?, 0x1592540?})
	/usr/lib/go/src/net/unixsock_posix.go:115 +0x4f
net.(*UnixConn).ReadMsgUnix(0xc000014518, {0xc000e95d80?, 0x0?, 0x0?}, {0xc0012bc020?, 0x4348a8?, 0xc0004d4d68?})
	/usr/lib/go/src/net/unixsock.go:143 +0x3c
github.com/godbus/dbus/v5.(*oobReader).Read(0xc0012bc000, {0xc000e95d80?, 0xc0012c9de8?, 0x434c87?})
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/transport_unix.go:21 +0x45
io.ReadAtLeast({0xda16c0, 0xc0012bc000}, {0xc000e95d80, 0x10, 0x10}, 0x10)
	/usr/lib/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/lib/go/src/io/io.go:351
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0xc0012b6cc0)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/transport_unix.go:91 +0x11e
github.com/godbus/dbus/v5.(*Conn).inWorker(0xc0011bda40)
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/conn.go:390 +0x48
created by github.com/godbus/dbus/v5.(*Conn).Auth
	/home/cedric/go/src/fyne.io/fyne/vendor/github.com/godbus/dbus/v5/auth.go:118 +0x99c

goroutine 99 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:145 +0x3a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:144 +0xf9

goroutine 100 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:128 +0x2b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/driver_desktop.go:127 +0xea
```

**Review by Bluebugs — APPROVED** [review]
Looks good.

**Review by Bluebugs — CHANGES_REQUESTED** [review]
I just got a dead lock while resizing my application. Working on a backtrace.

**Review by Bluebugs — APPROVED** [review]
Sorry it is unrelated.

**Pull request merged**
