### PR TITLE
Upgrade github.com/go-text/typesetting to v0.1.0

### LINKED ISSUE #4441: Fyne app now broken after upgrading go to 1.21.5 and doing go get -u.
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have a fyne app I'm developing that compiled and ran happily until I upgraded golang and did a go get -u.

I now have 

`# fyne.io/fyne/v2/internal/painter
../../go/pkg/mod/fyne.io/fyne/v2@v2.4.2/internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)
`
when I do a go run .

Any ideas?

### How to reproduce

Install golang 1.21.5
go get -u
try and run an application that was previously running.

### Screenshots

_No response_

### Example code

go run .

### Fyne version

2.4.2

### Go compiler version

1.21.5

### Operating system and version

Linux (KDE Neon)

### Additional Information

_No response_

### LINKED ISSUE #4443: Getting a "type shaping.Bounds has no field or method LineHeight" build error on v2.4.2 after go get -u
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am getting the following error on v2.4.2 after running `go get -u`. The issue is caused by go-text being updated to the latest version. I get the following error

```shell
internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)
```

The issue seems to be introduced in the commit https://github.com/go-text/typesetting/commit/2599c4677d2691cb91f68c0d3599fab87eb34ef1
 and the call to `LineBounds.LineHeight()` at https://github.com/fyne-io/fyne/blob/dc34dad76137def4466ab8eb4166e7ae741ef9ee/internal/painter/font.go#L209

### How to reproduce

1. Create a fresh app (I used the getting started example at https://developer.fyne.io/started/hello)
2. `go run .`
3. This will run fine
4. `go get -u`
5. The next `go run .` will give me the error
6. Downgrading go-text to an earlier version `go get -u github.com/go-text/typesetting@v0.0.0-20231101082850-a36c1d9288f6` fixes it

### Screenshots

_No response_

### Example code

Probably any app, but I used the getting started example at https://developer.fyne.io/started/hello

### Fyne version

2.4.2

### Go compiler version

1.21.4

### Operating system and version

Ubuntu 23.04

### Additional Information

_No response_

### LINKED ISSUE #4468: Compilation fails with error about out.LineBounds.LineHeight in internal/painter/font.go:209:65
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Compilation of my program (which uses almost all of Fyne's features) fails after a general dependency upgrade:

```
fyne.io/fyne/v2/internal/painter
/home/nemo/go/pkg/mod/fyne.io/fyne/v2@v2.4.2/internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)

```
The program is the [GUI version of my toy Lisp interpreter](https://github.com/rasteric/z3s5-lisp/blob/main/cmd/z3g/z3g.go) with wrapper functions defined [here](https://github.com/rasteric/z3s5-lisp/blob/main/gui/gui.go).

### How to reproduce

It's a compilation failure on Linux Mint 21.2 Cinnamon using Go 1.21.4

### Screenshots

_No response_

### Example code

I cannot isolate the compilation error, the wrapper uses nearly all features of Fyne. But it compiled fine before I upgraded dependencies.

### Fyne version

2.4.2

### Go compiler version

1.21.4

### Operating system and version

Linux Mint 21.2

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by donatj**
### Description:

github.com/go-text/typesetting mildly broke their API when they tagged their first release.

You can see in the commit though that LineHeight was renamed LineThickness without changing the logic.

image

https://github.com/go-text/typesetting/commit/2599c4677d2691cb91f68c0d3599fab87eb34ef1#diff-2dbee40d9565bb554054307ecf43cd0019c06d0e5d61d5a6fa0f6cb168f2631dR103-R109

Fixes #4468
Fixes #4443
Fixes #4441

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks for this. Please run `go mod tidy` on the code and fill in the checkboxes in the PR template (plus delete those that do not apply).

**Comment by donatj** [comment]
@Jacalz this was actually a bigger change than I'd anticipated. I'm getting a ton of failing tests even doing my best to update the png's for the failing rendering. I'm out of my element, lol. I'm going to close this I think … 😵‍💫

**Comment by andydotxyz** [comment]
If you're on an Apple M2 the failing test images may be false negatives. If our CI says failure then it is indeed broken.

**Comment by donatj** [comment]
@andydotxyz does M1 count in that too? I only have Apple Silicon based systems to test on. Can you trigger the CI tests here?

**Comment by Jacalz** [comment]
I think it does nut might be wrong. Please run `go mod tidy` first though. There is not much reason to run the tests until the module file is correct

**Comment by andydotxyz** [comment]
> @andydotxyz does M1 count in that too? I only have Apple Silicon based systems to test on. Can you trigger the CI tests here?

Apologies yes I think it may apply to all Apple Silicon. We need to solve this as the developer % on M1/2 increases.

**Comment by Jacalz** [comment]
There are more breaking changes than just `LineHeight`. This does not compile in its current state.

**Comment by Jacalz** [comment]
Fixing that compilation error does lead to a test failing due to ellipsis clipping output changing slightly. I think there is more work required here.

**Comment by andydotxyz** [comment]
> There are more breaking changes than just `LineHeight`. This does not compile in its current state. See [go-text/typesetting@0024ac6](https://github.com/go-text/typesetting/commit/0024ac628562919a80237a0ddf6293a3f6a01919).

Good point.
The fix is:
```diff
        l.Prepare(conf, runes, shaping.NewSliceIterator([]shaping.Output{out}))
-       finalLine, _, done := l.WrapNextLine(limit)
+       wrapped, done := l.WrapNextLine(limit)
 
-       count := finalLine[0].Runes.Count
+       count := wrapped.Line[0].Runes.Count
        full := done && count == len(runes)
```

And the test fix is simply the following (looks like no image tests were impacted @donatj !
```diff
@@ -100,7 +100,7 @@ func TestSelect_ClipValue(t *testing.T) {
 
        r2 := cache.Renderer(text)
        assert.Equal(t, 1, len(r2.Objects()))
-       assert.Equal(t, "som<E2><80><A6>", r2.Objects()[0].(*canvas.Text).Text)
+       assert.Equal(t, "some<E2><80><A6>", r2.Objects()[0].(*canvas.Text).Text)
 }
```

**Review by Jacalz — CHANGES_REQUESTED** [review]
Just a new review to sum up what needs to be done:
- Run `go mod tidy` to clean up and make the module files correct.
- Modify the code according to Andrew's comment above to fix compilation and test.

With that done, this should be good to go :)

**Comment by Jacalz** [comment]
Strange. I could swear that running Go mod tidy a few days ago was changing things on my end. My git install is behaving strangely now. Will restart my computer later today and see if I can see the same thing

**Review by Jacalz — APPROVED** [review]
You are absolutely right. Sorry about that. I don't know what was up with my setup. Everything is working correctly now :+1: 

Thanks for the contribution and for sponsoring Fyne. Much appreciated! :1st_place_medal:

**Comment by Jacalz** [comment]
Just remember to check the checkboxes in the PR description next time please :)

**Pull request merged**
