### PR TITLE
Apply the proposed fix for rounding errors in minsize/grid

### LINKED ISSUE #2817: Unexpected vertical scroll bar in entry
### Describe the bug:
As the title describes, when the grid layout is used, the vertical scroll bar appears in the entry

### To Reproduce:
Steps to reproduce the behaviour:
- Run the code below

### Screenshots:
图片

### Example code:
```go
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Widget")

	input := widget.NewEntry()
	input.SetPlaceHolder("Enter text...")

	content := container.NewGridWithColumns(2, input, widget.NewButton("btn", nil))

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows10
 - **Version:** 19044
 - **Go version:** go1.17.5
 - **Fyne version:** 2.1.3

### PR DESCRIPTION
**Pull request by andydotxyz**
Lots of test file changes as we essentially move to rounding up when aligning to pixels.

Fixes #2817

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Oh man random failures in a render test again :( How does fixing a rounding error cause such issues? :(
Cannot replicate locally either...

**Comment by andydotxyz** [comment]
> Oh man random failures in a render test again :( How does fixing a rounding error cause such issues? :(

My bad, it was not random - the images were generated on not-darwin, so have updated them now and things pass again :)

**Review by Bluebugs — APPROVED** [review]

**Review by Jacalz — CHANGES_REQUESTED** [review]
This seems to have merge conflicts. Rebase and you should be good to go :)

**Comment by andydotxyz** [comment]
Good catch @Jacalz sorry about that, I think I left it still too long.

**Review by Jacalz — APPROVED** [review]

**Pull request merged**
