### PR TITLE
Pick newer go-text with lower memory allocation.

### PR DESCRIPTION
**Pull request by Bluebugs**
### Description:
After https://github.com/go-text/typesetting/issues/53 landed, this significantly improve the amount of memory allocated during the drawing of a string. Picking up latest go-text lead to significantly less memory spike and allocation in my tests. Would be good to see if it solve any of #3471 or at least help.

#### Where applicable:
- [x] Updated the vendor folder (using `go mod vendor`).
- [x] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by dweymouth** [comment]
Very much looking forward to this as it might finally unblock allowing users to set their own font in my app and allow theme variant switching without memory issues. Do you need to call the new `SetFontCacheSize` API that was introduced in [go-text/typesetting#54](https://github.com/go-text/typesetting/pull/54)?

**Comment by andydotxyz** [comment]
Might be worth holding off a few more hours for a more complete reduction in initial memory requirement go-text/typesetting#58

**Comment by Bluebugs** [comment]
#58 seems like it will address the problem with large font, but there might be still some work on that one. With #53, I hope that the pick usage seen by @Jacalz is gone as I don't think he was using a special font for his tests. It would still be interesting to know if we are making general progress there or if we should look more into our allocation pattern.

**Comment by andydotxyz** [comment]
Good point. As it's about memory usage is there a before/after benchmark or measurement to verify?

**Comment by Bluebugs** [comment]
It does help in my own local tests, but I was hoping @Jacalz could re run the test he was doing with his app that was showing the issue in #3471.

**Comment by Jacalz** [comment]
I see about a 2 to 3 megabyte reduction. Nothing huge but a nice improvement :)

**Comment by Bluebugs** [comment]
Dang, I was hoping for more :-( Back at looking at our allocation profile I guess. Maybe you can use fyne build --pprof and share the resulting allocs file.

**Comment by Jacalz** [comment]
Sounds like a good plan. I just did some quick tests today. Will do some more thorough testing when I have a chance :)

**Comment by Jacalz** [comment]
I created some memory profiles using [rymdport](https://github.com/Jacalz/rymdport) on the [next](https://github.com/Jacalz/rymdport/tree/next) branch. The profiles were made by just clicking through the tabs a couple times. Memory usage does climb to around 60-70MB from around 55MB (according to the system monitor when collecting the profiles).

I believe that the one called `before.pprof` (on current develop branch) has slightly lower memory usage over all but it might just have been a fluke as it was not what I got when testing yesterday. The profile `after.pprof` is with this path applied. I hope that the profiles are helpful to figure out where memory is allocated/leaking.

[profiles.zip](https://github.com/fyne-io/fyne/files/11225675/profiles.zip)

**Comment by Bluebugs** [comment]
Was that the result of http://localhost:6060/debug/pprof/heap or http://localhost:6060/debug/pprof/allocs? I have the impression of the former. In that case, it seems our permanent used memory cost clearly come from font being fully loaded in memory and the patch pointed by Andrew should help. I would still like to see the result of allocs as that might point to why the GC keep memory high and doesn't give it back to the OS.

**Comment by Jacalz** [comment]
I believe it was the former, like you say, but I didn't use the built in pprof but instead the `pkg/pprof` package because I couldn't figure out how to collect the file. Will give allocs a go tomorrow.

**Comment by Jacalz** [comment]
We might want to make that more clear with the flag (I never got a chance to review the original PR before merging). I'll give it a shot later today if I can manage :)

**Comment by Jacalz** [comment]
Here's a memory allocation profile of Rymdport when using this PR: [allocs-with-pr.zip](https://github.com/fyne-io/fyne/files/11240243/allocs-with-pr.zip)

**Review by Jacalz — APPROVED** [review]
It works fine. No reason to not approve :)

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
