### PR TITLE
Adding Must methods to binding API

### LINKED ISSUE #2599: Binding "Must*" variants
### Is your feature request related to a problem? Please describe:

Struct binding is a little clunky to use with all of the error handling involved. First the user must bind to the struct, and then they'll want to bind to fields within the struct. Consider this example.
https://play.golang.org/p/Afw8NqQv6lR

Another case shown in the playground link is when manipulating a bound value with `Get` and `Set`. In this case it's not immediately clear to the user why either method *should* return an error in the first place, but an error returned must be an error handled. This is troublesome enough that even fyne examples don't always handle this error, and the user should be able to opt out of handling it in favor of panicking.

An idiomatic way to accomplish this behavior could be borrowed from something like the regexp package in the standard library. It has "Must" variants of functions for situations where the user knows that if the regex fails to compile, something critical will not work, so the best option is to panic.
https://pkg.go.dev/regexp#MustCompile

### Is it possible to construct a solution with the existing API?

The current solution is the problem. Errors must be handled - in some cases it's not clear why - and there should be an alternative.

### Describe the solution you'd like to see:

Provide "Must" variants of binding interaction functions. See the go playground link above for comments showing suggestions with struct binding and working with field binding Get/Set.

### PR DESCRIPTION
**Pull request by drognisep**
### Description:

Adding Must variants to binding API

Fixes #2599 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
  - Looks like there are some random benchmark failures locally

### CODE REVIEW

**Comment by drognisep** [comment]
@andydotxyz I'm not sure what's failing with static analysis. What am I missing there?

**Comment by drognisep** [comment]
@andydotxyz brought up some good points on this idea. This should be addressed with documentation, not panic options.
* As a rule things shouldn't panic in production. There are cases where an actual error would never be returned, and the error can be assigned to `_` in that case.
* Errors can convey legitimate conversion and validation problems and those should be handled appropriately and reported to the user rather than panicking.

All in all, the option to panic isn't more useful than ignoring a particular error completely (and can certainly be an anti-pattern instead), and it should be documented when errors will and will not be returned (and why) so the developer has better awareness.

**Comment by andydotxyz** [comment]
> @andydotxyz I'm not sure what's failing with static analysis. What am I missing there?

It looks like we had a merge conflict that slipped in - we recently updated to needing the new format for build tags on develop and I think some open PRs didn't have that yet. I will go check develop is consistent so new PRs don't hit this again.

**Comment by andydotxyz** [comment]
> I will go check develop is consistent so new PRs don't hit this again.

Yeah I was right, this is now fixed.

**Comment by drognisep** [comment]
> > I will go check develop is consistent so new PRs don't hit this again.
> 
> Yeah I was right, this is now fixed.

Thank you! :)

**Pull request closed without merging**
