### PR TITLE
Implement kayboard navigation in widget.Tree

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This implements the Focusable interface for Tree Nodes. Added keyboard navigation:
- Navigate between tree nodes using `tab` and `shift + tab`.
- Select a tree node by pressing space.
- Open a branch by pressing `right` and close using `left`. 

For https://github.com/fyne-io/fyne/issues/1515

Opening as draft for now until I have implemented tests.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
It seems like up/down would pair better with left/right than tab/shift+tab do...

**Comment by Jacalz** [comment]
But the focusing controls that landed in the List widget a while ago just uses Tab?

**Comment by andydotxyz** [comment]
> But the focusing controls that landed in the List widget a while ago just uses Tab?

Ah. Oops. On playing with it I don't think that was right.
Unfortunately it needs work on List as it will only tab through visible widgets - it really should handle moving up and down the list of items full, not just those rendered.

**Comment by Jacalz** [comment]
I'll close this and work on some other items that I prioritize higher. My backlog is getting rather big and with my limited spare time,  I prefer to work on improvements that I will be using in the near future. Sorry.

**Pull request closed without merging**
