### PR TITLE
Fix race in window fullscreen test

### PR DESCRIPTION
**Pull request by andydotxyz**
### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by dweymouth — APPROVED** [review]

**Review by Jacalz — CHANGES_REQUESTED** [review]
It seems like you are passing in a "false" parameter into almost all uses of the function. Would another solution not be better?

**Comment by andydotxyz** [comment]
I'm not sure what other solution you have in mind.
This helper function was doing too much in one block so either we pass in this extra state or it has to split into separate functions and all the tests have more code than before?

**Comment by Jacalz** [comment]
If I counted correctly, you are only passing in true in one of the tests. That just makes me think that the parameter shouldn't be there and that that one test needs to be modified, not all the other.

**Comment by andydotxyz** [comment]
> If I counted correctly, you are only passing in true in one of the tests. That just makes me think that the parameter shouldn't be there and that that one test needs to be modified, not all the other.

I understand. Updated.

**Comment by andydotxyz** [comment]
I guess the tests don't agree - for some reason that kicked me back to square one.
Off to think more.

**Comment by andydotxyz** [comment]
Merging in with the requested change to get this release together

**Comment by andydotxyz** [comment]
Not a problem. I think the items on GitHub appeared out of order for some reason. The commit above was the result of the thinking.

**Pull request merged**
