### PR TITLE
Add text benchmark tests

### PR DESCRIPTION
**Pull request by stuartmscott**
### Description:
Adds benchmark tests to measure the performance of splitLines and lineBounds text utilities.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [n/a] Public APIs match existing style.
- [n/a] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by stuartmscott** [comment]
On my laptop I get;
```
BenchmarkText_splitLines-4             	  129406	      9078 ns/op
BenchmarkText_lineBounds_WrapOff-4     	  137056	      8397 ns/op
BenchmarkText_lineBounds_Truncate-4    	       2	 828793583 ns/op
BenchmarkText_lineBounds_WrapBreak-4   	       1	12564453053 ns/op
BenchmarkText_lineBounds_WrapWord-4    	       1	1852231602 ns/op
```

**Comment by stuartmscott** [comment]
Travis failure is unrelated:
```
--- FAIL: TestFileWatcher_FileDeleted (0.37s)
    settings_desktop_test.go:87: File watcher callback was not called
FAIL
```
@Jacalz should these tests be run by travis?

**Comment by Jacalz** [comment]
> Travis failure is unrelated:
> 
> ```
> --- FAIL: TestFileWatcher_FileDeleted (0.37s)
>     settings_desktop_test.go:87: File watcher callback was not called
> FAIL
> ```
> 
> @Jacalz should these tests be run by travis?

The issue should be fixed in develop. I don’t know why it is appearing now, especially since no other pull requests are seeing this anymore.

**Comment by stuartmscott** [comment]
Maybe Travis doesn't like my PRs. It only seems to fail on Windows

**Comment by Jacalz** [comment]
> Maybe Travis doesn't like my PRs. It only seems to fail on Windows

Jag, I think this might be a regression in 1.14. It is only failing on that one at the moment and I know that there are regressions due to the changes in preemptive  go routine behavior. Let’s see what the new bug fix releases bring to the table. In the meantime, I will have a look and make sure that I didn’t miss any error handling that should be reverted due to the quirks in fsnotify.

**Comment by stuartmscott** [comment]
Thanks @Jacalz - I appreciate it!

**Pull request merged**
