### PR TITLE
Add Shift+Insert support for Paste shortcut

### PR DESCRIPTION
**Pull request by pymq**
One of my users noticed that Shift+Insert is a common shortcut for paste and should work - I think it's reasonable, as it works almost everywhere (QT, GTK, browsers what I tested), what do you say?

### CODE REVIEW

**Comment by swbartosz** [comment]
What about also adding:
CTRL + Insert for Copy
Shift + Delete for CUT

**Comment by andydotxyz** [comment]
This looks like a good change. I agree with @swbartosz though, it would be good to add the group rather than just a single one?

**Comment by pymq** [comment]
Didn't know about them :)
Thanks, added.

**Comment by andydotxyz** [comment]
Did you pull in the develop branch somehow? it seems to have added those commits to the history here but it doesn't normally do that...
Can you pick your 2 commits on top of the latest develop instead?

**Comment by andydotxyz** [comment]
It looks good from a code point of view though :)

**Comment by pymq** [comment]
Yeah, I tried to rebase on develop but messed up.
Fixed now

**Comment by andydotxyz** [comment]
Excellent thanks

**Pull request merged**
