### PR TITLE
Don't log a common error - lots of environments don't have this exported

### LINKED ISSUE #3515: org.freedesktop.portal.Desktop not exist
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

it is not fatal bug, but I have tried 2.2 vs 2.3 version on termux-proot-arch (except litle bit bigger binary 13M vs 16M) I have found interasting log:    `org.freedesktop.portal.Desktop not exist...`

### How to reproduce

1. run andronix-proot on termux
2. compile current version
3. see log

### Screenshots

Screenshot_20221229_201438_VNC Viewer

### Example code

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Fyne version

2.3

### Go compiler version

1.19

### Operating system

Linux

### Operating system version

arch (android 13 on sm-p619)

### Additional Information

version show neofetch ....

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #3515

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
Is it not better to keep the error? In my opinion, this is not much different than a systray enabled application giving an error when there is no systray support.

Would it perhaps be better to instead also print something about the desktop potentially not supporting dark theme preference?

**Comment by andydotxyz** [comment]
It's not really the same. This is a spec set up by one of many platforms that others don't respect. It means that a large percentage of apps launched on Linux will show this error.

I was responding to an issue which was opened because of just such a setup. 

It's not like systray - in that instance functionality will be limited. In this case it is likely of zero impact, because a desktop without this property may be setting dark mode in some other way.

**Comment by Jacalz** [comment]
But there could be genuine errors that we don't see on platforms with working support?

**Comment by andydotxyz** [comment]
This is one of many locations that can error in the method. This one is looking up the service which provides this data. If it is not present (but the dbus is working, as no earlier error) I'm not sure what else it could mean...

If looking for comparisons it's a bit like running on an Apple Intel and presenting an error because an M1 specific extension cannot be found. Something that a lot of users will see and is quite reasonable to ignore.

**Review by Jacalz — APPROVED** [review]
Alright then.

**Pull request merged**
