### PR TITLE
Update deps for initial NetBSD support

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This enables us to successfully build and run on NetBSD.

Screenshot from 2021-12-10 21-02-36

With this added, we now support all three major BSD versions (FreeBSD, OpenBSD and NetBSD).
The only missing BSD project is DragonflyBSD (`dragonfly` is the build tag for it). It would be cool to add that for completeness as it and illumos/solaris support are everything that is missing from supporting pretty much all unix-like operating systems that Go supports.

Installing on NetBSD can be done using the following command (as root):
```
pkgin install go pkgconf
```

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [x] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
I think this missed "go mod tidy" on the latest version?

**Comment by Jacalz** [comment]
I don't think so? I know that it was the case once up on a time, but the latest commit should have fixed that.

**Comment by Jacalz** [comment]
Running `go mod vendor` removed one item from the modules.txt file. Was that perhaps what you meant?

**Comment by andydotxyz** [comment]
Apologies, it seems that my comment missed your commit "Tidy the modules" which did indeed resolve it already.

**Review by andydotxyz — APPROVED** [review]

**Comment by Jacalz** [comment]
No worries. I find it weird that Go 1.16 doesn't always complain about thing not having been tidied.

**Pull request merged**
