### PR TITLE
Ignore Carriage Return when Measuring or Drawing Text

### PR DESCRIPTION
**Pull request by stuartmscott**
Carriage Return character is ignored in both the measure and draw loops.

Fixes: #2456

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass. (except unrelated test failures: https://gophers.slack.com/archives/CK5U4BU87/p1642091780028600)

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]

**Review by andydotxyz — COMMENTED** [review]
Apologies, I approved this as a good approach, but then I thought maybe there is need for an Entry test as well - when \r\n is the newline combination does it behave correctly with these elements simply not displayed?

**Comment by andydotxyz** [comment]
Thanks @stuartmscott , I see multiline Entry does not limit to 1 line.
I guess 2 options here:
* Remove the multi-check test that shows it is wrong and add that to a new issue.
* Fix the issue on this ticket too.

I think the first is perfectly OK - just avoiding committing a test with wrong output as golden image.

**Review by andydotxyz — APPROVED** [review]
Thanks @stuartmscott - before closing can you link to a bug for the single line supporting multiple lines so we don't forget?

**Comment by stuartmscott** [comment]
Moved to https://github.com/fyne-io/fyne/pull/2758

**Pull request closed without merging**
