### PR TITLE
Remove one small unnecessary type convertion

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

It ain't much, but it's honest work :)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — DISMISSED** [review]
Sorry about the test failure, maybe it was the 2.0.4 merge to develop

**Comment by Jacalz** [comment]
Sorry for the force push. Something was weird locally and git did not allow me to push after the rebase.

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
> Sorry for the force push. Something was weird locally and git did not allow me to push after the rebase.

I think it is rarely possible to push after a rebase unless you force. The rebase command rewrites history.

**Comment by Jacalz** [comment]
> > Sorry for the force push. Something was weird locally and git did not allow me to push after the rebase.
> 
> 
> 
> I think it is rarely possible to push after a rebase unless you force. The rebase command rewrites history.

Yeah that's true, there was however a strange error that wasn't the one that I was used to seeing.

**Pull request merged**
