### PR TITLE
cmd/fyne: Update goinfo for BSD support in "fyne env" command

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This updates `lucor/goinfo` to the latest commit, whick includes my work (https://github.com/lucor/goinfo/pull/2) on getting it to work on BSD also. I think we might want to backport this to 2.0.1.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
Hmm, looks like Windows and MacOS aren't working. Will look into that.

**Comment by andydotxyz** [comment]
> Hmm, looks like Windows and MacOS aren't working. Will look into that.

The XDG code seems to be running on Windows.
Also it seems to depend on Go 1.13.

**Comment by Jacalz** [comment]
> > Hmm, looks like Windows and MacOS aren't working. Will look into that.
> 
> The XDG code seems to be running on Windows.
> Also it seems to depend on Go 1.13.

Yeah, it seems to be missing a few build tags. Works great on Linux and BSD, but not on others. I have no idea why it would require Go 1.13 all of the sudden. Nothing except build tags and variable names have changed.

**Comment by andydotxyz** [comment]
A bug in the upstream PR meant that the build flags were ignored (commented inline).
The info project probably needs some more automated tests.

**Comment by andydotxyz** [comment]
Don't you need to revert https://github.com/fyne-io/fyne/commit/d20eda1f4960255830a1bf2d23bc7c9ff9d42723 as well?

**Comment by Jacalz** [comment]
> Don't you need to revert [d20eda1](https://github.com/fyne-io/fyne/commit/d20eda1f4960255830a1bf2d23bc7c9ff9d42723) as well?

Ah, yes. Sorry about that. Will get that added in tomorrow.

**Comment by Jacalz** [comment]
> Don't you need to revert [d20eda1](https://github.com/fyne-io/fyne/commit/d20eda1f4960255830a1bf2d23bc7c9ff9d42723) as well?

Looks like you reverted it yourself a while back ;) https://github.com/fyne-io/fyne/commit/a5684de9eae75e542463e2a7909b03361bfe4ca9
The command works as expected without reverting it:
Screenshot from 2021-02-10 15-58-10

**Comment by Jacalz** [comment]
I made sure to get the vendor folder updated as well :)

**Comment by andydotxyz** [comment]
> Looks like you reverted it yourself a while back ;) [a5684de](https://github.com/fyne-io/fyne/commit/a5684de9eae75e542463e2a7909b03361bfe4ca9)

Not completely, the following line is still not present, should it be added back in now?
```
reporters = append(reporters, &report.OS{})
```

**Comment by Jacalz** [comment]
> > Looks like you reverted it yourself a while back ;) [a5684de](https://github.com/fyne-io/fyne/commit/a5684de9eae75e542463e2a7909b03361bfe4ca9)
> 
> Not completely, the following line is still not present, should it be added back in now?
> 
> ```
> reporters = append(reporters, &report.OS{})
> ```

Ah, yes. Sorry about that. I added it back in and it works as expected now and of course also prints the OS info again on other systems as well. Two birds with one stone, I'd say :slightly_smiling_face:

**Review by andydotxyz — APPROVED** [review]
Thanks for bringing this back

**Pull request merged**
