### PR TITLE
extract markup fixtures

### LINKED ISSUE #1669: Move Test Markup to Files
### Is your feature request related to a problem? Please describe:
Updating XML markup tests is tedious as deltas need to be copied from the test output to a specific place inside the test files.

### Is it possible to construct a solution with the existing API?
No. Golden image tests are simpler to update as they only require copying the test output file to the golden image file.

### Describe the solution you'd like to see:
Move XML markup to files under `testdata/`, and write test output markup under `testdata/failed` so that updating a test is as simple as copying a file.

### PR DESCRIPTION
**Pull request by toaster**
### Description:
This PR changes the markup rendering test helper to work with golden master files instead of strings.
It is now similar to the image based test helper.

Fixes #1669 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
I saw that a test failed and noted that we still seem to be writing out the failed markdown to the terminal. Do we really want to do that? It makes it very hard to see what actually failed when you  need to scroll through a lot of text. Thoughts?

**Comment by toaster** [comment]
> I saw that a test failed and noted that we still seem to be writing out the failed markdown to the terminal. Do we really want to do that? It makes it very hard to see what actually failed when you need to scroll through a lot of text. Thoughts?

Yes (we want this) and yes (here come my thoughts): a common failure would be that some class or some detail changed. IMO it is helpful to see this in the test output. I normally run tests in GoLand when developing/debugging where I don’t have to scroll a lot but benefit from the detailed diff that the test tells me without having to run a diff tool on the master and the actual output.

**Comment by toaster** [comment]
Regarding the failures: I guess this is a windows newline thing. I don’t know why we cancel builds on the first failure. I still think this is wrong. The outcome of the cancelled builds would have helped. Also, there are sometimes multiple failures which might depend on the test environment. With cancel-on-failure it takes longer to find all.

**Comment by Jacalz** [comment]
I don’t think we have it set up to cancel all on failure. It’s just a thing that GitHub actions does to save resources in their virtual environments.

**Comment by toaster** [comment]
> I don’t think we have it set up to cancel all on failure. It’s just a thing that GitHub actions does to save resources in their virtual environments.

They should stop to be so stingy. They are not Scots ;).

**Review by andydotxyz — APPROVED** [review]
Sweet improvement for managing the changes

**Comment by stuartmscott** [comment]
I agree the difference should be printed in the test output, though maybe not the whole XML expected and actual strings, but instead just the lines/substrings that differ

**Review by stuartmscott — APPROVED** [review]
This is an improvement of several orders of magnitude. Thank you

**Comment by toaster** [comment]
> I agree the difference should be printed in the test output, though maybe not the whole XML expected and actual strings, but instead just the lines/substrings that differ

At first thought I’d agree with that, at second thought not. The raw output just helped me to quickly identify the issue with the windows failures :).

**Comment by stuartmscott** [comment]
You may have found it more quickly because, instead of a wall of text, it would be many lines of `expected '\n', got '\r\n'`

**Comment by stuartmscott** [comment]
Case in point, this is not helpful output;

`
Error:      	Not equal: 
            	            	expected: "<canvas padded size=\"200x300\">\n\t<content>\n\t\t<widget pos=\"4,4\" size=\"192x292\" type=\"*widget.Tree\">\n\t\t\t<widget size=\"192x292\" type=\"*widget.Scroll\">\n\t\t\t\t<widget size=\"206x292\" type=\"*widget.treeContent\">\n\t\t\t\t\t<widget size=\"206x37\" type=\"*widget.branch\">\n\t\t\t\t\t\t<widget pos=\"28,4\" size=\"174x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"166x21\">A</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<widget pos=\"4,4\" size=\"20x29\" type=\"*widget.branchIcon\">\n\t\t\t\t\t\t\t<image fillMode=\"contain\" rsc=\"moveDownIcon\" size=\"20x29\"/>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"background\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,37\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,38\" size=\"206x37\" type=\"*widget.leaf\">\n\t\t\t\t\t\t<widget pos=\"52,4\" size=\"150x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"142x21\">11111</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"background\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,75\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,76\" size=\"206x37\" type=\"*widget.branch\">\n\t\t\t\t\t\t<widget pos=\"28,4\" size=\"174x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"166x21\">B</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<widget pos=\"4,4\" size=\"20x29\" type=\"*widget.branchIcon\">\n\t\t\t\t\t\t\t<image fillMode=\"contain\" rsc=\"moveDownIcon\" size=\"20x29\"/>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"primary\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,113\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,114\" size=\"206x37\" type=\"*widget.leaf\">\n\t\t\t\t\t\t<widget pos=\"52,4\" size=\"150x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"142x21\">2222222222</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"background\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,151\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,152\" size=\"206x37\" type=\"*widget.branch\">\n\t\t\t\t\t\t<widget pos=\"52,4\" size=\"150x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"142x21\">C</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<widget pos=\"28,4\" size=\"20x29\" type=\"*widget.branchIcon\">\n\t\t\t\t\t\t\t<image fillMode=\"contain\" rsc=\"moveDownIcon\" size=\"20x29\"/>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"background\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,189\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,190\" size=\"206x37\" type=\"*widget.leaf\">\n\t\t\t\t\t\t<widget pos=\"76,4\" size=\"126x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"118x21\">333333333333333</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"background\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t</widget>\n\t\t\t\t<widget pos=\"0,286\" size=\"192x6\" type=\"*widget.scrollBarArea\">\n\t\t\t\t\t<widget backgroundColor=\"scrollbar\" pos=\"0,3\" size=\"178x3\" type=\"*widget.scrollBar\">\n\t\t\t\t\t</widget>\n\t\t\t\t</widget>\n\t\t\t\t<widget pos=\"192,0\" size=\"0x292\" type=\"*widget.Shadow\">\n\t\t\t\t\t<linearGradient angle=\"270\" endColor=\"shadow\" pos=\"-8,0\" size=\"8x292\"/>\n\t\t\t\t</widget>\n\t\t\t</widget>\n\t\t</widget>\n\t</content>\n</canvas>\n"
            	            	actual  : "<canvas padded size=\"200x300\">\n\t<content>\n\t\t<widget pos=\"4,4\" size=\"192x292\" type=\"*widget.Tree\">\n\t\t\t<widget size=\"192x292\" type=\"*widget.Scroll\">\n\t\t\t\t<widget size=\"206x292\" type=\"*widget.treeContent\">\n\t\t\t\t\t<widget size=\"206x37\" type=\"*widget.branch\">\n\t\t\t\t\t\t<widget pos=\"28,4\" size=\"174x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"166x21\">A</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<widget pos=\"4,4\" size=\"20x29\" type=\"*widget.branchIcon\">\n\t\t\t\t\t\t\t<image fillMode=\"contain\" rsc=\"moveDownIcon\" size=\"20x29\"/>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,37\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,38\" size=\"206x37\" type=\"*widget.leaf\">\n\t\t\t\t\t\t<widget pos=\"52,4\" size=\"150x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"142x21\">11111</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,75\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,76\" size=\"206x37\" type=\"*widget.branch\">\n\t\t\t\t\t\t<widget pos=\"28,4\" size=\"174x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"166x21\">B</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<widget pos=\"4,4\" size=\"20x29\" type=\"*widget.branchIcon\">\n\t\t\t\t\t\t\t<image fillMode=\"contain\" rsc=\"moveDownIcon\" size=\"20x29\"/>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle fillColor=\"primary\" size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,113\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,114\" size=\"206x37\" type=\"*widget.leaf\">\n\t\t\t\t\t\t<widget pos=\"52,4\" size=\"150x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"142x21\">2222222222</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,151\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,152\" size=\"206x37\" type=\"*widget.branch\">\n\t\t\t\t\t\t<widget pos=\"52,4\" size=\"150x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"142x21\">C</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<widget pos=\"28,4\" size=\"20x29\" type=\"*widget.branchIcon\">\n\t\t\t\t\t\t\t<image fillMode=\"contain\" rsc=\"moveDownIcon\" size=\"20x29\"/>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"4,189\" size=\"198x1\" type=\"*widget.Separator\">\n\t\t\t\t\t\t<rectangle fillColor=\"disabled\" size=\"198x1\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t\t<widget pos=\"0,190\" size=\"206x37\" type=\"*widget.leaf\">\n\t\t\t\t\t\t<widget pos=\"76,4\" size=\"126x29\" type=\"*widget.Label\">\n\t\t\t\t\t\t\t<text pos=\"4,4\" size=\"118x21\">333333333333333</text>\n\t\t\t\t\t\t</widget>\n\t\t\t\t\t\t<rectangle size=\"4x37\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t</widget>\n\t\t\t\t<widget pos=\"0,286\" size=\"192x6\" type=\"*widget.scrollBarArea\">\n\t\t\t\t\t<widget pos=\"0,3\" size=\"178x3\" type=\"*widget.scrollBar\">\n\t\t\t\t\t\t<rectangle fillColor=\"scrollbar\" size=\"178x3\"/>\n\t\t\t\t\t</widget>\n\t\t\t\t</widget>\n\t\t\t\t<widget pos=\"192,0\" size=\"0x292\" type=\"*widget.Shadow\">\n\t\t\t\t\t<linearGradient angle=\"270\" endColor=\"shadow\" pos=\"-8,0\" size=\"8x292\"/>\n\t\t\t\t</widget>\n\t\t\t</widget>\n\t\t</widget>\n\t</content>\n</canvas>\n"
`

**Pull request merged**
