### PR TITLE
widget/entry: remain the focus on Entry on popUp tap

### PR DESCRIPTION
**Pull request by tayadelmar**
related to #430

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is interesting. The test should not pass - as the paste callback is not firing.
I suspect that we have an issue whereby the test driver and the glfw driver behave differently with regards to focus? Maybe you could join the #fyne_contributors room on the gophers Slack server and we can discuss it further?

**Comment by tayadelmar** [comment]
Hm, actually I think that this test is useless for the callback testing, but it's okey that the Entry keeps focused, because nothing is happening. There is no any event happening, which will change the focus status.

> Maybe you could join the #fyne_contributors room on the gophers Slack server and we can discuss it further?

Sure, thanks for the invitation.

**Comment by tayadelmar** [comment]
I haven't found why entry looses the focus, I moved re-focus to NewPopUpMenu, so we will not need to re-focus for each action. 

NewPopUpMenu, canvas.SetOverlay(overlay), popUp.Show() are keeping canvas focused on the entry, but on Tapped, SecondaryTapped, MenuItem.OnTap the focus is already lost.

**Comment by andydotxyz** [comment]
Apologies I forgot about this PR. From the comments the state is unclear - is it complete or are there still issues to address?

**Comment by tayadelmar** [comment]
The PR solves the issue `focus lost on popUp tap`, but doesn't solve the issue `focus lost on overlay tap`.

**Comment by spatocode** [comment]
Nice fix @tayadelmar .

**Pull request merged**
