### PR TITLE
Add missed truncation mode for hyperlink

### PR DESCRIPTION
**Pull request by andydotxyz**
### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Review by dweymouth — APPROVED** [review]

**Comment by andydotxyz** [comment]
Fixes #4336 :)

**Comment by dweymouth** [comment]
> Fixes #4336 :)

I believe to fix #4336 we need to sync the truncation mode set on the parent RichText to the individual Hyperlink widgets that implement the HyperlinkSegments in richtext.go (or richtext_objects.go?)

**Comment by dweymouth** [comment]
Either one works, whichever's easier!

**Comment by andydotxyz** [comment]
Ok, let's leave it for now - it's actually more complex as the row layout code needs to understand that hyperlink can be truncated

**Pull request merged**
