### PR TITLE
Improved name consistency

### PR DESCRIPTION
**Pull request by vikkio88**
### Description:
This was done to avoid error in Icon List on the docs.
on [HERE](https://developer.fyne.io/explore/icons) those icons are presented as `ViewZoomIn` and `ViewZoomOut`, but in the code they are `ZoomIn` and `ZoomOut` the doc is generated by looking at the file names so I decided to make the naming more consistent.

this is what it looks now
image

and this is where they are generated from https://github.com/fyne-io/developer.fyne.io/blob/master/_gen/genicons.sh#L14

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
You cannot change a public API like this. I think the docs need fixed rather than changing exposed APIs

**Comment by vikkio88** [comment]
I only changed the names, the API already exposes the ZoomIn and ZoomOut
names?

**Comment by andydotxyz** [comment]
It looks like the API has changed:

image

**Comment by vikkio88** [comment]
this is too much changes for little gain, so will close it

**Pull request closed without merging**
