### PR TITLE
Expose more gomobile flags to package command

### PR DESCRIPTION
**Pull request by lkebin**
Replace #2919

### CODE REVIEW

**Comment by lkebin** [comment]
Expose gomobile flags could resolve #2899

**Comment by andydotxyz** [comment]
It it your intention that the minimum does not change - if so that probably helps with compatibility. However:

> However, if the API level of the platform is higher than the version declared by your app's targetSdkVersion, the system may enable compatibility behaviors to ensure that your app continues to work the way you expect.

(from https://developer.android.com/guide/topics/manifest/uses-sdk-element)
If the developer raises the target SDK higher than Fyne expects, then compatibility layers will be removed and features will stop working. If your aim is to fix the compile error then I don't think that this is the correct fix, as it opens up high risk of breakage at runtime.

Which compiler versions and device combinations have you tested against?

**Comment by lkebin** [comment]
> It it your intention that the minimum does not change - if so that probably helps with compatibility. However:
> 
> > However, if the API level of the platform is higher than the version declared by your app's targetSdkVersion, the system may enable compatibility behaviors to ensure that your app continues to work the way you expect.
> 
> (from https://developer.android.com/guide/topics/manifest/uses-sdk-element) If the developer raises the target SDK higher than Fyne expects, then compatibility layers will be removed and features will stop working. If your aim is to fix the compile error then I don't think that this is the correct fix, as it opens up high risk of breakage at runtime (because the Android code is written by Fyne, against version 15, not by the developer using the target they have installed).
> 
> Which compiler versions and device combinations have you tested against?

Understood, I just want to fix the compiler error, not really want to setup targetSdkVersion of the app.

Let's close the PR at the moment.

**Comment by lkebin** [comment]
> Ah, so you probably want the `compileSdkVersion` I guess? I wonder if we can fix the error in this way without exposing more flags. So target remains low and our code does not break - but we can discover what SDK is available and use it at compile time?

Actually, I want to fix this error:

```
no compiler for arm was found in the NDK (tried /Users/kb/Workspace/sdk/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang). Make sure your NDK version is >= r19c. Use `sdkmanager --update` to update it
```

The latest NDK version doesn't have `armv7a-linux-androideabi16-clang` anymore.

**Comment by andydotxyz** [comment]
Ok, that’s a great idea. If we have to update the minSDK then we must ensure all our code works at that minimum and update accordingly. If it is possible to use just a new compile version without impacting min we can keep compatibility and just find the lowest installed compiler to build. 
These possible solutions both avoid allowing developers to break Fyne behaviour accidentally.

**Pull request closed without merging**
