### PR TITLE
fix mac hang

### PR DESCRIPTION
**Pull request by dhowlett99**
### Description:

Fixes #(issue
 Hangs on repeated calls to SetSelected in table. #3684 

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Unfortunately a `defer` here is not OK - at the end we call `UpdateCell` (set to the local variable `updateCell`, which must not be within a lock.
User code should not be called when we are locked as they can call into any of our public API, which would be a deadlock

**Comment by dhowlett99** [comment]
Andy,  If I move the r.cells.propertyLock.Unlock() to just above the block just above the updateCell code it hangs. So something in the updateCell is causing a deadlock on Mac.  

If I follow the code down I end up at `func (w *BaseWidget) ExtendBaseWidget` which immediatley had another property lock. `w.propertyLock.Lock()`  I just don't have enough knowledge on Fyne to decipher whats happening here.

All I can tell you is if you call teh updateCell code without the lock you end up in dead lock on the Mac.

Let me know if there's any thing I can do to help. Perhaps a conf call ?

**Comment by andydotxyz** [comment]
> there is a stack trace in the original issue But I don't know why you refer to the updateCell Method as user code. Its a method on the table struct table.go line 30. from what i can see you should have the r.cells.propertyLock in place before messing with its internal cells.

The func() variable `updateCell` that I was referring to is set to the content of `r.cells.t.UpdateCell`. Therefore it must not be invoked with the table lock in place, as it is an exit point for the internal code.

**Comment by Jacalz** [comment]
Thanks for the contribution. I'm sorry that this got left for such a long time but I will have to close this per the rule that stale PRs can be closed after 6 months. If you want to continue working on this, you are more than welcome to rebase on latest `develop` and reopen (or open a new one if that's easier).

**Pull request closed without merging**
