### PR TITLE
add termux available

### PR DESCRIPTION
**Pull request by MatejMagat305**
well I would like to create video to fyne similar to [my video](https://youtu.be/7aUh39w_-2Q), would you agree?
On the video I show how to compile ndk apk in vlang (similar to golang) I think fyne it can done too
### Description:
add path on termux for fyne cmd (I asume that from apk cmd fyne will never call or will have similar structure like termux)

Fixes #(issue)
none
### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by Bluebugs** [comment]
That's interesting. Would you mind correcting the coding style?

Do you use a tablet with termux to develop with it? I am guessing there is more to support as you would want to install a fyne app from fyne cli and I would be surprised if that worked out of the box, but never the less, this is an interesting step forward.

**Comment by MatejMagat305** [comment]
sorry, I forgot you support 16+ - that method work on 28+ :(

**Comment by Jacalz** [comment]
You are not using any methods? What is it that only works on 1.18 (I assume it is the version you mean).

**Comment by MatejMagat305** [comment]
I mean version of android api ..., I was asume that it will be work when I enable path ...

**Comment by MatejMagat305** [comment]
I'm realy sorry it is seems like that go doesn't know open clang on termux ...

**Pull request closed without merging**
