### PR TITLE
WIP - Investigation - Add fine grained tuning to the app

### LINKED ISSUE #348: Memory leak in unused cached images
Just a video of me going through the fyne demo with task manager on the side , it seems to go well until the graphics tab as thats where memory usage makes massive spikes and is then never freed. 

https://youtu.be/b4Yh9dGj9e4?t=70

go1.12.4 windows/amd64

### PR DESCRIPTION
**Pull request by steveoc64**
### Description:

Add a simple keyValue store internally to store all tuning parameters used throughout an instance of the app.

Provide some Getters and Setters in the App object to allow the user/developer to fine tune these parameters.

Fixes #348 and #904 

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by steveoc64** [comment]
@andydotxyz  ... just confirming that you tweaked the main loop ?

So we are now running at 10Hz on the main loop.  Is it still feasible to make this tunable do you think ?

```
func (d *gLDriver) runGL() {
<<<<<<< HEAD
	// TUNING TODO - allow the ticker rate to be tunable ?
	fps := time.NewTicker(time.Second / 60)
=======
	eventTick := time.NewTicker(time.Second / 10)
>>>>>>> upstream/develop
```

**Comment by andydotxyz** [comment]
> 10Hz on the main loop

This is the event loop. The drawing is still 60FPS but is now on a different loop.
I don't think that 60FPS is tunable as we need to sync with the hardware.
I'm not sure what benefit tuning how often we look for events would add?

**Comment by Bluebugs** [comment]
Some backend will prefer to drive those tick tock directly (case for at least web assembly and wayland). I will not recommend to let the application control this.

**Comment by andydotxyz** [comment]
Closing due to age. This is a cool idea, but needs someone to champion such changes I guess.

**Pull request closed without merging**
