### PR TITLE
Replace theme maps with switch statements

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

This refactors and cleans up some of the theme code to use use functions with switch statements instead of static maps.
It has been said before but static maps can not be optimised by the compiler because it can not prove that they never change.
This decreases binary size by about 0,06% and is much more efficient.

### Checklist:

- [ ] Tests included.
- Should already be covered. It is also hard to write useful tests for functions that only switch on inputs.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Looks like a good change, but the functions are out of order

**Comment by Jacalz** [comment]
Good point. I have fixed it now

**Comment by Jacalz** [comment]
I have updated the PR to also include work for the icons code. However, I am not entirely sure why the tests are failing. Nothing seems incorrect to me.

**Comment by andydotxyz** [comment]
The tests look like they are failing because the test render to xml icon name lookup is broken

**Comment by Jacalz** [comment]
It feels strange that it would happen so suddenly. Will update the branch against develop and see if that changes anything (probably not).

**Comment by andydotxyz** [comment]
Feels vaguely logical from an outside perspective as the icon lookup code was changed in the theme package here - maybe test package needs to be updated to match?

**Comment by andydotxyz** [comment]
A really I figured out what it is - you moved from static resources (only ever one) to dynamic where it creates a new resource every time asked. So the test lookup is no longer getting a true when it compares a resource to the canonical call (as they are now different and indeed duplicate).

This actually seems like unnecessary object creation, perhaps this form of switch is not desirable.

**Comment by Jacalz** [comment]
I think you are right. The creation should be relatively cost-less because the function calls are inlined, but you are right that it isn't ideal. I will revert the commits about that tomorrow.

**Comment by Jacalz** [comment]
I have reverted it now. Should be good to go for a re-review :)

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
