### PR TITLE
Fix the logic error of rowColFromTextPos in Backspace

### PR DESCRIPTION
**Pull request by jorzion**
### Description:

https://github.com/fyne-io/fyne/pull/2723#issuecomment-1006180620

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

### CODE REVIEW

**Comment by jorzion** [comment]
If you have a better solution, please close this merge request.

**Comment by Jacalz** [comment]
Does this in some way replace #2726?

**Comment by jorzion** [comment]
The PR should have been submitted twice, but the unexpected result became the result of submitting two PRs in one submission action.

> Does this in some way replace #2726?

**Comment by jorzion** [comment]
As long as the problem can be solved, the others are not important. :)

**Comment by nullst** [comment]
Does this fix #2698 ? Seems to be related. Sorry, can't check it myself right now.

**Comment by jorzion** [comment]
> Does this fix #2698 ? Seems to be related. Sorry, can't check it myself right now.

Yes, It seems to be the same problem.

**Comment by andydotxyz** [comment]
> The PR should have been submitted twice, but the unexpected result became the result of submitting two PRs in one submission action.

I'm not sure what that means - should the older PR be replaced?
This includes commits from the older PR but also additional ones, I think we are not sure which should be reviewed for which fix.

**Comment by Jacalz** [comment]
Any update on the above comment @jorzion? I'm sorry to have to bump this but I think we should try to squeeze this in for the next bug fix release.

**Comment by andydotxyz** [comment]
It looks like between #2726 and the newer #2698 this PR is redundant. Sorry for picking up the latter, this PR seemed to have stagnated.

**Pull request closed without merging**
