### PR TITLE
Fix entry cursor animation

### LINKED ISSUE #1778: Cursor anim. sometimes distorts the text
### Describe the bug:

This bug seems to be sporadic and related  to the cursor animation, because it appeared when animation was added.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo.
2. Go to any tab with an Entry.
3. Write and delete quickly.

### Screenshots:

https://user-images.githubusercontent.com/12239342/104426037-662dff80-554f-11eb-9db5-c5b18b26a7a3.mp4

https://user-images.githubusercontent.com/12239342/104426055-6b8b4a00-554f-11eb-92b3-04957106917f.mp4

### Device (please complete the following information):
 - **OS:** MacOS 
 - **Version:** 10.15.4 Catalina 
 - **Go version:** 1.15.6 
 - **Fyne version:** develop @ ee882d72

### PR DESCRIPTION
**Pull request by fpabl0**
### Description:

This PR is based on the chat call (12/02/2021) and the discussion on #1779.

> Cursor should be static when user is interacting with the Entry.
> #1778 appears, because fade animation is running when user is typing.

#1956 should be landed first to avoid memory leaks.

Fixes #1778

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] #1956 landed

### CODE REVIEW

**Comment by PresleyHank** [comment]
when I container.NewVSplit then I click the maximize window button, and then click Restore, the interference line of the table will appear in the MultiLineEntry，How to fix it ,thanks you time.：）

**********************************************************
	tabVSplitEntry := container.NewVSplit(
		table1,
		multiLineEntry1,
	)

**********************************************************
I have tried as follows:
table1.Refresh()
multiLineEntry1.Refresh()

But the Interference line still appear

**Comment by andydotxyz** [comment]
Please open a new issue for this @PresleyHank

**Comment by andydotxyz** [comment]
@fpabl0 Sorry I forgot about this! I think the dependency is merged, what else needs to be done?

**Comment by andydotxyz** [comment]
Sorry for the delay on merging the dependency, I think this is unblocked now @fpabl0.

**Comment by fpabl0** [comment]
> Sorry for the delay on merging the dependency

No worries :)

>  I think this is unblocked now

Yes, it is 👍

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
