### PR TITLE
Deprecate fileicon selection

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:

Just adding a deprecation notice for now.
Not really useful until we have selection colour.
The wording can probably be a bit better. Feel free to come with better ideas.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by stuartmscott — APPROVED** [review]
Thanks Jacob!

Can you add a bug to the milestone so we don't forget to remove it in the next major release?

**Comment by stuartmscott** [comment]
Test failures are unrelated (@andydotxyz those pesky Form Hint tests again)

```
--- FAIL: TestForm_Hints (0.22s)
    util.go:47: 
        	Error Trace:	util.go:47
        	            				test.go:38
        	            				form_test.go:152
        	Error:      	Not equal: 
        	Test:       	TestForm_Hints
        	Messages:   	Image did not match master. Actual image written to file://D:\a\fyne\fyne\widget\testdata\failed\form\hint_initial.png.
    util.go:47: 
        	Error Trace:	util.go:47
        	            				test.go:38
        	            				form_test.go:155
        	Error:      	Not equal: 
        	Test:       	TestForm_Hints
        	Messages:   	Image did not match master. Actual image written to file://D:\a\fyne\fyne\widget\testdata\failed\form\hint_invalid.png.
    util.go:47: 
        	Error Trace:	util.go:47
        	            				test.go:38
        	            				form_test.go:158
        	Error:      	Not equal: 
        	Test:       	TestForm_Hints
        	Messages:   	Image did not match master. Actual image written to file://D:\a\fyne\fyne\widget\testdata\failed\form\hint_valid.png.
```

**Comment by Jacalz** [comment]
I kicked the tests. Hopefully they will complete now.

**Comment by Jacalz** [comment]
> Can you add a bug to the milestone so we don't forget to remove it in the next major release?

Good idea. Will crate an issue with notes about all the deprecated things that should be removed for 3.0. We can tag that for the milestone and update it with new deprecations as we go.

**Comment by andydotxyz** [comment]
I wasn’t sure what “Not really useful until we have selection colour.” means in the description

**Comment by Jacalz** [comment]
> I wasn’t sure what “Not really useful until we have selection colour.” means in the description.
> I’m not sure if we should deprecate methods that don’t yet have a replacement...

Yeah, I just meant that there was no replacement for it yet.

**Comment by Jacalz** [comment]
Created https://github.com/fyne-io/fyne/issues/2202. Will add this one once it lands.

**Comment by stuartmscott** [comment]
I think Focus colour is currently being used in place of the future Selection colour

**Comment by Jacalz** [comment]
What is the path forward for this? Should we leave it hanging until the focus colour changes are in?

**Comment by Jacalz** [comment]
Discussed on the call today. We should let this be until the changes to selection color changes are in. Are you working on that? @stuartmscott

**Comment by andydotxyz** [comment]
I would think this could be re-applied after #2296 - but I can't reopen it, possibly because the branch was removed?

**Comment by Jacalz** [comment]
Yeah, it is most likely possible to re-open this. Might have to open a new one, if you don't want to include the change in that PR?

**Comment by andydotxyz** [comment]
Happy to include it in the open PR :)

**Comment by andydotxyz** [comment]
Does this work @Jacalz ? https://github.com/fyne-io/fyne/pull/2296/commits/fa27918054acc35ac649bca8e101473a8d1bbb26

**Comment by Jacalz** [comment]
That's perfect 👍

**Pull request closed without merging**
