### PR TITLE
Add user-resizable columns and rows by dragging the separators in headers

### PR DESCRIPTION
**Pull request by andydotxyz**
A few things still to do - this draft is open for feedback on completed items so far:

- [x] Indication of user input option through cursor
- [x] Support the drag interaction to resize
- [x] Add appropriate tests

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Completed for sticky headers... Not yet in for the in-line headers.
Will come back to this following Slack chat about whether we could just set all headers to be sticky? :)

**Comment by andydotxyz** [comment]
As decided in the call today we will land this and remove non-sticky headers in a follow-up PR

**Comment by Bluebugs** [comment]
I got a crash with the following backtrace, but I can't quite reproduce it:
```
fyne.io/fyne/v2/widget.(*tableCellsRenderer).MinSize(0xc0018d2000)
	/home/cedric/go/src/fyne.io/fyne/widget/table.go:944 +0x1d8
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0xc00014a7e0?)
	/home/cedric/go/src/fyne.io/fyne/widget/widget.go:90 +0x2e
fyne.io/fyne/v2/internal/widget.(*scrollContainerRenderer).Layout(0xc001b7e720, {0x442fe19a, 0x43b01800})
	/home/cedric/go/src/fyne.io/fyne/internal/widget/scroller.go:276 +0x48
fyne.io/fyne/v2/internal/driver/common.updateLayout({0xdabb20?, 0xc00014a7e0})
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/canvas.go:535 +0xd4
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0xc0000c0ea0)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/common/canvas.go:111 +0x18d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:199 +0x35
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003d9180?, 0xc0004e3e30)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/window.go:907 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0021370c0?, 0x1?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:198 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc0004e3f90?)
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:106 +0x1ac
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:254 +0x1d4
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/home/cedric/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:230 +0xea
```

Also when you start a drag and move over enough to go over another column, it automatically pick that other one and start moving it. It feels a bit strange. If you also go off window with the mouse, it stop moving, but when you come back it start moving again which lead to very large movement which don't feel natural.

**Comment by andydotxyz** [comment]
> Also when you start a drag and move over enough to go over another column, it automatically pick that other one and start moving it. It feels a bit strange.

I cannot replicate this - it continues to resize the initial column if it gets so big to be over another one.
How did you make that happen?

> If you also go off window with the mouse, it stop moving

I cannot replicate this either - when I drag and leave the window it continues to resize (Linux and macOS anyhow)

**Comment by andydotxyz** [comment]
> I got a crash with the following backtrace, but I can't quite reproduce it:

It seems to be missing the top line where it says what sort of problem was encountered - the line refers to a map lookup with an OK check. This is also inside a property lock, so I can't see what error can occur.

Are you definitely running `8eab3a1`? I can't seem to replicate the issues on any computer.

**Comment by Bluebugs** [comment]
> > I got a crash with the following backtrace, but I can't quite reproduce it:
> 
> It seems to be missing the top line where it says what sort of problem was encountered - the line refers to a map lookup with an OK check. This is also inside a property lock, so I can't see what error can occur.

Is it possible that anything before accessing the map could be no nil?

> Are you definitely running `8eab3a1`? I can't seem to replicate the issues on any computer.

Certain of that.

**Comment by andydotxyz** [comment]
> Is it possible that anything before accessing the map could be no nil?

I couldn't see anything obvious - unfortunately without the cause line I don't know what I am looking for, could be nil / bad data / concurrent.

**Comment by andydotxyz** [comment]
Following the chat on Slack I can replicate the other items

**Comment by Bluebugs** [comment]
> > Is it possible that anything before accessing the map could be no nil?
> 
> I couldn't see anything obvious - unfortunately without the cause line I don't know what I am looking for, could be nil / bad data / concurrent.

From memory, I think it was nil.

**Comment by andydotxyz** [comment]
Fixed the issue where it jumped to other drag handles.
Not sure about the move-past-min-then-back stretching issue, this issue is present in `Split` as well.
Not sure exactly what this fix is, and whatever it should be applied to both at the same time.

**Comment by andydotxyz** [comment]
> > > Is it possible that anything before accessing the map could be no nil?
> > 
> > 
> > I couldn't see anything obvious - unfortunately without the cause line I don't know what I am looking for, could be nil / bad data / concurrent.
> 
> From memory, I think it was nil.

It shouldn't be possible, because it is protected a few lines earlier with `if len(r.cells.t.columnWidths) == 0`

**Review by Bluebugs — APPROVED** [review]
Works great for me.

**Pull request merged**
