### PR TITLE
PasswordEntry created from entry with Password = true has no revealer

### LINKED ISSUE #593: PasswordEntry created from entry with Password = true has no revealer
**Describe the bug**
If a password entry is made by creating a regular entry and then setting `yourEntryVar.Password = true`, results in a password entry that has no password revealer. You just get a regular entry, but with hidden symbols instead of text.

**To Reproduce**
Look at the example code below. The first widget is created using `widget.NewPasswordEntry()` and the second one is created with the widget.Entry type and then made in to a PasswordEntry.

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()

	window := app.NewWindow("Example")

	good := widget.NewPasswordEntry()

	bad := &widget.Entry{Password: true}

	window.SetContent(fyne.NewContainerWithLayout(layout.NewGridLayout(1), good, bad))

	window.ShowAndRun()
}
```

**Screenshots**
image

**Device (please complete the following information):**
 - OS: Solus (A Linux Distro)
 - Version: Version 4 with Linux Kernel 5.3.18
 - Go version: 1.13.5
 - Fyne version: 1.2.1

### PR DESCRIPTION
**Pull request by lucor**
Fixes #593

**Checklist**

- [x] Tests included
- [x] Lint and formatter run with no errors
- [x] Tests all pass

(where applicable)

- [ ] Public APIs match existing style
- [ ] Any breaking changes have a deprecation path or have been discussed

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks this is a good fix - but what happens if Password is then set to false? :)

**Comment by lucor** [comment]
Right :-) The fix was only to have behaviours aligned between the two initialization ways (struct and constructor).
Wondering if it is now a good time to deprecate the Password field in favour of the NewPasswordEntry constructor as discussed some time ago on slack.

**Comment by andydotxyz** [comment]
Yes you are probably right - too much hassle for maintaining an old fix.
If we are moving that way then perhaps also shift to the PasswordEntry type so that it can be easily extended through composition too?

**Comment by andydotxyz** [comment]
Can you add that to this PR as well @lucor so we wrap it up in one go?

**Pull request merged**
