### PR TITLE
Fix custom shortcuts with fyne.KeyTab

### LINKED ISSUE #3087: Custom shortcuts with fyne.KeyTab is not working
### Describe the bug:

I have noticed that using `fyne.KeyTab` doesn't work when using the `desktop.CustomShortcut` type. My idea is that something with our handling of tabs is treating the window canvas as not accepting tabs. Other buttons seem to be working fine on my end.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code below.
2. Press Ctrl + Tab on keyboard.
3. Notice that nothing happens.
4. Press Ctrl + Space on keyboard.
5. Notice that it works.

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
)

func main() {
	a := app.New()
	w := a.NewWindow("Custom Shortcut")

	ctrlTab := &desktop.CustomShortcut{KeyName: fyne.KeyTab, Modifier: fyne.KeyModifierControl}
	w.Canvas().AddShortcut(ctrlTab, func(shortcut fyne.Shortcut) {
		println("We tapped Ctrl+Tab")
	})

	ctrlSpace := &desktop.CustomShortcut{KeyName: fyne.KeySpace, Modifier: fyne.KeyModifierControl}
	w.Canvas().AddShortcut(ctrlSpace, func(shortcut fyne.Shortcut) {
		println("We tapped Ctrl+Space")
	})

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:**  Fedora Linux
 - **Version:**  35 with kernel 5.17.14
 - **Go version:**  1.16.15
 - **Fyne version:**  2.2.1

### PR DESCRIPTION
**Pull request by edwinclement08**
### Description:
Earlier all keypresses that had Tab in them were excluded from the normal shortcut handling process.
With this PR, only Tab & Shift+Tab are afforded that exclusion, all others will be routed through the `triggersShortcut` flow

Fixes #3087

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
Thanks for opening this PR. Would you mind checking this to target the `develop` branch? All PRs should, per the PR template, torget that and not master.

**Comment by edwinclement08** [comment]
Oh, didn't know that. Will do that.

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks a lot for this. This is working great for solving my issues. It would just be good if you could add some tests to make sure that this is working correctly. You can have a look at the `window_test.go` for how the existing ones are implemented :)

**Comment by andydotxyz** [comment]
Just FYI we are looking to put a release together this week - it would be great to land this if we can!

**Comment by edwinclement08** [comment]
Just FYI, there are a couple of broken test cases already:
```
--- FAIL: TestGlCanvas_ChildMinSizeChangesInDifferentScrollAffectAncestorsUpToScroll (0.34s)
--- FAIL: TestWindow_MinSize_Fixed (0.05s)
--- FAIL: TestWindow_HandleOutsideHoverableObject (0.67s)
--- FAIL: TestWindow_SetPadded (1.39s)
--- FAIL: TestWindow_SetPadded/window_with_menu_without_padding (0.36s)
--- FAIL: TestWindow_SetPadded/window_with_menu_and_padding (0.34s)
--- FAIL: TestWindow_SetFullScreen (0.08s)
```

The way I ran the test is `cd internal\driver\glfw` and then run `go test`. I am not sure if the failures are due to me running it incorrectly.

[temp2.log](https://github.com/fyne-io/fyne/files/10665465/temp2.log)

**Comment by andydotxyz** [comment]
The window size tests can be temperamental and we've never figured out why. Probably not a new issue...

**Comment by edwinclement08** [comment]
Added testcases, @Jacalz

**Review by andydotxyz — APPROVED** [review]
Great fix and tests, thanks

**Pull request merged**
