### PR TITLE
Fix for #2222, and #2220 for buttons

### LINKED ISSUE #2220: Themed resources are drawn with the wrong colors if a theme's Color() method returns certain types of Colors
### Describe the bug:
I've written a fix for this, and a bunch of tests. (I'm also going to make a pull request after posting this)

Fyne displays incorrect colors in PrimaryThemedResources (such as checkboxes) which are SVGs, when a theme's Color method returns an RGBA64, NRGBA64, RGBA with 0<a<0xff, NRGBA with 0<a<0xff, Alpha16, Gray16, or any custom Color implementation where the least significant byte of each component returned by RGBA() is not equal to the most significant byte. The correct colors are only shown with RGBA with a=0 or a=0xff, Alpha, or Gray, and those only appear correct because their RGBA() method simply clones each 8 bit component of the color into both the high and low byte of the 16 bit output components (Go's (color.RGBA) RGBA() returns r<<8|r, g<<8|g, b<<8|b, a<<8|a, where r is uint32(c.R), etc). The reason it gives incorrect colors when 0<a<0xff for RGBA and NRGBA is because of the alpha-premultiplication (RGBA has it built into the components, unless an RGBA is incorrectly constructed without it, and NRGBA's RGBA() multiplies the alpha into the r, g, and b return values), and theme/svg.go's colorToHexAndOpacity's current code is written as if it expects RGBA() to return non-alpha-premultiplied values (it doesn't remove the alpha-premultiplication) whose most significant byte matches their least significant byte (it doesn't >>8 the return values from RGBA() before casting them to bytes).

I also found the same problem in other places in Fyne's code:
- dialog/base.go's themedBackgroundRenderer's Refresh()
- test/markup_renderer.go's markupRenderer's setColorAttrWithDefault
- test/markup_renderer.go's rgbaColor
- widget/button.go's buttonColor() (which appears to have another issue as well, which I'll have to make a separate issue about)

I noticed this because I was returning an (opaque) NRGBA64 from a custom Theme's Color method. I have a video of that below.

(When I looked into this, I found out that svgs can't support 64 bit colors anyways, but this still seems like a bug worth fixing, especially since not all resources are SVGs, and there's other code with the same problem that doesn't use SVGs.)

### To Reproduce:
Steps to reproduce the behaviour:
1. Colorize a resource with NRGBA64{R: 0xff00, G: 0xffff, B: 0x00ff, A: 0xffff}.
2. Draw it.
3. It looks cyan when it should look yellow.
4. Do it again but give it an alpha value of 0x7fff.
5. It looks like a translucent light green color when it should look like a translucent yellow color.

### Video:
In this video, I change the value of an NRGBA64 color returned by a theme by dragging a hue slider (which goes from 0 to 360). The color created is opaque, and generated from converting HSL to RGB. You can see everything in the window change at the correct rate except the checkbox, which changes much more quickly because colorToHexAndOpacity is calling RGBA() and using the least significant byte of R, G, and B, instead of the most significant byte.
https://user-images.githubusercontent.com/6283593/116925385-20dd2d00-ac27-11eb-92d5-7a2c74528cfd.mp4

### Example code:
These are two of the subtests I added to theme/icons_test.go's TestColorizeResource. If colorToHexAndOpacity was working correctly, the first would be #ffff00, and the second would be #ffff00 with 50% alpha. Instead, the first is #00FFFF, and the second is #7fff7f with 50% alpha.
```go
		"NRGBA64": {
			svgFile: "circles.svg",
			color:     color.NRGBA64{R: 0xff00, G: 0xffff, B: 0x00ff, A: 0xffff},
			wantImage: "colorized/circles_yellow.png",
		},
		"translucent NRGBA64": {
			svgFile:   "circles.svg",
			color:     color.NRGBA64{R: 0xff00, G: 0xffff, B: 0x00ff, A: 0x7fff},
			wantImage: "colorized/circles_yellow_translucent.png",
		},
```

### Device (please complete the following information):
 - **OS:** Windows 10 Pro
 - **Version:** 20H2
 - **Go version:** 1.16.3 windows/amd64
 - **Fyne version:** 083f0344089df647ed3a2e33b8b77e0972b75517 (which is the last commit on the develop branch at time of writing)

### LINKED ISSUE #2222: buttonRenderer's buttonColor can generate out of range alpha values when hovered (might affect RGB too?)
### Describe the bug:
The math in widget/button.go's buttonRenderer's buttonColor() for color calculations while hovering appears to be very wrong (in addition to being affected by #2220), but I'm not sure what it is actually trying to do.

At present it is doing this when a button is hovered:
```go
		bg := theme.ButtonColor()
		if r.button.Importance == HighImportance {
			bg = theme.PrimaryColor()
		}
		dstR, dstG, dstB, dstA := bg.RGBA()
		srcR, srcG, srcB, srcA := theme.HoverColor().RGBA()
		srcAlpha := float32(srcA) / 0xFFFF
		dstAlpha := float32(dstA) / 0xFFFF
		targetAlpha := 1 - srcAlpha*dstAlpha
		outAlpha := srcAlpha + targetAlpha
		outR := (srcAlpha*float32(srcR) + targetAlpha*float32(dstR)) / outAlpha
		outG := (srcAlpha*float32(srcG) + targetAlpha*float32(dstG)) / outAlpha
		outB := (srcAlpha*float32(srcB) + targetAlpha*float32(dstB)) / outAlpha
		return color.RGBA{R: uint8(uint32(outR) >> 8), G: uint8(uint32(outG) >> 8), B: uint8(uint32(outB) >> 8), A: uint8(outAlpha * 0xFF)}
```

The problem here is that the math doesn't make any sense, even if it's accounting for premultiplication (I'm not sure if it is or not). You can see that if you just look at what's going on with the alpha values:
Let's assume srcA=51, dstA=204.
srcAlpha will be 0.2, and dstAlpha will be 0.8.
targetAlpha = 1 - 0.2 \* 0.8 = 0.84
outAlpha = 0.2 + 0.84 = 1.04
The alpha value that is used in the new color.RGBA will be uint8(1.04\*0xFF).
1.04\*0xFF is 265.2, or 0x109, and so when it's cut off to just 8 bits, the color.RGBA will have an alpha value of 0x09, which is equivalent to if outAlpha had been 0.035.

So that seems like an obvious bug, but less obvious is what the code is *supposed* to be doing.
I checked all the other things that can be hovered, but they pretty much all just set their color to HoverColor. This seems to be something new.

(This doesn't even get into how the alpha calculations may be screwing up the colors too - they'd be screwed up anyways from just having alpha due to #2220, which I haven't fixed for this method)

### To Reproduce:
Steps to reproduce the behaviour:
1. If you want to see it visually, try creating a theme whose background color is 0xff0000, button color is 0x00ff00 with alpha 204, and hover color is 0x0000ff with alpha 51, and a window with a button on it that you can move the mouse over to see what happens. Given that #2220 also applies, the results will probably be confusing. Also you can't actually see the alpha values this way, you'd have to try to infer them, which would be difficult given that the color values won't necessarily make any sense either...

### Device (please complete the following information):
 - **OS:** Windows 10 Pro
 - **Version:** 20H2
 - **Go version:** 1.16.3 windows/amd64
 - **Fyne version:** 083f0344089df647ed3a2e33b8b77e0972b75517

### PR DESCRIPTION
**Pull request by AmanitaVerna**
### Description:
- Replaces the math used for blending the hover color in button.go's buttonRenderer's buttonColor() to fix #2222 and also to fix #2220 for buttonColor().
- Fixes #2220 in button.go's newButtonTapAnimation() as well.
- Adds a math-based test which uses an alternate way of calculating the same blending operation to test buttonRenderer's hover code against (TestButton_Hover_Math in button_internal_test.go)
- Updates the hover test image used by button_test.go's TestButton_Hover()

Fixes #2222, and also fixes the last cases of #2220 that I've found.

### Checklist:
- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass. (except when they randomly fail, but that's unrelated to this code. I saw it fail on table and list tests several times, fail to render a set of lines on tables once, and render the button icon in the wrong place once, and I have no idea why any of that is sometimes happening.)

### CODE REVIEW

**Comment by AmanitaVerna** [comment]
I missed some tests which weren't in widget or widget_test, which are expecting wrong RGB values (calculated the previous, incorrect, way) or images, and I'll have to fix those.

**Comment by andydotxyz** [comment]
Sorry but the history of this PR is more messed up than the last one. Are you branching from `master` by mistake?

**Comment by AmanitaVerna** [comment]
I took the develop branch I already had, merged upstream/develop into it, and then merged the button changes into it.

I should just delete the branch and recreate it, probably.

**Comment by andydotxyz** [comment]
It looks like your develop may not line up with our develop then.

I would recommend removing it and checking it out from the upstream.
You can then make a branch for your commits and open a PR from there.
For future PRs then just merge upstream into develop and branch off again.

**Pull request closed without merging**
