### PR TITLE
Guarantee widget.Form tracks all entry validation changes, fixes #1965

### LINKED ISSUE #1965: Form validation doesn't enable submit button
### Describe the bug:
When creating a form with entries that include validation methods, typing valid input into those entries does not enable the form's submit button. However, typing input, deleting that input, and then typing it again does enable the form's submit button

### To Reproduce:
Steps to reproduce the behaviour:
1. Create form with entries that include validation and an `OnSubmit` function
2. Render the form
3. Type valid input into the form's entries
4. Observe that the submit button stays disabled
5. Delete and then re-enter the valid input
6. Observe that the submit button is now enabled

### Screenshots:
formbug

### Example code:

Code from the above gif:

```go
username := widget.NewEntry()
username.SetPlaceHolder("username")
username.Validator = func(s string) error {
    if s == "" {
        return errors.New("please specifiy a username")
    }

    return nil

}

password := widget.NewPasswordEntry()
password.SetPlaceHolder("password")
password.Validator = func(s string) error {
    if s == "" {
        return errors.New("please specifiy a password")
    }

    return nil
}

rememberCheck := widget.NewCheck("Remember my password", nil)

form := widget.NewForm(
    widget.NewFormItem("Username", username),
    widget.NewFormItem("Password", password),
    widget.NewFormItem("", rememberCheck),
)

form.SubmitText = "Login"
form.OnSubmit = func() {
    username.Disable()
    password.Disable()
    rememberCheck.Disable()
    defer username.Enable()
    defer password.Enable()
    defer rememberCheck.Enable()

    success := pres.Login(username.Text, password.Text, rememberCheck.Checked)
    if success {
        onSucess()
    }
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10.0.19042
 - **Go version:** go1.15.8
 - **Fyne version:** v2.0.0

### PR DESCRIPTION
**Pull request by fpabl0**
### Description:

Fixes #1965 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
The bug fix looks good, but the resulting test images show an invalid state - two focused elements at once. I don't know that fixing this is in scope for the ticket, but we should not commit invalid test images, so perhaps a line or to for `Canvas.Focus()` might help in the meantime?

**Comment by fpabl0** [comment]
Yes, I am aware of it, sorry about that, I tried to unfocus them, but have no success.

> Canvas.Focus() might help in the meantime?

Oh, I will try with that, later today.

**Comment by fpabl0** [comment]
@andydotxyz Unfortunately, `Canvas.Focus()` didn't work, so I manually unfocused one entry, are now the test images looks good? Or should I unfocus both of them?

**Comment by andydotxyz** [comment]
> @andydotxyz Unfortunately, `Canvas.Focus()` didn't work, so I manually unfocused one entry, do now the test images look good? Or should I unfocus both of them?

Yeah that's OK for now. I suspect the focus issue requires a fix in the text code which we can look at separately.

**Review by andydotxyz — APPROVED** [review]
Looks good to me, though I would appreciate @Jacalz thoughts as well

**Review by Jacalz — APPROVED** [review]

**Pull request merged**
