### PR TITLE
Fix panic on NewTextGrid().Text()

### PR DESCRIPTION
**Pull request by jangler**
### Description:

See PR #1427, approved for master branch but had conflicts when base switched to develop.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Review by stuartmscott — APPROVED** [review]
Perfect, thanks @jangler!

**Comment by stuartmscott** [comment]
Go ahead and "Squash and Merge" your first contribution to Fyne!

**Comment by jangler** [comment]
Me? I don't have write access.

**Comment by stuartmscott** [comment]
Oh, my mistake, I thought you could merge as it was approved

**Comment by stuartmscott** [comment]
Thanks for the fix @jangler, hope to work with you again!

**Pull request merged**
