### PR TITLE
Make sure we have sufficient space for the bar as well if content is tiny

### LINKED ISSUE #3885: AppTabs has overlapping tabs in VBox or HBox
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

AppTabs has overlapping tabs in VBox or HBox;
After preliminary verification,
container.TabLocationTop, container.TabLocationBottom -->AppTabs has overlapping tabs in HBox

container.TabLocationLeading and container.TabLocationTrailing -->AppTabs has overlapping tabs in VBox

### How to reproduce

must appear

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("X2demo")

	searchEntry := widget.NewEntry()
	searchEntry.SetPlaceHolder("some message")

	tabs := container.NewAppTabs(
		container.NewTabItem("devices info", widget.NewLabel("Hello")),
		container.NewTabItem("mqtt ", widget.NewLabel("World!")),
	)
	tabs.Append(container.NewTabItemWithIcon("Home", theme.HomeIcon(), widget.NewLabel("Home tab")))
	tabs.SetTabLocation(container.TabLocationLeading)

	container := container.NewVBox(
		searchEntry,
		tabs,
		layout.NewSpacer(),
		widget.NewLabel("log info"),
	)

	myWindow.SetContent(container)
	myWindow.Resize(fyne.NewSize(800, 600))
	myWindow.ShowAndRun()
}
```

### Fyne version

2.3.4

### Go compiler version

1.19.3

### Operating system and version

win11

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #3885

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
It looks like some tests need to be adjusted

**Comment by andydotxyz** [comment]
> It looks like some tests need to be adjusted

Sorry about that, was away from the machine a couple days. Fixed now

**Review by Jacalz — CHANGES_REQUESTED** [review]
This PR does unfortunately seem to introduce various bugs with the showing and hiding of tabs. One thing I noticed is that the window sometimes becomes larger when selecting a different tab if there are tabs in the dropdown menu:

[Screencast from 2023-05-22 20-31-36.webm](https://github.com/fyne-io/fyne/assets/25466657/a8e93b13-b9cc-4e2d-9e74-e0a4503ad9c2)

I also noticed that you can't make the window smaller again if you make it large enough to show more tabs:

[Screencast from 2023-05-22 20-33-40.webm](https://github.com/fyne-io/fyne/assets/25466657/d03cac1d-70d7-4bd4-a971-dca5d83ed28d)

**Comment by andydotxyz** [comment]
Thanks for catching that, should be fixed now

**Review by Jacalz — COMMENTED** [review]
I still can't seem to make the window smaller if new tabs are shown.

**Review by Jacalz — APPROVED** [review]
Seems fine now. Thanks :+1:

**Pull request merged**
