### PR TITLE
Fix misuse of FileDirectory for FileDialog

### PR DESCRIPTION
**Pull request by codesoap**

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]
Thanks for this

**Comment by Jacalz** [comment]
It needs to be rebased on and target the develop branch

**Comment by codesoap** [comment]
@Jacalz sorry, I wasn't aware of the develop branch. Should be fixed now.

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
Personally I wouldn't have been too fussed with a documentation fix - if it lands on develop then it could be 4 months before the website gets updated (when the code merges for release).

**Comment by Jacalz** [comment]
I was merely thinking about the fact that the workflows were complaining

**Pull request merged**
