### PR TITLE
Add CurrentKeyModifiers API to desktop driver

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Comment by dweymouth** [comment]
The two 'update go.mod' commits undo each other and was from when I was trying to figure out how to use my own fork as fyne.io/fyne in my app :)

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Thanks for this. Your version TODO should be 2.4, as that is our next API update release in the current plans.


As for "Active" I think we use that in a different context (i.e. an active menu item).
I wonder if "Current" would be more consistent (like fyne.CurrentApp to AppTabs.CurrentTab)?
Alternatively just "KeyModifiers" could be considered, but I think that would read a little ambiguously...

**Comment by dweymouth** [comment]
> Thanks for this. Your version TODO should be 2.4, as that is our next API update release in the current plans.
> 
> As for "Active" I think we use that in a different context (i.e. an active menu item). I wonder if "Current" would be more consistent (like fyne.CurrentApp to AppTabs.CurrentTab)? Alternatively just "KeyModifiers" could be considered, but I think that would read a little ambiguously...

I think `CurrentKeyModifiers` is good. Updated.

**Comment by dweymouth** [comment]
Accidentally closed PR! meant to resolve Andy's comment

**Comment by dweymouth** [comment]
This is broken due to https://github.com/glfw/glfw/issues/1630, do not merge. I will see if I can come up with a fix

**Comment by andydotxyz** [comment]
Well noticed.
I think if you look at some of our tests there is a related comment / workaround internally but I can't find it right now.

**Comment by andydotxyz** [comment]
I think something has gone wrong with the git history here... 140 commits got added today

**Comment by dweymouth** [comment]
Yeah you're right- I merged this into the base branch for my project but it messed up the history. I think I'll just close this PR and start it afresh.

I really wish GitHub would allow you to fork a repo twice so I could keep things separate more easily, though maybe I'm not using git as effectively as I could be

**Comment by andydotxyz** [comment]
Multiple branches (one per PR) is often the easiest way

**Comment by dweymouth** [comment]
Reopened as https://github.com/fyne-io/fyne/pull/3772

**Pull request closed without merging**
