### PR TITLE
List Selection

### PR DESCRIPTION
**Pull request by stuartmscott**
### Description:
Updates the List Selection API to match #1395

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
I'll leave @okratitan to do the review, but I wanted to add some thoughts:

From the demo code II am pleased to see that this reads more cleanly.
However I think it still suffers from the struct-initialising 0 != -1 issue that we discussed?

**Comment by stuartmscott** [comment]
> still suffers from the struct-initialising 0 != -1 issue that we discussed

yes, I'll update to use a slice. In future with multi select it may become a performance issue to iterate the slice for each list item, so we could consider switching to a map, but slice should be fine for now.

**Comment by stuartmscott** [comment]
> From the demo code II am pleased to see that this reads more cleanly.

Me too, tho the code below will never be called as the list has 125 pre-selected, and there is no way to unselect

```go
list.OnUnselected = func(id widget.ListItemID) {
	label.SetText("Select An Item From The List")
	icon.SetResource(nil)
}
```

**Comment by andydotxyz** [comment]
> effect of the code below will never be seen

But unselecting to select a new one is still going to execute the same callback right?

**Comment by stuartmscott** [comment]
It will be called, but the label's text will be replaced soon after by the select callback, thus the user will never see "Select An Item From The List"

**Comment by andydotxyz** [comment]
Kicked travis, looks like random error

**Comment by stuartmscott** [comment]
Looks like another random error:
```
--- FAIL: TestEntry_SelectSnapLeft (0.10s)
    util.go:47: 
        	Error Trace:	util.go:47
        	            				test.go:32
        	            				entry_test.go:1048
        	Error:      	Not equal: 
        	Test:       	TestEntry_SelectSnapLeft
        	Messages:   	Image did not match master. Actual image written to file:///home/travis/gopath/src/fyne.io/fyne/widget/testdata/failed/entry/selection_initial.png.
```

**Review by okratitan — APPROVED** [review]

**Pull request merged**
