### PR TITLE
Add locking to Button

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Add locking to Button for thread safety

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
Should the renderer not use the lock when reading properties like Accordion does?

**Comment by dweymouth** [comment]
> Should the renderer not use the lock when reading properties like Accordion does?

I think it does? The read lock is held for the duration of buttonRenderer.Refresh and for the second half of Layout when it accesses button properties, and also in CreateRenderer of the button.

**Comment by Jacalz** [comment]
> I think it does? The read lock is held for the duration of buttonRenderer.Refresh and for the second half of Layout when it accesses button properties, and also in CreateRenderer of the button.

It is not held during MinSize from what I can see.

**Comment by dweymouth** [comment]
> > I think it does? The read lock is held for the duration of buttonRenderer.Refresh and for the second half of Layout when it accesses button properties, and also in CreateRenderer of the button.
> 
> It is not held during MinSize from what I can see.

The renderer MinSize function actually doesn't read any properties from the button struct. We could add a lock to the renderer but I think Fyne actually calls renderer methods single-threaded, if I understand correctly.

**Pull request merged**
