### PR TITLE
fix: Problem displaying some svg files #2864

### LINKED ISSUE #2864: Problem displaying some svg files
### Describe the bug:

Displaying a number of svg images from the internet within a fyne app, most display without issue, some produce errors on the console but display without issue others produce an error on the console and produce no image on screen.
Error logged is as follows:
Fyne error:  SVG Load error:
Cause: Param mismatch
At: /src/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/painter/image.go:78

### To Reproduce:

svg file attached that generates the error and doesn't display as per the following screenshot.

### Screenshots:

The problem can been seen with horse number 7.
image

### Example code:

```go
silk *canvas,Image
uri,err:=fyne.LoadResourceFromURLString("http://176.58.114.32:8091/silks?s=60859")
if err==nil	{
	silk.Resource=uri 
}	else 	{
	log.panic(" ParseURI failed ",err, " Setting to NR")
}
			
```

### Device (please complete the following information):
 - **OS:**  Windows 
 - **Version:** 10 
 - **Go version:**  1.17.7 windows/amd64
 - **Fyne version:** 2.1.4

### PR DESCRIPTION
**Pull request by cedy**
### Description:

Fixes #2864
SVGs resources with some bad elements would not display, because oksvg library would error on bad elements. https://github.com/srwiley/oksvg/commit/dd853b67852cb6a521b588c2d501517771324d9e adds logic in oksvg to ignore such errors. This PR updates oksvg to the latest version and adds a test that exposes the bug. 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

~TestColorDialog_Theme fails for me locally on develop (b71c0f2e5ab70eefa34e6a0b9a1643ffbaa68915) as well =/~ works with 1.17
#### Where applicable:

- [x] Updated the vendor folder (using `go mod vendor`).

### CODE REVIEW

**Comment by Jacalz** [comment]
Woolf you mind updating the PR description to say which issue it fixes? As well as giving a short description (perhaps linking to the upstream commit in oksvg)?

**Comment by andydotxyz** [comment]
The dialog colour problem has been identified and is in a PR so should land soon. To work around it you can use Go 1.17 locally, as the issue seems to be triggered by 1.18 somehow.

**Comment by cedy** [comment]
> Woolf you mind updating the PR description to say which issue it fixes? As well as giving a short description (perhaps linking to the upstream commit in oksvg)?

I've put it in the title, in the branch name, but forgot to put it in the most important place, where it actually required :) Fixed, thanks! Also added some description and reference to oksvg commit.

**Comment by cedy** [comment]
**TestForm_Disabled* fails on some platforms, but I can't reproduce it :(  here https://github.com/fyne-io/fyne/actions/runs/2771629944 it failed on platform ubuntu 1.17, same code force-pushed failed on ubuntu 1.14 https://github.com/fyne-io/fyne/actions/runs/2771706878 and mobile 1.17 https://github.com/fyne-io/fyne/actions/runs/2771706877

**Review by andydotxyz — APPROVED** [review]
Great, thanks

**Pull request merged**
