### PR TITLE
Don't allocate new slices on each animation tick

### LINKED ISSUE #4445: Animation runner allocates new slices every frame
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When animations are running, the animation runner allocates a new slice of active animations 60 times a second [here](https://github.com/fyne-io/fyne/blob/master/internal/animation/runner.go#L73). This leads to a lot of work for the garbage collector and possibly increased system memory use of Fyne apps.

### How to reproduce

Run any app that has animations. This is not really a bug though but a ticket to track implementing memory optimizations in the animation runner.

### Screenshots

_No response_

### Example code

n/a

### Fyne version

2.4.2

### Go compiler version

n/a

### Operating system and version

n/a

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Another try at fixing the excess allocations in the animation runner in a simpler way than #4451, with no public API change. This does not address the non-idempotency of starting an animation (one can still be started twice), but aims only to avoid the performance penalty of allocating slices every tick.

Fixes #4445 

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]
Thanks

**Comment by Jacalz** [comment]
Starting a goroutine allocates memory as well. Have you benchmarked that this improves performance?

**Comment by dweymouth** [comment]
> Starting a goroutine allocates memory as well. Have you benchmarked that this improves performance?

No, though I was operating under the assumption that since animations tick 60 times a second, the number of ticks will vastly outnumber the number of Stop calls, so worse Stop performance was acceptable. The other PR I have in draft for 2.5 would overall be a better solution, though it still has some unresolved issues

**Comment by Jacalz** [comment]
Oh yeah, you are absolutely right there. Benchmarking is very important though and I think we ought to do so for any non-trivial optimizations. If not doing so for making sure that we don't accidentally regress, then do it  to make me excited for the nice improvements ;)

You can leave it this time though since it's already merged and I agree that you are right with your statement :)

**Pull request merged**
