### PR TITLE
Introduce `onPrimary` color for better contrast of text and icons on the primary color

### LINKED ISSUE #2469: Ability to change the text color of the button
### Is your feature request related to a problem? Please describe:
I want to create a custom dialog with the following design: 
Screenshot from 2021-09-14 15-34-06

But I am not able to change the foreground color of the button in the dialog box:
The design I am able to achieve by changing the background color of all the buttons as: 
Screenshot from 2021-09-14 15-30-38

(The blur entry field is not the feature provide by fyne I have used  image editing for it for privacy reasons)
But I not able to change the color of the text in the button without changing the Foreground color of entire theme.

https://gophers.slack.com/archives/CB4QUBXGQ/p1631614154106500?thread_ts=1631610434.092900&cid=CB4QUBXGQ

### Describe the solution you'd like to see:

Ability to change the foreground color of the button without changing the foreground color of entire theme.

### PR DESCRIPTION
**Pull request by toaster**
### Description:

The material design defines “on” colors in its [color roles](https://m3.material.io/styles/color/roles).
This PR introduces the first “on” color: `onPrimary`

This helps to improve the contrast on important buttons.

This probably fixes #2469. Not in the generic way that the creator might have intended but in a way compatible to Fyne.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Comment by Jacalz** [comment]
Nice idea. I think this might fix https://github.com/Jacalz/rymdport/issues/115 as well.

**Comment by toaster** [comment]
> ~Nice idea. I think this might fix [Jacalz/rymdport#115](https://github.com/Jacalz/rymdport/issues/115) as well.~ EDIT: No, it does not 🙃

I hope, it’s a nice idea nevertheless 😆.

**Comment by Jacalz** [comment]
Yes, indeed. The improved contrast is noticeable even by just looking at test images :)

**Comment by toaster** [comment]
Please ignore the “*master images*” commits at the end. It seems that a rendering glitch is also present when running Linux on Apple silicon. The output then differs from MacOS/ARM as well as Linux/x86 😞.

**Comment by toaster** [comment]
I will remove these commits soon.

**Review by andydotxyz — APPROVED** [review]
Thanks, that is clearer :)

**Pull request merged**
