### PR TITLE
Improve url input checking to only get valid urls

### PR DESCRIPTION
**Pull request by Jacalz**
### Description:
This fixes a potential security issues reported by gosec (now down to 19).
We are now actually verifying the url to make sure that it is valid before sending the http request.

Partial fix for #742 

### Checklist:

- [ ] Tests included.
  - Might add more tests for these functions in a future PR.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [-] Public APIs match existing style.
- [-] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by pymq** [comment]
I am sorry @Jacalz , but it seems like url.Parse is already called under the hood in [request.go#L854](https://github.com/golang/go/blob/master/src/net/http/request.go#L854) so extra parsing -> String() is unnecessary

**Comment by Jacalz** [comment]
> I am sorry @Jacalz , but it seems like url.Parse is already called under the hood in [request.go#L854](https://github.com/golang/go/blob/master/src/net/http/request.go#L854) so extra parsing -> String() is unnecessary

Alright. Everywhere I read online suggested that url strings should be verified this way, but they might not be using http.Get(). Do you have a better suggestion to do this then?

**Comment by Jacalz** [comment]
It looks like url.ParseRequestURI() is much more strict with checking this, but ain’t don’t really know how this would be solved otherwise.

**Comment by pymq** [comment]
> It looks like url.ParseRequestURI() is much more strict with checking this, but ain’t don’t really know how this would be solved otherwise.

You had any issues with how plain `url.Parse` validate urls?
As I see from docs `url.ParseRequestURI` is intended for use on a server side, to process incoming HTTP requests.
So I think `url.Parse` should be enough, as it is used in stdlib.

**Comment by Jacalz** [comment]
Yeah, I guess so. The whole issues is that gosec complains about using http.Get() with a variable and that it apparently something you should avoid 🤷‍♂️

**Pull request closed without merging**
