### PR TITLE
Add locking to Hyperlink

### PR DESCRIPTION
**Pull request by dweymouth**
### Description:

Protects access to hyperlink.Text and hyperlink.Url which are not safe to access concurrently.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
Should the renderer not use the lock when reading properties like Accordion does?

**Comment by dweymouth** [comment]
> Should the renderer not use the lock when reading properties like Accordion does?

Good catch. Added renderer locking.

**Review by andydotxyz — DISMISSED** [review]
Thanks for this!

**Review by Jacalz — CHANGES_REQUESTED** [review]
This seems to deadlock when going the welcome screen in `fyne_demo`.

**Comment by dweymouth** [comment]
Ah, bad merge I guess. Will take a look.

**Review by Jacalz — APPROVED** [review]

**Pull request merged**
