### PR TITLE
Sticky rows and columns for table

### LINKED ISSUE #3594: Extending table capabilities
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Its more of a suggestion, https://github.com/fyne-io/fyne/issues/1658 here is a request for table headers, i want to expand on this.

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

At the moment table has very basic functionality, extending this would make table widget much more usable and enjoyable.
In the issue that i [linked](https://github.com/fyne-io/fyne/issues/1658)  there is request for the headers, i will expand on this a bit : 

1) Columns should be able to be pinned 

2)Rows should be able to be pined 
(pinning a row, makes further scrolling down the table possible, while not losing the focus of current row ) same for column
especially usefull when there are a lot of rows/columns and we must scroll

3)Rows should be able to be marked somehow (different color, it would make searching and comparing data easier,)
(example, all rows containing X value in column Y should be red)

4)Sorting of the table out of the box

5)Clicking on cell in a row should Highlight whole row, this makes following the row with your eyes much easier, and less error prone,

6)Pagination (scrolling table is great, but with larger amount of data pagination is much more useful)

### PR DESCRIPTION
**Pull request by andydotxyz**
Add freezing / sticking of a number of table cells or rows. With headers turned on the first row/col will be counted.

Show header row and col, set sticky row and col to 2 and you get sticky headers and 1 row /col of stuck data.

A new function `NewTableWithHeaders` was added to show headers with default content and stick them as well.

TODO:

- [x] Add some sticky tests
- [x] Fix graphical glitches with separators and hover effects
- [x] Make the sticky columns respond to hover/select

Fixes #3594

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style and have Since: line.

### CODE REVIEW

**Comment by andydotxyz** [comment]
I think I have to move the scroller internally, which might simplify the clipping code too

**Comment by andydotxyz** [comment]
> I think I have to move the scroller internally, which might simplify the clipping code too

Actually this will not be possible until we support clipping of non-scrolling regions (the headers spilled over into other widgets) - went back to fixing graphical improvements based on current PR

**Comment by andydotxyz** [comment]
After testing on Linux I'm not thrilled with the refresh - are other people seeing the sticky cells/headers flickering / moving off their spots?
It's beautiful on macOS 64 (where we have only a single thread for draw/events)

**Comment by andydotxyz** [comment]
Flickering seems to be caused because the scroll events are actioned quickly but the redraw takes a little longer... Two possible approaches to resolve:

1) Move the headers/stuck rows to an overlay which does not move. This would mean that the separators once again overlap the scroll bars...
2) Change all OS to use a single thread for draw and events, simplifying the code base a little and making it more consistent across OS.

1 may be just short lived as this feature could be moved out of the scroller once we have support for clipping non-scrolling widgets. However seeing this tear/jitter made me feel that perhaps we should be creating a more "synced draw" experience for others writing complex widgets?

I will try and follow up with a discussion on Slack to see how to proceed.

**Comment by andydotxyz** [comment]
I have realised that 1. is not actually possible (at least not nicely) - whilst implementing it I realised that it suffers from the same content overspill due to the lack of clipping at the edges when not surrounded by a scroll container :(.

So I propose the second option. The basic diff to revert multithread event/draw would be as follows, though a lot of other tidy up can be completed as a result:

```diff
diff --git a/internal/driver/glfw/driver.go b/internal/driver/glfw/driver.go
index 99d28fadf..ca48f1157 100644
--- a/internal/driver/glfw/driver.go
+++ b/internal/driver/glfw/driver.go
@@ -37,14 +37,11 @@ var (
 // Declare conformity with Driver
 var _ fyne.Driver = (*gLDriver)(nil)
 
-var drawOnMainThread bool // A workaround on Apple M1, just use 1 thread until fixed upstream
-
 type gLDriver struct {
 	windowLock sync.RWMutex
 	windows    []fyne.Window
 	device     *glDevice
 	done       chan interface{}
-	drawDone   chan interface{}
 
 	animation *animation.Runner
 
@@ -173,7 +170,6 @@ func (d *gLDriver) Run() {
 func NewGLDriver() fyne.Driver {
 	d := new(gLDriver)
 	d.done = make(chan interface{})
-	d.drawDone = make(chan interface{})
 	d.animation = &animation.Runner{}
 
 	repository.Register("file", intRepo.NewFileRepository())
diff --git a/internal/driver/glfw/loop.go b/internal/driver/glfw/loop.go
index 33821e4f0..b8d9cc5a6 100644
--- a/internal/driver/glfw/loop.go
+++ b/internal/driver/glfw/loop.go
@@ -31,7 +31,6 @@ type runFlag struct {
 
 // channel for queuing functions on the main thread
 var funcQueue = make(chan funcData)
-var drawFuncQueue = make(chan drawData)
 var run *runFlag
 var initOnce = &sync.Once{}
 var donePool = &sync.Pool{New: func() interface{} {
@@ -74,15 +73,7 @@ func runOnMain(f func()) {
 
 // force a function f to run on the draw thread
 func runOnDraw(w *window, f func()) {
-	if drawOnMainThread {
-		runOnMain(func() { w.RunWithContext(f) })
-		return
-	}
-	done := donePool.Get().(chan struct{})
-	defer donePool.Put(done)
-
-	drawFuncQueue <- drawData{f: f, win: w, done: done}
-	<-done
+	runOnMain(func() { w.RunWithContext(f) })
 }
 
 func (d *gLDriver) drawSingleFrame() {
@@ -120,12 +111,14 @@ func (d *gLDriver) runGL() {
 	if d.trayStart != nil {
 		d.trayStart()
 	}
+
+	settingsChange := make(chan fyne.Settings)
+	fyne.CurrentApp().Settings().AddChangeListener(settingsChange)
 	fyne.CurrentApp().Lifecycle().(*app.Lifecycle).TriggerStarted()
 	for {
 		select {
 		case <-d.done:
 			eventTick.Stop()
-			d.drawDone <- nil // wait for draw thread to stop
 			d.Terminate()
 			fyne.CurrentApp().Lifecycle().(*app.Lifecycle).TriggerStopped()
 			return
@@ -134,6 +127,17 @@ func (d *gLDriver) runGL() {
 			if f.done != nil {
 				f.done <- struct{}{}
 			}
+		case set := <-settingsChange:
+			painter.ClearFontCache()
+			cache.ResetThemeCaches()
+			app.ApplySettingsWithCallback(set, fyne.CurrentApp(), func(w fyne.Window) {
+				c, ok := w.Canvas().(*glCanvas)
+				if !ok {
+					return
+				}
+				c.applyThemeOutOfTreeObjects()
+				go c.reloadScale()
+			})
 		case <-eventTick.C:
 			d.tryPollEvents()
 			newWindows := []fyne.Window{}
@@ -175,10 +179,7 @@ func (d *gLDriver) runGL() {
 				}
 
 				newWindows = append(newWindows, win)
-
-				if drawOnMainThread {
-					d.drawSingleFrame()
-				}
+				d.drawSingleFrame()
 			}
 			if reassign {
 				d.windowLock.Lock()
@@ -217,46 +218,6 @@ func (d *gLDriver) repaintWindow(w *window) {
 	})
 }
 
-func (d *gLDriver) startDrawThread() {
-	settingsChange := make(chan fyne.Settings)
-	fyne.CurrentApp().Settings().AddChangeListener(settingsChange)
-	var drawCh <-chan time.Time
-	if drawOnMainThread {
-		drawCh = make(chan time.Time) // don't tick when on M1
-	} else {
-		drawCh = time.NewTicker(time.Second / 60).C
-	}
-
-	go func() {
-		runtime.LockOSThread()
-
-		for {
-			select {
-			case <-d.drawDone:
-				return
-			case f := <-drawFuncQueue:
-				f.win.RunWithContext(f.f)
-				if f.done != nil {
-					f.done <- struct{}{}
-				}
-			case set := <-settingsChange:
-				painter.ClearFontCache()
-				cache.ResetThemeCaches()
-				app.ApplySettingsWithCallback(set, fyne.CurrentApp(), func(w fyne.Window) {
-					c, ok := w.Canvas().(*glCanvas)
-					if !ok {
-						return
-					}
-					c.applyThemeOutOfTreeObjects()
-					go c.reloadScale()
-				})
-			case <-drawCh:
-				d.drawSingleFrame()
-			}
-		}
-	}()
-}
-
 // refreshWindow requests that the specified window be redrawn
 func refreshWindow(w *window) {
 	w.canvas.SetDirty()
diff --git a/internal/driver/glfw/loop_desktop.go b/internal/driver/glfw/loop_desktop.go
index 1d3620dc5..1d530dfde 100644
--- a/internal/driver/glfw/loop_desktop.go
+++ b/internal/driver/glfw/loop_desktop.go
@@ -5,7 +5,6 @@ package glfw
 
 import (
 	"fmt"
-	"runtime"
 
 	"fyne.io/fyne/v2"
 
@@ -14,10 +13,6 @@ import (
 
 func (d *gLDriver) initGLFW() {
 	initOnce.Do(func() {
-		if runtime.GOOS == "darwin" && runtime.GOARCH == "arm64" {
-			drawOnMainThread = true
-		}
-
 		err := glfw.Init()
 		if err != nil {
 			fyne.LogError("failed to initialise GLFW", err)
@@ -25,7 +20,6 @@ func (d *gLDriver) initGLFW() {
 		}
 
 		initCursors()
-		d.startDrawThread()
 	})
 }
 
diff --git a/internal/driver/glfw/loop_goxjs.go b/internal/driver/glfw/loop_goxjs.go
index e5082800a..c0cc71e55 100644
--- a/internal/driver/glfw/loop_goxjs.go
+++ b/internal/driver/glfw/loop_goxjs.go
@@ -8,8 +8,8 @@ import (
 
 	"fyne.io/fyne/v2"
 
-	gl "github.com/fyne-io/gl-js"
-	glfw "github.com/fyne-io/glfw-js"
+	"github.com/fyne-io/gl-js"
+	"github.com/fyne-io/glfw-js"
 )
 
 func (d *gLDriver) initGLFW() {
@@ -19,8 +19,6 @@ func (d *gLDriver) initGLFW() {
 			fyne.LogError("failed to initialise GLFW", err)
 			return
 		}
-
-		d.startDrawThread()
 	})
 }
 
diff --git a/internal/driver/glfw/window_notlinux.go b/internal/driver/glfw/window_notlinux.go
index ed30559c3..c8f6bd6d0 100644
--- a/internal/driver/glfw/window_notlinux.go
+++ b/internal/driver/glfw/window_notlinux.go
@@ -12,13 +12,6 @@ func (w *window) platformResize(canvasSize fyne.Size) {
 		return
 	}
 
-	if drawOnMainThread {
-		w.canvas.Resize(canvasSize)
-		d.repaintWindow(w)
-	} else {
-		runOnDraw(w, func() {
-			w.canvas.Resize(canvasSize)
-			d.repaintWindow(w)
-		})
-	}
+	w.canvas.Resize(canvasSize)
+	d.repaintWindow(w)
 }
```

**Comment by andydotxyz** [comment]
I am working on a special option 3 which will re-order what we refresh to try and get the top items completed before the other cells, in case this helps at all.

**Comment by andydotxyz** [comment]
Ok, secret option 3 panned out - using a scroller with scrolling turned off to work as a clip rectangle...
Kinda weird but it works well

**Comment by andydotxyz** [comment]
All right... I think it's done!!! 🎉 .

This is a handy little table testing app that may be useful:

```go
package main

import (
	"fmt"
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Table headers")

	t := widget.NewTable(
		func() (int, int) { return 500, 150 },
		func() fyne.CanvasObject {
			return widget.NewLabel("Cell 00, 00")
		},
		func(id widget.TableCellID, cell fyne.CanvasObject) {
			label := cell.(*widget.Label)
			label.SetText(fmt.Sprintf("Cell %d, %d", id.Row+1, id.Col+1))
		})

	var row, col *widget.Check
	row = widget.NewCheck("", func(on bool) {
		t.ShowHeaderRow = on
		row.Refresh()
		t.Refresh()
	})
	col = widget.NewCheck("", func(on bool) {
		t.ShowHeaderColumn = on
		col.Refresh()
		t.Refresh()
	})

	rows := widget.NewRadioGroup([]string{"0", "1", "2", "3"}, func(s string) {
		num, _ := strconv.Atoi(s)
		t.StickyRowCount = num
		t.Refresh()
	})
	rows.Horizontal = true
	rows.SetSelected("0")
	cols := widget.NewRadioGroup([]string{"0", "1", "2", "3"}, func(s string) {
		num, _ := strconv.Atoi(s)
		t.StickyColumnCount = num
		t.Refresh()
	})
	cols.Horizontal = true
	cols.SetSelected("0")

	options := widget.NewForm(
		widget.NewFormItem("Header row", row),
		widget.NewFormItem("Header column", col),
		widget.NewFormItem("Stick rows", rows),
		widget.NewFormItem("Stick columns", cols),
	)

	w.SetContent(container.NewBorder(options, nil, nil, nil, t))
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
> I have noticed an issue with the separator line actually stepping outside of the scroller somehow. Maybe like it doesn't seems to be clipped properly.

Ah the dividers were not clipped, just calculated to fit. Added clipping to handle the fast scroll.

**Review by Bluebugs — APPROVED** [review]
Nice work! This looks good.

**Pull request merged**
