### PR TITLE
Add flags to package cmd

### PR DESCRIPTION
**Pull request by lkebin**
### Description:
Add more flags to package command

- add `androidAPI` flag to set the Android API version
- add `iosVersion` flag to set the minimal version of the iOS SDK

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks for the change. I think it may be potentially dangerous, because changing the minimum SDK for Android (and iOS) can alter how an application functions, and so may break Fyne functionality. Have you been able to test a range of versions?

Would it be possible to provide some more information about what problem this solves so we know how to evaluate it?

We don't really use the constructor options pattern - this is a lot of boiler plate for passing an internal value "sdkVersion" into the builder.

**Comment by andydotxyz** [comment]
(p.s. it looks like this is not really based off `develop` branch, can you please check?)

**Comment by lkebin** [comment]
> (p.s. it looks like this is not really based off `develop` branch, can you please check?)

I was create branch from master. When I submit PR I found need do GitFlow branch model. So I just create a new one from develop branch and merge the old one into.

This should be fine in GitFlow, right ?


> Thanks for the change. I think it may be potentially dangerous, because changing the minimum SDK for Android (and iOS) can alter how an application functions, and so may break Fyne functionality. Have you been able to test a range of versions?
> 
> Would it be possible to provide some more information about what problem this solves so we know how to evaluate it?
> 
> We don't really use the constructor options pattern - this is a lot of boiler plate for passing an internal value "sdkVersion" into the builder.

When I installed NDS from Android Studio, Fyne package command doesn't work with it. 

```
no compiler for arm was found in the NDK (tried /Users/kb/Workspace/sdk/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang). Make sure your NDK version is >= r19c. Use `sdkmanager --update` to update it
```

Seems the latest NDK doens't have default minimal API version compiler (default is 16)

```
$ ls /Users/kb/Workspace/sdk/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/
aarch64-linux-android21-clang      clang-14                           llvm-dwarfdump
aarch64-linux-android21-clang++    clang-check                        llvm-dwp
aarch64-linux-android22-clang      clang-cl                           llvm-lib
aarch64-linux-android22-clang++    clang-format                       llvm-link
aarch64-linux-android23-clang      clang-tidy                         llvm-lipo
aarch64-linux-android23-clang++    clangd                             llvm-modextract
aarch64-linux-android24-clang      dsymutil                           llvm-nm
aarch64-linux-android24-clang++    git-clang-format                   llvm-objcopy
aarch64-linux-android26-clang      i686-linux-android19-clang         llvm-objdump
aarch64-linux-android26-clang++    i686-linux-android19-clang++       llvm-profdata
aarch64-linux-android27-clang      i686-linux-android21-clang         llvm-ranlib
aarch64-linux-android27-clang++    i686-linux-android21-clang++       llvm-rc
aarch64-linux-android28-clang      i686-linux-android22-clang         llvm-readelf
aarch64-linux-android28-clang++    i686-linux-android22-clang++       llvm-readobj
aarch64-linux-android29-clang      i686-linux-android23-clang         llvm-size
aarch64-linux-android29-clang++    i686-linux-android23-clang++       llvm-strings
aarch64-linux-android30-clang      i686-linux-android24-clang         llvm-strip
aarch64-linux-android30-clang++    i686-linux-android24-clang++       llvm-symbolizer
aarch64-linux-android31-clang      i686-linux-android26-clang         llvm-windres
aarch64-linux-android31-clang++    i686-linux-android26-clang++       sancov
aarch64-linux-android32-clang      i686-linux-android27-clang         sanstats
aarch64-linux-android32-clang++    i686-linux-android27-clang++       scan-build
armv7a-linux-androideabi19-clang   i686-linux-android28-clang         scan-view
armv7a-linux-androideabi19-clang++ i686-linux-android28-clang++       x86_64-linux-android21-clang
armv7a-linux-androideabi21-clang   i686-linux-android29-clang         x86_64-linux-android21-clang++
armv7a-linux-androideabi21-clang++ i686-linux-android29-clang++       x86_64-linux-android22-clang
armv7a-linux-androideabi22-clang   i686-linux-android30-clang         x86_64-linux-android22-clang++
armv7a-linux-androideabi22-clang++ i686-linux-android30-clang++       x86_64-linux-android23-clang
armv7a-linux-androideabi23-clang   i686-linux-android31-clang         x86_64-linux-android23-clang++
armv7a-linux-androideabi23-clang++ i686-linux-android31-clang++       x86_64-linux-android24-clang
armv7a-linux-androideabi24-clang   i686-linux-android32-clang         x86_64-linux-android24-clang++
armv7a-linux-androideabi24-clang++ i686-linux-android32-clang++       x86_64-linux-android26-clang
armv7a-linux-androideabi26-clang   ld                                 x86_64-linux-android26-clang++
armv7a-linux-androideabi26-clang++ ld.lld                             x86_64-linux-android27-clang
armv7a-linux-androideabi27-clang   ld64.lld                           x86_64-linux-android27-clang++
armv7a-linux-androideabi27-clang++ lld                                x86_64-linux-android28-clang
armv7a-linux-androideabi28-clang   lld-link                           x86_64-linux-android28-clang++
armv7a-linux-androideabi28-clang++ lldb                               x86_64-linux-android29-clang
armv7a-linux-androideabi29-clang   lldb-argdumper                     x86_64-linux-android29-clang++
armv7a-linux-androideabi29-clang++ lldb.sh                            x86_64-linux-android30-clang
armv7a-linux-androideabi30-clang   llvm-addr2line                     x86_64-linux-android30-clang++
armv7a-linux-androideabi30-clang++ llvm-ar                            x86_64-linux-android31-clang
armv7a-linux-androideabi31-clang   llvm-as                            x86_64-linux-android31-clang++
armv7a-linux-androideabi31-clang++ llvm-cfi-verify                    x86_64-linux-android32-clang
armv7a-linux-androideabi32-clang   llvm-config                        x86_64-linux-android32-clang++
armv7a-linux-androideabi32-clang++ llvm-cov                           yasm
clang                              llvm-cxxfilt
clang++                            llvm-dis
```

After check the gomobile code, it provide `-androidapi` flag for specific Android API, so I think could expose this flag to package command too.

I think this doesn't break anything, the new flags have same default value with gomobile. If user doesn't specific them in command line, it works as the before. 

I could replace constructor option with parameter directly soon, or add separate RunNewBuild function for iOS and Android ?

**Comment by andydotxyz** [comment]
> So I just create a new one from develop branch and merge the old one into.

I don't know, I've not merged like that before - cherry picking the commits onto the new branch might have been cleaner.
Possibly something else is not working correctly, I will look into it.

> I think this doesn't break anything, the new flags have same default value with gomobile. If user doesn't specific them in command line, it works as the before.

When you compile against a higher minimum version Android will remove compatibility layers - and so the functionality compiled could change and/or break. Is Google making it impossible to install that version, or is it now off by default?

**Comment by andydotxyz** [comment]
It looks like we missed this: https://android-developers.googleblog.com/2021/07/google-play-services-discontinuing-jelly-bean.html

Now Google is forcing us to drop some devices just like Apple did with iOS 32bit. It makes me sad but maybe we can't do anything about it...

**Comment by lkebin** [comment]
I just create a new PR for fixes base branch, also replaced functional options to parameter list. #2922

> Is Google making it impossible to install that version, or is it now off by default?

Seems it is possible to install an old version of NDK separately, but impossible from Android Studio
refer to: https://github.com/android/ndk/wiki/Unsupported-Downloads

Expose more gomobile flags won't break anything by default, the flags default value is same as gomobile flags.

**Comment by andydotxyz** [comment]
I agree that exposing a configuration flag by default does not break things. But passing a value like "21" to it will likely break how some Fyne internals work, which worries me a lot.

**Comment by lkebin** [comment]
> I agree that exposing a configuration flag by default does not break things. But passing a value like "21" to it will likely break how some Fyne internals work, which worries me a lot.

OK

If we don't expose flags, we'd better add description to document, to make new user clearly that Fyne can works only with Android API 16.

**Comment by andydotxyz** [comment]
Let's pick it up on the open PR

**Pull request closed without merging**
